### PR TITLE
Present nicer error messages in GTests

### PR DESCRIPTION
**Pull request by sethfowler**
This PR makes the GTests that include P4 source use raw strings (which makes them easier to define and nicer to read) and adds a helper macro that prepends a `#line` directive to the source so that error messages point to the right location.

Making this work required handling the global state related to source locations a little more robustly.

I've also moved the GTest helper functions (now we have 2, and I'm sure there'll be more) to a .cpp file. The current approach will cause errors if we `#include helpers.h` in more than one (non-unified) source file.

### CODE REVIEW

**Comment by hanw** [comment]
travis is not happy though.

**Comment by sethfowler** [comment]
There's a cpplint error, and the old version of GCC we're using on Travis also seems a bit more picky about raw strings. I'll fix the errors.

**Comment by sethfowler** [comment]
The "unterminated raw string" issue is an actual [GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55971). Since we're in the process of moving our tests to run on Ubuntu 16.04 anyway, which include a newer version of GCC that doesn't have this bug, I'll hold off on merging this for now.

**Comment by mbudiu-vmw** [comment]
Since not everyone has the same version of Ubuntu or gcc, maybe it's useful to 
- either check in configure the wrong version of gcc
- avoid of merging this altogether

**Comment by sethfowler** [comment]
We support specific versions of Ubuntu and GCC; as much as it would be great to be able to support every compiler and OS version out there, we just don't have the resources to do it.

**Comment by mbudiu-vmw** [comment]
If you don't support it it would be nice for ./configure to say it. Or at the very least the README.

**Comment by sethfowler** [comment]
Yeah, I agree. We'll update the README when the changeover happens. And in general, we need to make `configure` smarter about pointing out possible issues, and that includes compiler versions. I'll add that to my to-do list.

**Pull request merged**
