### PR TITLE
Save the key names in @name annotations: fix for issue #259

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
This fixes issue #259 by preserving the key names for all tables using @name annotations.
This has to be run very early in the front-end, before doing any renaming; otherwise identifier names may change.
This does not really solve the problem, but it just passes the buck to issue #219. We should use these @name annotations when generating the PI.
Unfortunately most reference outputs have changed.

### CODE REVIEW

**Comment by cc10512** [comment]
I am puzzled why we need to hand annotate _all_ these names manually, and essentially repeat the name for the key in a @name annotation. The front end should be able to generate the annotations before any transformation, and then we would need/require hand annotations only for expressions or other corner cases.

**Comment by mbudiu-vmw** [comment]
They are not annotated manually; the -first.p4 and -midend.p4 files are actually generated by the compiler exactly as you describe. They contain the program representation at a specific point in the compiler pipeline.

**Comment by mbudiu-vmw** [comment]
@ChrisDodd: There's no nullptr cstring, so I didn't know how to do it less verbose. I would appreciate a suggestion.

**Comment by cc10512** [comment]
Oh, I missed that these were "samples". Thanks for pointing it out.

**Comment by ChrisDodd** [comment]
cstring() is a "nullptr" cstring -- the explicit cstring::operator bool()
method returns false for this (and only this) cstring.  It is distinct from
cstring("") which is an empty string (and for which operator bool returns
true)

**Pull request merged**
