### PR TITLE
Mark tests as xfailed due issue #486 - to be fixed

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
This is required for the testsuite to pass with the latest build of the behavioral model.

### CODE REVIEW

**Comment by jafingerhut** [comment]
You beat me to it, Mihai.  Those are exactly the 3 files that I expect to be XFAIL because of Antonin's recent changes in bmv2.  Thanks.

**Comment by sethfowler** [comment]
(If I'm wrong, @jafingerhut, please request changes. I'm just trying to let @mbudiu-vmw land all his PRs. =)

**Comment by jafingerhut** [comment]
Sorry, didn't know I was requested for approval.  I do, with no further changes.

**Comment by sethfowler** [comment]
Closing this because the patch landed in #1068.

**Pull request closed without merging**
