### PR TITLE
Made all slices unsigned

### PR DESCRIPTION
**Pull request by liujed**
Seeing what breaks.

### CODE REVIEW

**Comment by liujed** [comment]
It looks like slices have been preserving signedness for at least as long as this repo has been in existence: https://github.com/p4lang/p4c/blob/bc7b75bd1892ab230c2ec2d125af8529cf092f4a/frontends/p4/typeChecking/typeChecker.cpp#L1448

**Comment by mbudiu-vmw** [comment]
This looks fine.

**Comment by liujed** [comment]
I will wait to merge this until we've had a chance to discuss its effects in the next LDWG meeting. As I've mentioned, this changes undocumented behaviour that has been around for at least a few years, and runs the risk of breaking existing programs.

**Comment by mbudiu-vmw** [comment]
Please supply a PR against the spec as well.

**Pull request merged**
