### PR TITLE
fix for issue 1923: assignments in ingress apply block not represented

### PR DESCRIPTION
**Pull request by hanw**

### CODE REVIEW

**Comment by jafingerhut** [comment]
I am surprised Mihai didn't ask for the front/midend/etc. expected compiler outputs before I mentioned them :-)  I will do some local testing with these changes to see if they work as advertised.  I scanned through the code changes, but as is common I do not know the code well enough to spot anything wrong that way.

**Comment by jafingerhut** [comment]
The test program I wrote, and that you include in the PR, fails for me, with output from psa_switch like this:
```
[15:42:24] $ ./bmv2/testdata/p4_16_samples/psa-simple-reflector-bmv2.p4.test
Check for  /home/jafinger/forks/p4c/testdata/p4_16_samples/psa-simple-reflector-bmv2.stf
Calling target program-options parser
Invalid reference to object of type 'header' with name 'scalars'
*** Test failed
```
which is the same error message for issue https://github.com/p4lang/p4c/issues/1919 and I suspect semi-independent of the issue where top-level assignments in the ingress/egress control are not appearing in the BMv2 JSON file.

**Comment by jafingerhut** [comment]
If the p4c code changes are good, though, perhaps the best approach is to remove the failing test program from the PR.

Maybe I can find a different test program that breaks without these changes, and works with them, but I don't think that should hold up the PR.

**Comment by jafingerhut** [comment]
I found a slightly different test program and STF file that fails without these changes, and passes with them.  Attaching them to this comment.
[psa-top-level-assignments-bmv2.p4.txt](https://github.com/p4lang/p4c/files/3267955/psa-top-level-assignments-bmv2.p4.txt)
[psa-top-level-assignments-bmv2.stf.txt](https://github.com/p4lang/p4c/files/3267956/psa-top-level-assignments-bmv2.stf.txt)

**Comment by hanw** [comment]
There seems to be another bug related to 'scalars' field in generated json. I am using the test program in issue 1919 to debug the issue.

**Comment by hanw** [comment]
It's not clear to me what types of fields should be counted as 'scalar'.

**Comment by mbudiu-vmw** [comment]
BMv2 supports only header and struct instances. Everything else (e.g., local variables) is packed in a "scalars" struct.

**Comment by jafingerhut** [comment]
Certainly very happy if you would like to fix both issues in the same PR, Han, but fixing one but not the other also seems like a viable option to me.

**Pull request closed without merging**
