### PR TITLE
add a feature to control logging via an annotation on annotated IR ob…

### PR DESCRIPTION
**Pull request by hanw**
…ject only

To use this feature, backend can set the enableLoggingGlobally to false based on a command line flag or a custom annotation, and set the enableLoggingInContext to true on the annotated IR class. 

This helps to filter excessive logging in our backend to focus on certain instance of IR class that is touched by a pass.

### CODE REVIEW

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by mbudiu-vmw** [comment]
Don't forget to clang-format

**Comment by fruffy** [comment]
If you install pip3 install --user "clang-format==15.0.4" and then run `make clang-format-fix-errors` you should get the same result as what CI checks for. 

The MacOS tests are failing for an unrelated reason, which needs to be fixed.

**Comment by hanw** [comment]
Looks like the macos issue is gating a few other PRs as well?

**Comment by fruffy** [comment]
I think right now PRs can still be merged despite the test failing.

**Pull request merged**
