### PR TITLE
Fix for issue #510

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by ChrisDodd** [comment]
It might make sense (for some targets where bits are a premium) to try to figure out the minimum number of bits to use for an error code (to allow all declared errors to have a distinct code), rather than just using 32, but that seems like significantly more work?

**Comment by mbudiu-vmw** [comment]
The 32 bit size was hardwired by @hanw.
I only made it a constant.
This code is in the bmv2 back-end, and not in a reusable pass. We probably should have a mid-end pass for this purpose, which would work a lot like the enum conversion pass, by taking a policy class.

**Comment by hanw** [comment]
wasn't me =), the 32 bit was there before the refactoring. but I agree with the policy class approach.

**Comment by mbudiu-vmw** [comment]
In fact it was @antoninbas with this commit: https://github.com/p4lang/p4c/commit/6c3f06aef57bf794403591c1d22e48b08f0395e9
Sorry for the mis-attribution.

**Pull request merged**
