### PR TITLE
Expand side-effect computations in table keys

### LINKED ISSUE #2546: Side-effect function call in table key
I am not sure what the decision of allowing or forbidding function calls in keys and actions is currently. Depending on the outcome this issue may not matter but I recorded it just for completeness sake. 
The following program

```p4
control ingress(inout Headers h) {
    @noWarn("unused") @name(".NoAction") action NoAction_0() {
    }
    @noWarn("unused") @name(".NoAction") action NoAction_3() {
    }
    @name("ingress.simple_table_1") table simple_table {
        key = {
            48w1: exact @name("KOXpQP") ;
        }
        actions = {
            @defaultonly NoAction_0();
        }
        default_action = NoAction_0();
    }
    @name("ingress.simple_table_2") table simple_table_0 {
        key = {
            (simple_table.apply().hit ? 8w1 : 8w2): exact @name("key") ;
        }
        actions = {
            @defaultonly NoAction_3();
        }
        default_action = NoAction_3();
    }
    apply {
        if (simple_table_0.apply().hit) {
            h.eth_hdr.dst_addr = 48w1;
        }
    }
}
```
is transformed into

```p4
control ingress(inout Headers h) {
    @noWarn("unused") @name(".NoAction") action NoAction_0() {
    }
    @noWarn("unused") @name(".NoAction") action NoAction_3() {
    }
    bit<48> key_0;
    @name("ingress.simple_table_1") table simple_table {
        key = {
            key_0: exact @name("KOXpQP") ;
        }
        actions = {
            @defaultonly NoAction_0();
        }
        default_action = NoAction_0();
    }
    bit<8> key_1;
    @name("ingress.simple_table_2") table simple_table_0 {
        key = {
            key_1: exact @name("key") ;
        }
        actions = {
            @defaultonly NoAction_3();
        }
        default_action = NoAction_3();
    }
    apply {
        {
            key_1 = (simple_table.apply().hit ? 8w1 : 8w2);
            if (simple_table_0.apply().hit) {
                h.eth_hdr.dst_addr = 48w1;
            }
        }
    }
}
```
which causes `simple_table_1` to match on a key with undefined behavior. This call is side-effect free from what I can tell.

For what it is worth changing the key from `48w1` to something like `h.eth_hdr.eth_type` leads to a compiler bug. 

[nested_tbl_apply.p4.txt](https://github.com/p4lang/p4c/files/5217828/nested_tbl_apply.p4.txt)
[nested_tbl_apply_crash.p4.txt](https://github.com/p4lang/p4c/files/5217829/nested_tbl_apply_crash.p4.txt)

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
This pass is now part of the side-effect ordering mega-pass.
The new part is the KeySideEffect, which lifts complex key computations into statements invoked before a table application.
What makes this tricky is that table applications can be part of other expressions, including... other table key computations. So the pass is careful to expand the keys in the right order so that it always knows where to insert the newly created additional statements. There is an example in issue2546-2.p4 which illustrates the complexities.
I have also moved some code that is common between this pass and midend/simplifyKey.h into the sideEffect.h file.
Fixes #2546.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Fixes #2362

**Comment by mbudiu-vmw** [comment]
Fixes #2258

**Comment by fruffy** [comment]
Cannot comment a whole lot on the code in the side-effect ordering pass, but I will fuzz this.

**Comment by mbudiu-vmw** [comment]
You already filed 3 issues that have been solved by this.

**Comment by fruffy** [comment]
Yes, so I was planning to make sure that there is no new variation that new emerges or has not been covered.

**Review by fruffy — COMMENTED** [review]
Fuzzing has not revealed anything related to this pull request. I guess #2266 will be dealt with separately? 
Will give this a proper review in the next couple of days.

**Review by fruffy — APPROVED** [review]
I looked at this before but I can not really say much about the quality of the implementation. I do not know the side-effect ordering pass that well. However, I did not see any logic errors or mistakes.

**Pull request merged**
