### PR TITLE
Remove XFAIL for two PSA test programs that should now pass

### PR DESCRIPTION
**Pull request by jafingerhut**
given recent changes in p4lang/behavioral-model code for PSA
implementation.

### CODE REVIEW

**Comment by jafingerhut** [comment]
If the automated tests for this PR pass, it should be merged ASAP.  p4lang/behavioral-model was recently enhanced so that these 2 test programs STF tests now pass, so until this is merged, automated tests for all p4c PRs will fail.

**Comment by mbudiu-vmw** [comment]
It looks like the bmv2 changes have been propagated; perhaps you can rerun travis so we can merge this.

**Comment by jafingerhut** [comment]
I will give it another go, and keep my fingers crossed this time.

**Comment by mbudiu-vmw** [comment]
There are no more changes to XFAIL. What do we do with this PR?

**Comment by jafingerhut** [comment]
I am going to merge it.  This PR was poorly named.  The updated tests are failing, because they are more accurate tests than the previous ones, which should still fail because psa_switch has bugs.

**Pull request merged**
