### PR TITLE
Split psa_switch.h into two files

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

This is not really the desired final result, but it is a test that the bmv2-specific parts can be separated from the psa-specific parts of the code. The psa-specific parts should be reused by multiple backends. Probably we should move them to some architecture/ directory.

@osinstom can you see whether this structure removes all bmv2 dependencies from the ebpf backend (except psaProgramStructure.h)?

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Today the p4c code structure does not have separate directories for architectures (models?) and targets. 
The code specific to an architecture essentially validates that the code is written for the correct architecture and extracts all relevant information for code-generation. Code-generation is target-specific, and should only read the extracted information.

**Comment by osinstom** [comment]
@mbudiu-vmw thanks for investigating this. I'm getting exactly the same error as on CI: https://github.com/p4lang/p4c/runs/5654254563?check_suite_focus=true. 

```
/home/dev/workspace/p4c-1/backends/bmv2/psa_switch/psaProgramStructure.cpp: In member function ‘virtual bool BMV2::InspectPsaProgram::preorder(const IR::Parameter*)’:
/home/dev/workspace/p4c-1/backends/bmv2/psa_switch/psaProgramStructure.cpp:193:9: error: ‘PsaSwitchExpressionConverter’ has not been declared
  193 |     if (PsaSwitchExpressionConverter::isStandardMetadata(ptName)) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by rst0git** [comment]
> @mbudiu-vmw thanks for investigating this. I'm getting exactly the same error as on CI: https://github.com/p4lang/p4c/runs/5654254563?check_suite_focus=true.
> 
> ```
> /home/dev/workspace/p4c-1/backends/bmv2/psa_switch/psaProgramStructure.cpp: In member function ‘virtual bool BMV2::InspectPsaProgram::preorder(const IR::Parameter*)’:
> /home/dev/workspace/p4c-1/backends/bmv2/psa_switch/psaProgramStructure.cpp:193:9: error: ‘PsaSwitchExpressionConverter’ has not been declared
>   193 |     if (PsaSwitchExpressionConverter::isStandardMetadata(ptName)) {
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

`isStandardMetadata()` is defined in `psaSwitch.h`.

**Comment by rst0git** [comment]
> The psa-specific parts should be reused by multiple backends. Probably we should move them to some architecture/ directory.

Sounds good to me.

**Comment by mbudiu-vmw** [comment]
Hopefully my new commit has fixed the missing class problem.

**Comment by osinstom** [comment]
@mbudiu-vmw I confirm that PSA-eBPF compiles successfully with the set of dependencies that I've pasted above. Feel free to merge this, so that I can rebase and apply these modifications to #3139.

**Comment by mbudiu-vmw** [comment]
Will do once CI tests are finished

**Review by rst0git — APPROVED** [review]
LGTM

**Pull request merged**
