### PR TITLE
Update version to match language specification

### PR DESCRIPTION
**Pull request by jnfoster**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
It looks like the checks have completed, but github has not found out yet.

**Comment by jnfoster** [comment]
Huh. Is there a way to tell GitHub/Travis to try again other than pushing a trivial commit?

**Comment by cc10512** [comment]
Yes, one can restart the Travis job. I just did.

**Comment by jnfoster** [comment]
Thank you!

**Pull request merged**
