### PR TITLE
Fix for issue #1020

### PR DESCRIPTION
**Pull request by AlexBernstein**
Statements like the one below are ignored in SimplifyKey midend pass when applying insertions
`hit = table.apply().hit;`

### CODE REVIEW

**Comment by ChrisDodd** [comment]
I think this is correct, but it would be nice to have a testcase.

**Comment by mbudiu-vmw** [comment]
Thank you. This is nice. The protocol is to run 'make check' and then submit all the files that have appeared in the 'testcase' folder. These are reference outputs that make sure that the compiler always does the same thing.

**Comment by AlexBernstein** [comment]
Added a test case by modifying existing key-ebpb.p4 test to make key complex and force the move. in the midend output complex keys in the table definition get replaced by key_0 and key_1, and declarations are added before the table. However, assignments
```
key_0 = headers.ipv4.srcAddr + 1;
key_1 = headers.ipv4.dstAddr +1; 
```
are missing. They should appear before the `tmp_0 = t.apply().hit;`

**Comment by AlexBernstein** [comment]
Added a test case by modifying existing key-ebpf.p4 test to make key complex and force the move. in the midend output complex keys in the table definition get replaced by key_0 and key_1, and declarations are added before the table. However, assignments
```
key_0 = headers.ipv4.srcAddr + 1;
key_1 = headers.ipv4.dstAddr + 1; 
```
are missing. They should appear before the `tmp_0 = t.apply().hit;`

**Comment by mbudiu-vmw** [comment]
Yes, that is exactly what the reference outputs would be conveying.

**Comment by AlexBernstein** [comment]
Sorry, first time submitting. I've run the 'make check', but having trouble finding the folder with the generated output. Is it somewhere in the 'build' directory?

**Comment by mbudiu-vmw** [comment]
run 'cmake ..', then 'make check -j4', and then 'git status'
You will see some new p4 files that you should commit.

**Comment by mbudiu-vmw** [comment]
Thank you. If the Travis build completes successfully we'll merge this.

**Pull request merged**
