### PR TITLE
Fix: Links in Generated Documentation

### PR DESCRIPTION
**Pull request by AdarshRawat1**
For better Presentation of content in generated documentation.

## Changes 

- [x] Enabled GitHub Markdown Style TOC  (i.e. TOC given in README was no functional in generated output.)
- [x] Generated Relative link fixes to non README files and PPTs/PDF.
- [x] Docs : Added P4 Coding Standard Philosophy to Docs 
- [x] Fix : Sequence of IR introduction in docs
- [x] Fix: relative linking to subsections in Doxygen output 

### on Main Page [P4 Compiler Documentation]

- Card links on "p4 Compiler Onboarding" and "Getting Started" 

### on Repository Page 
- migration guide
- compiler design
- "guidelines" link https://p4lang.github.io/p4c/CodingStandardPhilosophy.md#git-commits-and-pull-requests
- "guidelines" link https://p4lang.github.io/p4c/CodingStandardPhilosophy.md#handling-errors

### on P4C Page 
- CI installation script link 
- dependencies installation script
- "rule" link
- bazel/example
- "unsupported P4_16 language features" link https://p4lang.github.io/p4c/backends/bmv2/README.md#unsupported-p4_16-language-features

### CODE REVIEW

**Comment by fruffy** [comment]
Is this ready for review?

**Comment by AdarshRawat1** [comment]
> Is this ready for review?

Filtering the repo to find more, to avoid extra PRs.

**Comment by jafingerhut** [comment]
So the primary way that I know to review fixes for broken links is to wait until a PR like this is merged in, wait a little while until the doxygen task runs to generate new output from the changes, and then look at those.

I do not mind learning how to take a PR and locally, on my own development system, run doxygen on the changes and look at them on my local system.  Are there step-by-step instructions for doing that somewhere?

**Comment by jafingerhut** [comment]
This newly created issue summarizes my confusion with how to use doxygen on p4c: https://github.com/p4lang/p4c/issues/4805

**Comment by AdarshRawat1** [comment]
> So the primary way that I know to review fixes for broken links is to wait until a PR like this is merged in, wait a little while until the doxygen task runs to generate new output from the changes, and then look at those.
> 
> I do not mind learning how to take a PR and locally, on my own development system, run doxygen on the changes and look at them on my local system. Are there step-by-step instructions for doing that somewhere?


Yes, you can test the PR locally by checking out this PR.

- Fetch the PR by using ` git fetch upstream pull/PR_ID/head ` 
Example for this PR- 
```bash 
git fetch upstream pull/4793/head   
```

- Check out 
```bash
git checkout FETCH_HEAD
```

**Review by jafingerhut — APPROVED** [review]
LGTM

**Comment by jafingerhut** [comment]
Given that these changes are fairly small and focused, and that it is easier to see what is fixed in the docs once the changes are merged in (yes, I know I can try out the changes locally on my system from the PR, without it being merged in), I would like to see this merged in, so we can look for issues in the generated docs after these changes are merged.

If we end up with one or two extra PRs, I do not think that is a big issue, relative to knowing what we have generated from the latest main branch version of all files.

**Pull request merged**
