### PR TITLE
adding tests re the driver (1) missing error messages and (2) giving misleading error messages

### PR DESCRIPTION
**Pull request by Abe149**
Added four tests of the compiler driver to check that it is outputting good error messages for bad CLI inputs.

These tests are all expected to fail until my recent improvements to the driver are merged, so for now these tests are “XFAIL”s that are labeled as such; those tests are being permitted to not “break the build” by using “WILL_FAIL” in the “set_tests_properties” invocations in {repo.}/“tools/driver/CMakeLists.txt”.

My improvements to the driver are in a branch currently named “Abe149/002___fixing_driver_re_misleading_error_messages_re_multiple_CLI_args_that_look_to_the_driver_like_P4_source-file_pathnames”.

### CODE REVIEW

**Review by hanw — APPROVED** [review]

**Comment by Abe149** [comment]
I rebased onto an updated "main" just a minute or two ago...  that`s why the new commit hash ("92164b2"... instead of "443c9ce"...).

**Comment by mbudiu-vmw** [comment]
Yes, but there should be 1 commit, not 22.

**Comment by Abe149** [comment]
### draft commit message for a squashed commit/merge...


Added four tests of the compiler driver to check that it is outputting good error messages for bad CLI inputs.

These tests are all expected to fail until my recent improvements to the driver are merged, so for now these tests are “XFAIL”s that are labeled as such; those tests are being permitted to not “break the build” by using “WILL_FAIL” in the “set_tests_properties” invocations in {repo.}/“tools/driver/CMakeLists.txt”.

My improvements to the driver are in a branch currently named “Abe149/002___fixing_driver_re_misleading_error_messages_re_multiple_CLI_args_that_look_to_the_driver_like_P4_source-file_pathnames”.

**Comment by Abe149** [comment]
@mbudiu-vmw "_Yes, but there should be 1 commit, not 22._": understood and agreed.  I`m working on some finishing touches and allowing the CI/CD to retest.  Once that is done, I will ask Han to recheck and re-approve [on Monday, I think].  Thanks for your feedback.

**Comment by hanw** [comment]
Is this ready to merge?

**Review by hanw — APPROVED** [review]
LGTM

**Pull request merged**
