### PR TITLE
[P4Tools] Clean up use of ::P4 prefix for errors, warnings, and logs.

### PR DESCRIPTION
**Pull request by fruffy**

### CODE REVIEW

**Comment by fruffy** [comment]
Unclear why p4c-lint is failing. The formatter makes no changes locally...

**Comment by vlstill** [comment]
> Unclear why p4c-lint is failing. The formatter makes no changes locally...

Maybe mismatch in `clang-format` version or some problem with local config? The CI log shows the errors and they make sense to me.

**Review by vlstill — APPROVED** [review]
Looks good, thank you.

**Comment by fruffy** [comment]
> Maybe mismatch in `clang-format` version or some problem with local config? The CI log shows the errors and they make sense to me.

I made sure the clang-format versions are the same.

**Comment by fruffy** [comment]
> > Maybe mismatch in `clang-format` version or some problem with local config? The CI log shows the errors and they make sense to me.
> 
> I made sure the clang-format versions are the same. Maybe it doesn't pick up the config correctly.

The problem was that the branch was opened from a different repository... Should be fixed now.

**Review by vlstill — APPROVED** [review]

**Review by vlstill — APPROVED** [review]

**Pull request merged**
