### PR TITLE
Remove tenjin Python package from Docker dependencies

### PR DESCRIPTION
**Pull request by antoninbas**
tenjin installation seems to be creating issues in CI. It is unclear whether
this is because of tenjin or pip, but nothing in this repo uses tenjin anyway.

### CODE REVIEW

**Comment by cc10512** [comment]
Looks like if not tenjin, then pyroute2 ... 18.04 then? Custom pip?

**Comment by jafingerhut** [comment]
Looks like tenjin isn't the culprit.  The list of Ubuntu packages installed in the Dockerfile has some differences from what is recommended in the p4c/README.md.  e.g. python-setuptools is installed by Dockerfile, but is mentioned nowhere in the p4c/README.md.  I don't know which package install is actually failing from the error messages, though.

**Comment by antoninbas** [comment]
Let me try to upgrade pip.

**Comment by jafingerhut** [comment]
Is it significant that early log output shows several mentions of "trusty" (Ubuntu 14.04) but later package installations all mention "xenial" (Ubuntu 16.04)?

**Comment by antoninbas** [comment]
> Is it significant that early log output shows several mentions of "trusty" (Ubuntu 14.04) but later package installations all mention "xenial" (Ubuntu 16.04)?

No, it just means that the Host OS (Travis VM) is Ubuntu 14.04, but the docker image uses Ubuntu 16.04.

**Comment by antoninbas** [comment]
Replaced by https://github.com/p4lang/p4c/pull/1931

**Pull request closed without merging**
