### PR TITLE
Distinguish runner OS.

### PR DESCRIPTION
**Pull request by fruffy-g**

### CODE REVIEW

**Review by vlstill — APPROVED** [review]

**Comment by vlstill** [comment]
Is this error related to this fix? https://github.com/p4lang/p4c/actions/runs/8100632186/job/22139073840

**Comment by asl** [comment]
> Is this error related to this fix? https://github.com/p4lang/p4c/actions/runs/8100632186/job/22139073840

Looks like this

**Comment by fruffy** [comment]
> Is this error related to this fix? https://github.com/p4lang/p4c/actions/runs/8100632186/job/22139073840

Yes, I am simply guessing it was a cache issue,but I thought `runner.os` would distinguish. If this does not work, I need to figure out why the M1 homebrew can not find that particular boost version all of a sudden. It seems supported:
https://formulae.brew.sh/formula/boost

**Comment by asl** [comment]
> Yes, I am simply guessing it was a cache issue, although I thought `runner.os` would already distinguish them. If this does not work, I need to figure out why the M1 homebrew can not find that particular boost version all of a sudden. It seems supported:

Yes:
```
brew info boost
==> boost: stable 1.84.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/opt/homebrew/Cellar/boost/1.83.0 (16,038 files, 508.4MB) *
```

**Comment by fruffy** [comment]
Yeah `runner.os` returns macOS here, so it must have been a cache conflict. I believe the cache paths are correct.

**Comment by asl** [comment]
@fruffy Does not seem to help. It looks like `brew` is already pre-installed in the image. Maybe we'd need to do `brew update` explicitly before installation.

**Pull request merged**
