### PR TITLE
Do not call super::visit

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Fixes #2541

**Comment by hesingh** [comment]
Should we make the change in upbf backend as well to keep the code consistent between the two backends?

**Comment by mbudiu-vmw** [comment]
First you should test this and see if it works for you. Feel free to submit a PR against the ubpf back-end and ask for a review.

**Comment by hesingh** [comment]
Ok, let me test right away, thanks.

**Comment by mbudiu-vmw** [comment]
I think this can be tested without making any changes to the model, just by inserting some assignments statements in the parser.

**Comment by hesingh** [comment]
I tested this fix and it works.

**Comment by hesingh** [comment]
> I think this can be tested without making any changes to the model, just by inserting some assignments statements in the parser.

In a P4 program, I did declare a local variable at the top of the parser and set the variable equal to zero in a parser state.  The p4c ebpf backend ebpfParser.cpp preorder(const IR::AssignmentStatement*) is not hit.  This means a pass already removed the local variable in the parser.  However, since ebpf model has "headers" as a parameter to the parser, one could set a header field to a value in a parser state and test this PR's code change.  You could add such a test case.

**Review by ChrisDodd — APPROVED** [review]

**Pull request merged**
