### PR TITLE
LocalCopyProp fix for abstract functions

### PR DESCRIPTION
**Pull request by ChrisDodd**
- abstract function calls might call any concrete function defined in
  the target object.
- propagate reads/writes from callee to caller properly.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
This is related to #1284. I think we need a real way to solve this at the language level, perhaps using some annotations. My proposal there was to use a `@synchronous(callers)` annotation on *callees* to indicate who may call them and when. I still think this is sound. If a method is not tagged as `@synchronous` then it is not allowed to capture any variables.

**Comment by mbudiu-vmw** [comment]
It's not about blocking, it's about when they are being called.
`@synchronous(caller) void callee()` means that callee is only called by caller when caller executes, and the caller is expected to execute in the context of a packet.
It cannot be invoked by any other method, or, most importantly, by the control-plane.

**Comment by mbudiu-vmw** [comment]
We should bring this to the design meetings.

**Comment by ChrisDodd** [comment]
If we do add annotations it makes more sense to do it the other way around (eg, `@may_call(callee) abstract void caller();` since generally functions have no idea when they might be called.

**Comment by ChrisDodd** [comment]
Superceded by #1284

**Pull request closed without merging**
