### PR TITLE
Also include the backend IR files in the ir-generated library file.

### LINKED ISSUE #3984: Broken p4c build because of recent change
I have a build of p4c that started breaking today:
```
2023-04-19T01:58:15.1136240Z Scanning dependencies of target p4c-bm2-psa
2023-04-19T01:58:15.1279690Z [ 87%] Building CXX object backends/bmv2/CMakeFiles/p4c-bm2-psa.dir/psa_switch/main.cpp.o
2023-04-19T01:58:37.4412524Z [ 87%] Building CXX object backends/bmv2/CMakeFiles/p4c-bm2-psa.dir/psa_switch/midend.cpp.o
2023-04-19T01:59:01.8426055Z [ 88%] Building CXX object backends/bmv2/CMakeFiles/p4c-bm2-psa.dir/psa_switch/psaSwitch.cpp.o
2023-04-19T01:59:31.6954983Z [ 88%] Building CXX object backends/bmv2/CMakeFiles/p4c-bm2-psa.dir/psa_switch/psaProgramStructure.cpp.o
2023-04-19T01:59:51.6638714Z [ 88%] Building CXX object backends/bmv2/CMakeFiles/p4c-bm2-psa.dir/psa_switch/options.cpp.o
2023-04-19T02:00:06.2884435Z [ 89%] Linking CXX executable p4c-bm2-psa
2023-04-19T02:00:13.9224961Z [91m../../ir/libir.a(visitor.cpp.o):visitor.cpp:function Visitor::visit(IR::DpdkDeclaration const*&, char const*): error: undefined reference to 'typeinfo for IR::DpdkDeclaration'
2023-04-19T02:00:13.9225859Z ../../ir/libir.a(visitor.cpp.o):visitor.cpp:function Visitor::visit(IR::DpdkDeclaration const*&, char const*, int): error: undefined reference to 'typeinfo for IR::DpdkDeclaration'
2023-04-19T02:00:13.9226696Z ../../ir/libir.a(visitor.cpp.o):visitor.cpp:function Visitor::visit(IR::DpdkExternDeclaration const*&, char const*): error: undefined reference to 'typeinfo for IR::DpdkExternDeclaration'
2023-04-19T02:00:13.9227549Z ../../ir/libir.a(visitor.cpp.o):visitor.cpp:function Visitor::visit(IR::DpdkExternDeclaration const*&, char const*, int): error: undefined reference to 'typeinfo for IR::DpdkExternDeclaration'
2023-04-19T02:00:13.9228356Z ../../ir/libir.a(visitor.cpp.o):visitor.cpp:function Visitor::visit(IR::DpdkHeaderType const*&, char const*): error: undefined reference to 'typeinfo for IR::DpdkHeaderType'
2023-04-19T02:00:13.9229149Z ../../ir/libir.a(visitor.cpp.o):visitor.cpp:function Visitor::visit(IR::DpdkHeaderType const*&, char const*, int): error: undefined reference to 'typeinfo for IR::DpdkHeaderType'
2023-04-19T02:00:13.9230310Z ../../ir/libir.a(visitor.cpp.o):visitor.cpp:function Visitor::visit(IR::DpdkStructType const*&, char const*): error: undefined reference to 'typeinfo for IR::DpdkStructType'
2023-04-19T02:00:13.9231101Z ../../ir/libir.a(visitor.cpp.o):visitor.cpp:function Visitor::visit(IR::DpdkStructType const*&[0m[91m, char const*, int): error: undefined reference to 'typeinfo for IR::DpdkStructType'
...
```

As can be seen above, I get many errors when `p4c-bm2-psa` is being linked.

To build p4c, I use g++-9 and the following command:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_FLAGS:STRING=-O3 -DENABLE_GTESTS=OFF -DENABLE_EBPF=OFF -DENABLE_P4C_GRAPHS=OFF .. && \
    make && \
    make DESTDIR=/output install
```

This commit seems to be the culprit: ab46e6892c3310263aed4ceab5c8873dd053466b. cc @fruffy since this is his change.

### PR DESCRIPTION
**Pull request by fruffy**
Hopefully fixes #3984.

### CODE REVIEW

**Comment by fruffy** [comment]
There seems to be some non-determinism in the json loader for Ubuntu 18. Not quite sure what could cause that. Maybe it is using unordered maps?

**Comment by antoninbas** [comment]
> There seems to be some non-determinism in the p4c-bm2 json serialization (or json loading?) for Ubuntu 18. Not quite sure what could cause that. Maybe it is using unordered maps?
> 
> Edit: Protobuf maps do not necessarily preserve ordering. Could that be the reason? https://protobuf.dev/programming-guides/proto3/#maps

I don't think the tests in load_ir_from_json.cpp have anything to do with Protobuf. That's IR serialization.

**Comment by fruffy** [comment]
> I don't think the tests in load_ir_from_json.cpp have anything to do with Protobuf. That's IR serialization.

Ah, for some reason I assumed the JSON generated by `p4c-bm2-ss` is generated using protobuf. But the back end has its own serializer. Makes it even more confusing.

**Comment by fruffy** [comment]
Turns out the `ConvertEnums::EnumMapping` was not an `ordered_map` and did not preserve insertion order.

**Review by antoninbas — APPROVED** [review]
Thanks for fixing the build issue

**Comment by fruffy** [comment]
@mbudiu-vmw @jnfoster @pkotikal Could you rubberstamp this? The PR fixes a build problem, but is blocked because of the codeowners restriction.

**Review by jnfoster — APPROVED** [review]
Rubberstamp'd.

**Comment by fruffy** [comment]
Thanks!

**Pull request merged**
