### PR TITLE
update psa.p4 include in output tests

### PR DESCRIPTION
**Pull request by DusanKrdzic**
fix : https://github.com/p4lang/p4c/issues/2851
Updated `psa.p4` include in outputs.

### CODE REVIEW

**Review by jafingerhut — APPROVED** [review]
Looks good to me.

**Comment by DusanKrdzic** [comment]
Test `dpdk/testdata/p4_16_samples/psa-meter1.p4` also fails on main branch. This failure has nothing to do with changes in this pr.

**Comment by mbudiu-vmw** [comment]
Can you figure out what changed to cause this failure?

**Comment by mbudiu-vmw** [comment]
If there is a clear explanation you can just add this file to the list of xfail tests in the respective backend.

**Comment by hanw** [comment]
This is caused by the removal of p4include/psa.p4 and addition of p4include/bmv2/psa.p4 and p4include/dpdk/psa.p4.

The consequence is p4test does not have a corresponding backend psa.p4 anymore. As a result, bmv2/psa.p4 was used as a default psa.p4 for p4test.

**Comment by DusanKrdzic** [comment]
I'm not sure but I think it is already in xfail list.
https://github.com/p4lang/p4c/blob/e3375706258042d86beb3f287ab01880e3d9f4a4/backends/dpdk/DpdkXfail.cmake#L12-L15

**Comment by mbudiu-vmw** [comment]
Indeed, but the xfail indicates that an error message containing "Ambiguous method execute" is expected, but the actual error is different.

**Comment by DusanKrdzic** [comment]
> Indeed, but the xfail indicates that an error message containing "Ambiguous method execute" is expected, but the actual error is different. 

Do I need to add this test file with new error message in dpdk xfails or?

Is there anything else you want me to do in order to fix and merge this pr?

**Comment by mbudiu-vmw** [comment]
I believe that changing the error message in the xfail test should be sufficient.
You should be able to just run that specific test on your machine to verify that it works.

**Comment by DusanKrdzic** [comment]
I've changed the error massage. It works on my machine now.

**Pull request merged**
