### PR TITLE
Require scapy=2.4.0 in Dockerfile

### PR DESCRIPTION
**Pull request by ChrisDodd**

### CODE REVIEW

**Comment by cc10512** [comment]
@hanw had the fix in https://github.com/p4lang/p4c/pull/1655

**Comment by hanw** [comment]
I used double equal, but it does not fix the issue.

**Comment by jafingerhut** [comment]
I am not sure, but I thought the problem where scapy was not installed correctly was for macOS, not Ubuntu

**Comment by hanw** [comment]
Is ebpf supported on osx? I may be wrong, but I thought it is a linux networking stack feature?

**Comment by mbudiu-vmw** [comment]
The way we test the ebpf back-end is to just run C programs in user-space. So that part of the testing does work.
On linux we also attempt to load the programs in the kernel - if all the supporting software is available.

**Comment by hanw** [comment]
I tried to run one of the test on osx. Here is the log:
```
hanwang-lt1:build hanwang$ ebpf/testdata/p4_16_samples/valid_ebpf.p4.test -v
Checking for  /Users/hanwang/p4c/testdata/p4_16_samples/valid_ebpf.stf
Writing temporary files into  /Users/hanwang/p4c/build/tmppGBZ7N
Loading target  targets.test_target
Writing make -f runtime.mk -C /Users/hanwang/p4c/backends/ebpf/runtime TARGET=test /Users/hanwang/p4c/build/tmppGBZ7N/test.c BPFOBJ=/Users/hanwang/p4c/build/tmppGBZ7N/test.c P4FILE=/Users/hanwang/p4c/testdata/p4_16_samples/valid_ebpf.p4 P4C=/Users/hanwang/p4c/build/p4c-ebpf
Executing make -f runtime.mk -C /Users/hanwang/p4c/backends/ebpf/runtime TARGET=test /Users/hanwang/p4c/build/tmppGBZ7N/test.c BPFOBJ=/Users/hanwang/p4c/build/tmppGBZ7N/test.c P4FILE=/Users/hanwang/p4c/testdata/p4_16_samples/valid_ebpf.p4 P4C=/Users/hanwang/p4c/build/p4c-ebpf

########### PROCESS OUTPUT BEGIN:
/Users/hanwang/p4c/build/p4c-ebpf --Werror -I./p4include --target test -o /Users/hanwang/p4c/build/tmppGBZ7N/test.c /Users/hanwang/p4c/testdata/p4_16_samples/valid_ebpf.p4
########### PROCESS OUTPUT END

Generating LALR tables
WARNING: 8 shift/reduce conflicts
Writing make -f runtime.mk -C /Users/hanwang/p4c/backends/ebpf/runtime TARGET=test BPFOBJ=/Users/hanwang/p4c/build/tmppGBZ7N/test CFLAGS+=-DCONTROL_PLANE
Executing make -f runtime.mk -C /Users/hanwang/p4c/backends/ebpf/runtime TARGET=test BPFOBJ=/Users/hanwang/p4c/build/tmppGBZ7N/test CFLAGS+=-DCONTROL_PLANE

########### PROCESS OUTPUT BEGIN:
Creating folder: /Users/hanwang/p4c/build/tmppGBZ7N/build/./ /Users/hanwang/p4c/build/tmppGBZ7N/build/./ /Users/hanwang/p4c/build/tmppGBZ7N/build/./ /Users/hanwang/p4c/build/tmppGBZ7N/build/./ /Users/hanwang/p4c/build/tmppGBZ7N/build//Users/hanwang/p4c/build/tmppGBZ7N/ /Users/hanwang/p4c/build/tmppGBZ7N/build/./
Compiling: ebpf_runtime.c -> /Users/hanwang/p4c/build/tmppGBZ7N/build/./ebpf_runtime.o
gcc -I/usr/local/opt/openssl/include/ -I/usr/local/include -DCONTROL_PLANE -O2 -g  -I/Users/hanwang/p4c/build/tmppGBZ7N/ -I./. -include ebpf_runtime_test.h -lpcap -MP -MMD -c ebpf_runtime.c -o /Users/hanwang/p4c/build/tmppGBZ7N/build/./ebpf_runtime.o
########### PROCESS OUTPUT END

*** Error 2: Failed to build the filter:
clang: warning: -lpcap: 'linker' input unused [-Wunused-command-line-argument]
In file included from <built-in>:1:
In file included from ././ebpf_runtime_test.h:27:
In file included from ././ebpf_test.h:29:
././ebpf_common.h:23:10: fatal error: 'linux/bpf.h' file not found
#include <linux/bpf.h>  // types, and general bpf definitions
         ^~~~~~~~~~~~~
1 error generated.
make: *** [/Users/hanwang/p4c/build/tmppGBZ7N/build/./ebpf_runtime.o] Error 1
```

**Comment by ChrisDodd** [comment]
That's not one of the tests that is trying to run on OSX travis and failing -- it only runs the ebpf-bcc tests, which are supposed to just run the compiler.

**Pull request closed without merging**
