### PR TITLE
[PSA] Supporting Indexed Meter as a Extern

### PR DESCRIPTION
**Pull request by yunheL**
Supporting meter extern on PSA:

meter.execute(): Syntax exposed to programmer is `ret = meter.execute(index)`. Internally, the compiler backend generate .json for `meter.execute(dst, ret)`, where `ret` is a parameter of `execute()` in the .json file.

`meter` is generated in `extern_instances` section of the .json file instead of the `meter_arrays` section.

Testing filename: `testdata/p4_16_samples/psa-meter7-bmv2.p4 (.stf)`
* A PR has been submitted to bmv2 end to support `psa-meter` as well.

### CODE REVIEW

**Comment by jfingerh** [comment]
Note from @hanw during 2020-Jun-26 PSA meeting: Han worked with Yunhe on these changes, and they look good.  The plan is to wait until there are corresponding changes in BMv2 psa_switch so that these changes can be fully tested with packet forwarding.

**Comment by mbudiu-vmw** [comment]
This looks good, but I will approve it after the corresponding changes are merged in bmv2. Please ping us at that time.

**Comment by yunheL** [comment]
psa-meter merged in to bmv2! :tada:

**Comment by yunheL** [comment]
> psa-meter merged in to bmv2! 🎉

Now that the psa-meter PR has been merged into bmv2, this PR should be able to pass Travis build. Is there a way I can trigger Travis build to run on this PR again? Thanks!

**Comment by jfingerh** [comment]
It probably already did before the PR was ever merged, with links to the test results that should be visible in the PR itself, not as one of the comments, but as additional comment-like Travis messages with links that you should be able to view from the PR.

You can always create a trivial PR that does nothing except add a line of comments to some file to one of the repos, to trigger running the Travis build with that trivial change, and look at the results that way.

Andy

**Comment by yunheL** [comment]
> It probably already did before the PR was ever merged, with links to the test results that should be visible in the PR itself, not as one of the comments, but as additional comment-like Travis messages with links that you should be able to view from the PR. You can always create a trivial PR that does nothing except add a line of comments to some file to one of the repos, to trigger running the Travis build with that trivial change, and look at the results that way. Andy

Got it, thanks Andy!

**Comment by jafingerhut** [comment]
@yunheL Sorry I missed that you were asking about p4c changes, not behavioral-model repo changes.

For p4c changes, it takes some non-deterministic number of hours after the commit to the behavioral-model repository before any p4c Travis runs will include those changes.  It may be best to wait a day before 'poking' the p4c Travis run again.

**Comment by yunheL** [comment]
> @yunheL Sorry I missed that you were asking about p4c changes, not behavioral-model repo changes.
> 
> For p4c changes, it takes some non-deterministic number of hours after the commit to the behavioral-model repository before any p4c Travis runs will include those changes. It may be best to wait a day before 'poking' the p4c Travis run again.

Thanks Andy! I "poked" the p4c Travis run before seeing this message and the Travis run already passed! Probably because the corresponding PR on bmv2 end has been merged for several hours already :D

**Comment by mbudiu-vmw** [comment]
@haw: if you have time, perhaps you can review some of my open PRs, they have been waiting for a while. most are short.

**Pull request merged**
