### PR TITLE
Fix broken Debian CI test badge in the README. Add Fedora and MacOS CI badge. 

### PR DESCRIPTION
**Pull request by Abhinavcode13**
The Main build image has been removed for improved readability

### CODE REVIEW

**Comment by fruffy** [comment]
I would suggest using the same approach as https://github.com/p4lang/p4c/pull/4510, which does not remove the main build image but fixes it.

**Comment by fruffy** [comment]
Looks good, please change the title of this pull request to more accurately reflect the content changes. It also helps to update your description.

**Comment by Abhinavcode13** [comment]
Sure @fruffy , LGTM now.

**Comment by fruffy** [comment]
I have updated the title to better reflect what the PR is actually doing. It is important to be precise to reduce cognitive load.

**Review by fruffy — APPROVED** [review]

**Pull request merged**
