### PR TITLE
Allow lookahead of structs with size of 0

### LINKED ISSUE #4143: Compiler crash on lookahead call with bit<0> in structure
### Issue
```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: ./p4c/midend/expandLookahead.cpp:46
Compiler Bug: bit<0>: unexpected size 0
```

### P4 program
```
#include <core.p4>

parser Parser(packet_in pkt);
package SimpleArch(Parser p);

struct Foo {
    bit<0> f0;
}

parser MyParser(packet_in packet) {
   state start {
       transition select(packet.lookahead<Foo>().f0) {
           0: accept;
           default: reject;
       }
   }
}

SimpleArch(MyParser()) main;
```

### PR DESCRIPTION
**Pull request by mihaibudiu**
Fixes #4143

### CODE REVIEW

**Review by jafingerhut — APPROVED** [review]
LGTM.  Such a lookahead is pretty much a no-op, yes?

**Comment by fruffy** [comment]
> LGTM. Such a lookahead is pretty much a no-op, yes?

You could probably write/add a pass to simplify this code, but not sure whether that is worth it.

**Comment by mihaibudiu** [comment]
I think that in the end that's what you'll get

**Comment by jnfoster** [comment]
Can't wait until we announce this new feature at the 2024 P4 Workshop...
<Don Steve Jobs-esque turtleneck>
Announcing... 0-bit lookahead. Your packet parsers have never been so Zen.

**Pull request merged**
