### PR TITLE
Disable libcall optimizations for wrappers of memory allocation functions

### PR DESCRIPTION
**Pull request by davidbolvansky**
Fixes https://github.com/p4lang/p4c/issues/3584

I was able to compile p4c with Clang 12.

### CODE REVIEW

**Comment by davidbolvansky** [comment]
For future readers:
If this somehow breaks again in the future (I believe that this should work fine with LTO or unity builds as well), you can try a bigger hammer:
`set (P4C_CXX_FLAGS "-fno-builtin")`

**Comment by davidbolvansky** [comment]
cc @mbudiu-vmw @ChrisDodd 

I believe this fix is better than https://github.com/p4lang/p4c/pull/3585 as that can be again defeated by more inlining done by cpp compiler.

**Comment by davidbolvansky** [comment]
Later (if project maintainers consider this useful) I can extend current github actions to build and test p4c with clang as well.

**Comment by mbudiu-vmw** [comment]
I can't test this but I will approve it.

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by davidbolvansky** [comment]
Ok thanks, you can merge it

**Pull request merged**
