### PR TITLE
Avoid to-after-is double calls to RTTI in the type checker

### PR DESCRIPTION
**Pull request by vlstill**
These calls are redundant and cost extra. While this probably has little impact of the compiler speed with the new RTTI, this way of using `to` also makes it easier to see the cast is properly checker.

### CODE REVIEW

**Review by fruffy — APPROVED** [review]
A lot of these can probably be `const auto*`?

**Comment by vlstill** [comment]
> A lot of these can probably be `const auto*`?

probably... one day I will try to configure `clang-tidy` or something to add these automatically. Most of the type checker does not even use the `auto *` convention for pointers/IR nodes.

**Comment by fruffy** [comment]
> > A lot of these can probably be `const auto*`?
> 
> probably... one day I will try to configure `clang-tidy` or something to add these automatically. Most of the type checker does not even use the `auto *` convention for pointers/IR nodes.

Well... there is a PR open which adds clang-tidy support to our CMake. 😉  
We can run it selectively. Maybe it is even possible to parametrize it.

**Review by asl — APPROVED** [review]
Lots of similar code everywhere, yes!

**Pull request merged**
