### PR TITLE
Restructure malloc / realloc implementations to inhibit libcall optimizations done by compilers even more

### PR DESCRIPTION
**Pull request by asl**

### CODE REVIEW

**Comment by asl** [comment]
Tagging @davidbolvansky

**Comment by asl** [comment]
This may fix https://github.com/p4lang/p4c/issues/3584

**Comment by davidbolvansky** [comment]
Possibly easier approach

`void* malloc(size_t x) __attribute__((no_builtin("malloc"))) {
    return realloc(nullptr, x);
}`

https://godbolt.org/z/cseMGqb6G

**Comment by davidbolvansky** [comment]
Alternative appoach (works even with clang < 10 which has no no_builtin attribute) https://godbolt.org/z/T86vs8dEW

**Comment by asl** [comment]
> void* malloc(size_t x) __attribute__((no_builtin("malloc"))) { return realloc(nullptr, x); }

Unfortunately, it's clang-only attribute (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96628). So, we'd need to provide some gcc shim. And nothing would prevent from, say, future versions of gcc to optimize in the similar way.

**Comment by davidbolvansky** [comment]
Okay, I that case, please add -fno-builtin to compilation flags of this file or for all p4c.

https://godbolt.org/z/Gxfar6cvq

Disables libcall optimizations.

**Comment by davidbolvansky** [comment]
could you try to add 
set_target_properties(p4ctoolkit PROPERTIES COMPILE_FLAGS -fno-builtin)

as last line of https://github.com/p4lang/p4c/blob/main/lib/CMakeLists.txt ?

**Comment by davidbolvansky** [comment]
Alternative approach: https://github.com/p4lang/p4c/pull/3586

**Comment by asl** [comment]
@davidbolvansky Does it fix the issue with clang on linux for you?

**Comment by davidbolvansky** [comment]
> @davidbolvansky Does it fix the issue with clang on linux for you?

https://github.com/p4lang/p4c/pull/3586 fixes https://github.com/p4lang/p4c/issues/3584. I think it is a simple fix and more future-proof. Does my path fix issue for you? (Compiler hangs)

**Comment by asl** [comment]
It should work IMO. I can imagine it could be broken with LTO and / or unity builds though...

**Comment by davidbolvansky** [comment]
> It should work IMO. I can imagine it could be broken with LTO and / or unity builds though...

I think it should work fine but I will leave a note for future readers in that PR.

**Pull request closed without merging**
