### PR TITLE
Fix exit bugs

### PR DESCRIPTION
**Pull request by hesingh**
This PR fixes the following issues

https://github.com/p4lang/p4c/issues/2358
https://github.com/p4lang/p4c/issues/2374
https://github.com/p4lang/p4c/issues/2382

Also, fixes both test P4 programs included in the following issue.
https://github.com/p4lang/p4c/issues/2435

Existing tests in p4c/testdata/p4_16_samples/exit?.p4 are left untouched in case the bmv2 backend uses exit testing of these tests.  The tests are special because they include exit statements in if-else code blocks and actions have no parameters to check for inout/out.  If asked of, I can look into removing exits from test tests as well. 

Other test outputs have changed in two ways:

1. exit statements have been removed in output if the action parameter have inout/out property.
2. Some outputs repeat the same warning. This is because the `RemoveAllUnusedDeclarations` pass is called an extra time by the new pass of this PR.

### CODE REVIEW

**Comment by hesingh** [comment]
@jafingerhut Please review the outputs of these P4 exit programs which fruffy filed - thanks.

```bash
global_action_after_exit.p4
inline_actions_exit.p4
key_after_exit.p4
nested_exit_out_param-bmv2.stf
nested_exit_out_param-bmv2.p4
side_effect_ordering_exit.p4
```

**Comment by mbudiu-vmw** [comment]
I don't see any test with a conditional exit statement: `if (cond) exit;`
The way the code is structured I don't think it handles this case.

**Comment by hesingh** [comment]
> I don't see any test with a conditional exit statement: `if (cond) exit;`
> The way the code is structured I don't think it handles this case.

If you see my notes in the PR, I said if-else statements with exit exist in p4c/testdata/p4_16_sample/exit?.p4.  One example is exit2.p4.  exit2.p4 does not have any action with a parameter so there is no way to check for inout or out.  I'd be happy to change p4c code of this PR to perform an additional check which will catch that action with exit resides in control with an out parameter and thus exit statements should be removed.  Sound reasonable?

**Comment by mbudiu-vmw** [comment]
I don't think that your approach will work. You are not really handling the case of actions with copy-out arguments where the action does not exit on all paths. Also, you are not handling the case of a table where some actions may call exit.

**Comment by hesingh** [comment]
> I don't think that your approach will work. You are not really handling the case of actions with copy-out arguments where the action does not exit on all paths. Also, you are not handling the case of a table where some actions may call exit.

Let me look into handling the case of actions with copy-out args where the action does not exit on all paths. 

Regarding handling the case of a table where some actions may call exit, I am handling the first exit encountered because then the control has to exit.

**Comment by mbudiu-vmw** [comment]
I don't understand your argument about tables. Consider two actions a and b where a will exit but b will not. If both can appear in table t how are you handling t.apply()?

**Comment by fruffy** [comment]
Did a really quick check on this. It passes the files I have submitted and also the exit_combination files in https://github.com/p4gauntlet/p4_tv/tree/master/false_friends. 
However, here is an example that leads to a wrong result:
[exit_combination_18.p4.txt](https://github.com/p4lang/p4c/files/4794188/exit_combination_18.p4.txt)
The exit is erroneously removed because there is a subsequent return.

**Comment by hesingh** [comment]
> I don't understand your argument about tables. Consider two actions a and b where a will exit but b will not. If both can appear in table t how are you handling t.apply()?

Did you see p4c/testdata/p4_16_samples/nested_exit_out_param-bmv2.p4?  One action exits while another does not.  However, since these are nested actions, there is only one t.apply() for which test passes.

I will add the test case you speak of and handle its t.apply() with new p4c changes.

**Comment by hesingh** [comment]
> Did a really quick check on this. It passes the files I have submitted and also the exit_combination files in https://github.com/p4gauntlet/p4_tv/tree/master/false_friends.
> However, here is an example that leads to a wrong result:
> [exit_combination_18.p4.txt](https://github.com/p4lang/p4c/files/4794188/exit_combination_18.p4.txt)
> The exit is erroneously removed because there is a subsequent return.

Thanks for checking.  Let me look into your new exit_combination_18.p4 test.  As one can see, I have built a framework in a new frontend pass to catch any exit in action or control.  So, the new tests asked of by Mihai and fruffy should be possible to support with more changes which won't be major.

**Comment by hesingh** [comment]
This is the program in `p4c/testdata/p4_16_samples/exit2.p4`.

```p4
control ctrl(out bit<32> c) {
    bit<32> x;

    action e() {
        exit;
        x = 1;
    }

    apply {
        bit<32> a;
        bit<32> b;

        a = 0;
        b = 1;
        c = 2;
        if (a == 0) {
            b = 2;
            e();
            c = 3;
        } else {
            b = 3;
            e();
            c = 4;
        }
        c = 5;
    }
}

control noop(out bit<32> c);
package p(noop _n);
p(ctrl()) main;
```

Does the following transformation as `exit2-frontend.p4` look ok to @jafingerhut and @mbudiu-vmw 

```p4
control ctrl(out bit<32> c) {
    bit<32> a_0;
    @name("ctrl.e") action e() {
    }
    @name("ctrl.e") action e_2() {
    }
    apply {
        a_0 = 32w0;
        if (a_0 == 32w0) {
            e();
        } else {
            e_2();
        }
        c = 32w5;
    }
}

control noop(out bit<32> c);
package p(noop _n);
p(ctrl()) main;
```

**Comment by mbudiu-vmw** [comment]
Change this example to only call e on one branch of the if.

**Comment by hesingh** [comment]
@mbudiu-vmw Now that I got time to think, I totally agree with you that this pass will only handle simple cases of exit statement removal such as in fruffy's issues.  In the next commit fruffy's `exit_combination_18.p4` is fixed.

More complex cases which you gave examples of (one table with two actions, or if has exit but else does not) are dealt with complicated logic which you have with `hasReturned/hasReturns` in the `RemoveReturns` pass. 

Right now this PR's new pass runs earlier than the `RemoveReturns` or `SideEffectsOrdering` passes.  I think, we could do simple processing in the `rmExits` pass of this PR and handle the complicated cases in subsequent passes.  Right now the `rmExits` pass only processes `MethodCallStatement` (to catch nested actions with exit) and the `ExitStatement`.

**Comment by mbudiu-vmw** [comment]
The general solution should handle all these special cases. I don't think there is any point to implement a solution that only works for some programs if we can give a general solution.

**Comment by hesingh** [comment]
Ok, got it.  Let me mull over a general solution and get back.

**Comment by ChrisDodd** [comment]
random question -- how do you mark a pull request as a 'draft' (as this one is), so it can't be merged?

**Comment by mbudiu-vmw** [comment]
I think that when you submit you get a choice of whether it's a draft or not.

**Comment by hesingh** [comment]
> random question -- how do you mark a pull request as a 'draft' (as this one is), so it can't be merged?

Moved to draft because after Mihai's review I have to work on generalizing the pass.

**Comment by hesingh** [comment]
First the if-else case has to be clarified.  
This is the P4 program with exit in if-block but not in the else-block.

```p4
control ctrl(out bit<32> c) {
    bit<32> x;
    bit<32> a;
    bit<32> b;

    action e() {
        if (a == 0) {
            b = 2;
            exit;
            c = 3;
        } else {
            b = 3;
            c = 4;
        }
        x = 1;
    }

    apply {
        a = 0;
        b = 1;
        c = 2;
        e();
        c = 5;
    }
}
```

For a first analysis of the program, it should be this:
Move else blocks to a new action.
If any statements remain in the original action using if-else, the statements move to a new action. Then the actions are called in a specific sequence.  For any statements in action before the if block, move the statements to yet another new action.  In a subsequent analysis get rid of the if-block in action e. 

The generalization is new work for p4c because I don't think a test like this exits in the p4c repo. I admit haven't looked hard. 

```p4
control ctrl(out bit<32> c) {
    bit<32> x;
    bit<32> a;
    bit<32> b;

    action e() {
        if (a == 0) {
            b = 2;
            exit;
            c = 3;
        }
    }

    action ee() {
        b = 3;
        c = 4;
    }

    action ex() {
        x = 1;
    }

    apply {
        a = 0;
        b = 1;
        c = 2;
        e();
        ee();
        ex();
        c = 5;
    }
}
```

**Comment by ChrisDodd** [comment]
It is already the case that some targets/architectures may not support conditionals (if/else) in action at all.  For such a target it is necessary to convert all conditionals in actions into separate actions (and perhaps separate tables); this will likely be done as a midend pass.  So if such is transform is done before exit removal, then exit removal need not worry about conditionals.

**Comment by mbudiu-vmw** [comment]
The exit removal should be done when the expansion of copy-out is done, otherwise the semantics of the program after copy-out expansion is actually incorrect. This happens in the front-end, in the side-effect ordering. So I am afraid that side-effect ordering should also do exit removal right away.

**Comment by hesingh** [comment]
Thanks @ChrisDodd and @mbudiu-vmw.

@mbudiu-vmw The test case you wanted me to support with only one of if- or else- blocks, should we only support the test in a control apply block or also inside an action?  As Chris said, some targets do not support if-else inside an action, so we could skip the action?

**Comment by mbudiu-vmw** [comment]
As I said, the removeExits pass is almost correct, we just have to fix it to treat correctly copy-out.
It handles all these cases already.

**Comment by fruffy** [comment]
It looks like this may not be needed any more. Should we close this? #2374 and #2382 are still not fixed, but they might be resolved with a different pull request.

**Pull request closed without merging**
