### PR TITLE
Rename eBPF section names for tc backend

### PR DESCRIPTION
**Pull request by vbnogueira**
Rename parser C file's eBPF section to "p4tc/parse" and control blocks C file's eBPF section to "p4tc/main".

### CODE REVIEW

**Review by usha1830 — APPROVED** [review]
LGTM!

**Comment by usha1830** [comment]
@vbnogueira some reference outputs need to be updated. Please check.

**Comment by vbnogueira** [comment]
Seems like the tests are failing because of a problem with apt-get in ubuntu:

```
44.89 + add-apt-repository -uy ppa:ubuntu-toolchain-r/test
75.83 Error: retrieving gpg key timed out.
```

Seems like an internal issue.
Is there a way to try and make it run again after this is solved?

**Comment by usha1830** [comment]
> Seems like the tests are failing because of a problem with apt-get in ubuntu:
> 
> ```
> 44.89 + add-apt-repository -uy ppa:ubuntu-toolchain-r/test
> 75.83 Error: retrieving gpg key timed out.
> ```
> 
> Seems like an internal issue. Is there a way to try and make it run again after this is solved?

The tests are passing, but branch needs rebase with main before we could merge this.

**Pull request merged**
