### PR TITLE
Update CI script to improve caching.

### PR DESCRIPTION
**Pull request by smolkaj**
This should speed up CI quite a bit, starting with the first run after this PR.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
I will approve this, but I really have no idea whether it works.

**Comment by smolkaj** [comment]
Should be good. We are using the same pattern here: https://github.com/google/p4-pdpi/blob/master/.github/workflows/ci-build.yml

**Review by antoninbas — APPROVED** [review]
LGTM

**Comment by smolkaj** [comment]
The Bazel builds are down to ~ 2.5 minutes, so this seems to have worked.

**Comment by mbudiu-vmw** [comment]
It looks like we have some not-so-deterministic code that generates some hidden table names, which caused these tests to fail.
You should probably check-in the modified reference files, or we can merge another PR which fixes this and you can rebase.

**Comment by smolkaj** [comment]
@mbudiu-vmw The travis failure is unrelated to my PR, right? Seems to have failed for several of the last commits to master as well. Happy to rebase once it is fixed.

**Comment by smolkaj** [comment]
Ready to be merged.

**Pull request merged**
