### PR TITLE
Update expected contents of p4info files.

### PR DESCRIPTION
**Pull request by kfcripps**
This is what I get when I run `P4TEST_REPLACE=1 make check` on `main` ToT.

### CODE REVIEW

**Comment by fruffy** [comment]
Can you rebase and check whether this still applies?

**Comment by kfcripps** [comment]
@fruffy Sure, is https://github.com/p4lang/p4c/pull/4348 expected to fix this?

**Comment by fruffy** [comment]
> @fruffy Sure, is #4348 expected to fix this?

No, was thinking there was a mismatch with #4350. But that does not seem to be the case. In either case, in order to merge this PR it needs to up-to-date with main.

**Comment by kfcripps** [comment]
Ok, I will rebase after checking that the CI passes.

**Comment by fruffy** [comment]
#4352, which is approved should also fix this. But we can merge yours first to unblock you.

**Comment by kfcripps** [comment]
@fruffy If you think that #4352 will be merged today, then I can wait and I'll close this.

**Comment by kfcripps** [comment]
Do any of the jobs spuriously fail? I noticed that the CI was red earlier, and now it is yellow, so I'm assuming that either someone re-triggered the failing job or it was re-triggered automatically, and I'm wondering if it is the same job that is currently failing in #4357.

**Comment by kfcripps** [comment]
Ah, looks like it failed again here

**Comment by fruffy** [comment]
I merged https://github.com/p4lang/p4c/pull/4352, which should obsolete this PR.

**Comment by kfcripps** [comment]
Thank you @fruffy

**Pull request closed without merging**
