### PR TITLE
Do not require explicit types for type variables of optional parameters

### LINKED ISSUE #2810: Regarding compiler error for optional parameter
Getting error for an extern function that has type parameter with @optional.

Error message:
```
    -bash-4.2$ ./p4test test.p4
    test.p4(29): [--Werror=type-error] error: HwSplFunc: could not infer a type for variable R
            HwSplFunc(hdr.mac);
            ^^^^^^^^^^^^^^^^^^
    test.p4(9)
    extern void HwSplFunc<T, **R**>(in T hdr1, @optional in **R** hdr2);
                         ^
```

Is this a bug in compiler?
P4 Spec supports both ‘type parameter’ and @optional for a parameter: 

An example from P4 spec:
         package pack<HP, MP, HC, MC>(**@optional** parserProto<**HP, MP**> _parser,  // optional parameter
                                 controlProto<HC, MC> _control = nothing()); // default parameter value

Example is attached
[test.zip](https://github.com/p4lang/p4c/files/6682803/test.zip)

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #2810

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
The code is an almost identical clone of the code handling constructors in the same file.

**Comment by rst0git** [comment]
@mbudiu-vmw when I try to compile the P4 test program with the patch from this pull request, I see the following error:
```console
./p4c --std p4-16 ../testdata/p4_16_samples_outputs/issue2810.p4

Compiler Bug: ../testdata/p4_16_samples_outputs/issue2810.p4(5): Changing binding for R/74 from _ to _
extern void HwSplFunc<T, R>(in T hdr1, @optional in R hdr2);
```
Is this expected?

**Comment by mbudiu-vmw** [comment]
That is weird - why did all the tests pass then? This command is definitely run as part of the testsuite.

**Comment by mbudiu-vmw** [comment]
Well, a similar command, using p4test.

**Review by rst0git — APPROVED** [review]
I can confirm that the tests are passing and `p4test` works as expected:
```
$ ctest -R issue2810

    Start 1291: p4/testdata/p4_16_samples/issue2810.p4
1/1 Test #1291: p4/testdata/p4_16_samples/issue2810.p4 ...   Passed    0.42 sec

100% tests passed, 0 tests failed out of 1
```
Perhaps, the difference is that `p4c` is trying to compile `issue2810.p4` with the BMv2 simple_switch backend. I assume that the error mentioned above is expected or it could be fixed in another pull request.

**Comment by mbudiu-vmw** [comment]
A compiler bug is a bug - I will investigate.

**Comment by rst0git** [comment]
@mbudiu-vmw Thank you for fixing the problem with duplicate values.

**Pull request merged**
