### PR TITLE
Add the DASH BMv2 model to the tested programs.

### PR DESCRIPTION
**Pull request by fruffy**
Another large BMv2 program to test on.

### CODE REVIEW

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by fruffy** [comment]
I believe there is a bug in the way `Inline` handles table names. It converts the table name into `outbound_acl_stage1:dash_acl_rule|dash_acl` instead of `outbound_acl_stage1`.

**Comment by fruffy** [comment]
@jafingerhut You mentioned the dash programs were slightly unusual in the way they were written. Were you referring to the table names, for example? Are names like `stage1:dash_acl_rule|dash_acl` legal P4Runtime names?

**Comment by jafingerhut** [comment]
@fruffy I had forgotten about the unusual characters in @name annotations, which are a bit odd, true.

More likely what I was referring to is that there are new custom match_kinds and syntax of proposed non-standard P4 language constructs in some of the original source files (e.g. search for a match_kind 'list' and I think also 'list_port', and a keyword 'struct_graph' in some of the files), that give errors if you attempt to compile them with the latest published p4c.  Those are only enabled with certain preprocessor symbol #define settings that you probably did not use.

**Comment by jafingerhut** [comment]
@fruffy By the way, are the unusual characters in @name annotations causing problems within p4c itself?  e.g. causing intermediate P4_16 files to be generated that cannot be parsed as P4_16 source code by p4c?  Or some other issues?

It seems worth mentioning this fact to the authors of the DASH P4 program, in case they are unaware of it.

**Comment by fruffy** [comment]
Rerequesting to make sure that the changes to `inline.cpp` are acceptable.

**Comment by jafingerhut** [comment]
I have created this issue on the DASH repo pointing out the possible issue with `@name` annotations having characters that are not legal in P4 identifiers.

@fruffy I am guessing that if the string contents of a `@name` annotation were a legal P4 identifier name, there should be no problems encountered?

**Comment by apinski-cavium** [comment]
I remember asking about `@name` specifically on keys as the p4c will definitely create `@name` annotations like `a & 15`.

**Comment by mbudiu-vmw** [comment]
https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-cp-names describes how control-plane names are calculated.
I think this change is not conformant to the spec.

**Comment by apinski-cavium** [comment]
> https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-cp-names describes how control-plane names are calculated. I think this change is not conformant to the spec.

https://github.com/p4lang/p4-spec/pull/1141 ...

**Comment by fruffy** [comment]
> https://p4.org/p4-spec/docs/P4-16-v-1.2.3.html#sec-cp-names describes how control-plane names are calculated. I think this change is not conformant to the spec.

In what way is this not conformant?  I believe the control plane will still just refer to the `@name`, which is unchanged.

**Comment by mbudiu-vmw** [comment]
Is there a test case exercising the new inline code?
Then we can tell whether the result is wrong.

**Comment by fruffy** [comment]
> Is there a test case exercising the new inline code? Then we can tell whether the result is wrong.

Done, the compiler seems to be handling the characters well. And so does the PTF framework, surprisingly. The STF framework does not.

**Comment by fruffy** [comment]
Any remaining concerns with this PR?

**Comment by mbudiu-vmw** [comment]
I have approved

**Pull request merged**
