### PR TITLE
Use the type from the typeMap; fixes #2163

### LINKED ISSUE #2163: Compiling a v1model program using p4c and value_set gives compiler bug error message
I have not gone to earlier versions of p4c to see how far back this behavior goes, but least with the latest version of p4c source code as of 2020-Jan-28, compiling any of these programs in the testdata/p4_16_samples directory using the command `p4c file.p4` or `p4c --target bmv2 --arch v1model file.p4`:

+ pvs-struct.p4
+ pvs-nested-struct.p4
+ v1model-p4runtime-most-types1.p4

gives a compiler bug error:
```
$ p4c pvs-struct.p4
In file: /home/andy/forks/p4c/ir/type.def:365
Compiler Bug: Type_Name is not a canonical type, use getTypeType()?
```

None of them give any errors when compiled using the `p4test file.p4` command.

I think the last two test programs above were created to test out the edge cases of supported types, and may not be intended to compile without any errors, but a compiler bug doesn't seem appropriate.

The attached program pvs-2-bmv2.p4 is a small modification of the existing test program pvs-struct.p4, except that it compiles without error using `p4c` and `p4c --target bmv2 --arch v1model`.  Something like it should perhaps be added as another test program, and might be useful in comparing the compiler's behavior against the other test programs when investigating why only the ones above give a compiler bug.

[pvs-2-bmv2.p4.txt](https://github.com/p4lang/p4c/files/4126118/pvs-2-bmv2.p4.txt)

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
The tests are in #2174

### CODE REVIEW

**Comment by hesingh** [comment]
This was my first fix with https://github.com/p4lang/p4c/pull/2173.

Why did you duplicate the PR when I asked my PR to be reviewed?

**Comment by hesingh** [comment]
I care about bugs getting fixed ASAP.  If anyone approves this PR, go ahead and check it in since you have checkin permission and I don't.

**Comment by mbudiu-vmw** [comment]
I have reviewed your current fix, I cannot review fixes you made in the past.
The current fix is wrong.
I was on vacation this week-end, I cannot review code continuously.

**Comment by hesingh** [comment]
No problem/  These were my first changes in my PR:

https://github.com/p4lang/p4c/pull/2173/commits/656ad4a8a6544bec57f9bf8b257fc63428d722b0

**Comment by hesingh** [comment]
@mbudiu-vmw When you get a chance please reply to this question I asked in my PR today:

It is correct behavior that TypeInference::postorder(IR::P4ValueSet) does not change type for decl->elementType when elementType is struct?  

I didn't get an answer to this question and this is why I was looking at frontend changes.

**Comment by hesingh** [comment]
Could someone please review this PR so that the code can be checked in today.  The changes will unblock Andy's pvs P4 tests and also my follow on work related to pvs.  thanks.

Changes look good to me, but my vote doesn't count.

**Comment by mbudiu-vmw** [comment]
TypeInference never changes any IR node in the graph. It can only insert new nodes in the graph, and only if it is called with a `readOnly=false` flag, which happens only very early in the front-end.

**Pull request merged**
