### PR TITLE
Fir for issue #212

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
I have followed the instructions for git:
```
git fetch upstream
git rebase upstream/master
git pull # without this I could not push
git push origin master
```
but I now see even more spurious commits!

### CODE REVIEW

**Comment by sethfowler** [comment]
Your life will be a lot easier if you work on each PR in a separate feature branch. If you don't do that, you're mixing everything together, and you'll end up with commits included in your PR that you didn't intend.

Those directions probably need some work.

**Comment by mbudiu-vmw** [comment]
Can you please update the directions for contributing using git?
You should specify the fact that each PR should contain exactly one fix.

**Comment by ChrisDodd** [comment]
Do not do the `git pull` from your repo, which has the unmerged changes.  Instead, `git push -f` your changes into your repo before making the pull request.  The merge commits are there in your repo because you've previously done merges from p4c/master there.

**Comment by ChrisDodd** [comment]
At this point, if you do `git rebase upstream/master` followed by `git push -f` it should clean things up.

**Comment by ChrisDodd** [comment]
I see an error

    terminate called after throwing an instance of 'Util::CompilerBug'
      what():  COMPILER BUG: ../frontends/p4/typeMap.cpp:82
    Could not find type for <Cast>(90760)

with a testcase when I merge this -- I've moved the testcase from our internal repo to the public as it doesn;t really have any internal stuff in it (need a better scrub, since there are a bunch of such tests)

**Comment by mbudiu-vmw** [comment]
The new test checked-in now passes as well.
I have also fixed issue #210.

**Pull request merged**
