### PR TITLE
Remove old ipaddr python module

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
The Python package ipaddr has been superseded by ipaddress: https://pypi.org/project/ipaddr/

Its use has been removed from p4lang/behavioral-model code recently: https://github.com/p4lang/behavioral-model/commit/7a8843ffb87bab9eb0a44c993ae39a9fefca10cf

It would be nice to remove its use from other p4lang repos where it is mentioned, too, including p4c.

**Review by mihaibudiu — APPROVED** [review]

**Comment by fruffy** [comment]
I believe the failures are because the `p4lang-bmv2` package has not been updated yet.

@rst0git how do you maintain this package? Any way we can help?

**Comment by rst0git** [comment]
@fruffy Thank you for the heads-up. I will update the packages in the next few hours.

**Review by rst0git — APPROVED** [review]
LGTM

**Pull request merged**
