### PR TITLE
Fix build with system Protobuf

### LINKED ISSUE #4316: Protobuf build errors with v1.2.4.7
Hey,

v1.2.4.7 fails to build for me because of the changes to the Protobuf cmake file: https://github.com/p4lang/p4c/commit/aaa5c7d547e968f0bd90e96d7eac6304e1e348bf
The problem is that the variables `Protobuf_LIBRARY`, `Protobuf_PROTOC_EXECUTABLE`, `PROTOC_BINARY` and `Protobuf_INCLUDE_DIR` are not defined when linking against system protobuf. I was able to resolve this by applying the following patch:
```patch
diff --git a/cmake/Protobuf.cmake b/cmake/Protobuf.cmake
index f1feeb00e..f0891c50e 100644
--- a/cmake/Protobuf.cmake
+++ b/cmake/Protobuf.cmake
@@ -15,15 +15,13 @@ macro(p4c_obtain_protobuf)
     if(NOT Protobuf_FOUND)
       find_package(Protobuf REQUIRED)
     endif()
-    # Protobuf sets the protoc binary to a generator expression, which are problematic.
-    # They are problematic because they are only evaluated at build time.
-    # However, we may have scripts that depend on the actual build time during the configure phase.
-    # Hard code a custom binary instead.
-    find_program(PROTOC_BINARY protoc)
 
     if(ENABLE_PROTOBUF_STATIC)
       set(CMAKE_FIND_LIBRARY_SUFFIXES ${SAVED_CMAKE_FIND_LIBRARY_SUFFIXES})
     endif()
+    set(Protobuf_LIBRARY "protobuf::libprotobuf")
+    set(Protobuf_PROTOC_EXECUTABLE "protobuf::protoc")
+    set(PROTOC_BINARY "protobuf::protoc")
   else()
     # Google introduced another breaking change with protobuf 22.x by adding abseil as a new
     # dependency. https://protobuf.dev/news/2022-08-03/#abseil-dep We do not want abseil, so we stay
diff --git a/control-plane/CMakeLists.txt b/control-plane/CMakeLists.txt
index 1e59f9a56..4d1b504b9 100644
--- a/control-plane/CMakeLists.txt
+++ b/control-plane/CMakeLists.txt
@@ -52,7 +52,7 @@ add_custom_target (mkP4configdir
   ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/p4/config)
 add_custom_command(OUTPUT ${P4RUNTIME_GEN_SRCS} ${P4RUNTIME_GEN_HDRS}
   COMMAND ${Protobuf_PROTOC_EXECUTABLE}
-          -I${P4RUNTIME_STD_DIR} -I${CMAKE_CURRENT_SOURCE_DIR} -I${Protobuf_INCLUDE_DIR}
+          -I${P4RUNTIME_STD_DIR} -I${CMAKE_CURRENT_SOURCE_DIR}
           --cpp_out ${CMAKE_CURRENT_BINARY_DIR}
           --python_out ${CMAKE_CURRENT_BINARY_DIR}
           --experimental_allow_proto3_optional
```

### PR DESCRIPTION
**Pull request by jkhsjdhjs**
This sets the flag `protobuf_MODULE_COMPATIBLE` in the Protobuf cmake file, so the Protobuf files expose some variables required by the build, such as `Protobuf_PROTOC_EXECUTABLE`.

Furthermore, `Protobuf_LIBRARY` is defined manually as `protobuf::libprotobuf`, because it is only holds the path to the Protobuf library, not the abseil library Protobuf depends on since version 22.

Fix #4316 

@fruffy This still fails to build with system protobuf because `Protobuf_INCLUDE_DIR` is not defined:
https://github.com/p4lang/p4c/blob/8cc98afc5116730f8b8c90e6ed4a482874c6efee/control-plane/CMakeLists.txt#L55

When building with system protobuf, only `Protobuf_INCLUDE_DIRS` (plural) is defined. We could assign `Protobuf_INCLUDE_DIRS` to `Protobuf_INCLUDE_DIR` or just use `Protobuf_INCLUDE_DIRS` in the control-plane cmake file, but what would happen if it contains multiple variables?

### CODE REVIEW

**Comment by fruffy** [comment]
`Protobuf_INCLUDE_DIR` is used in a bunch of places, switching to Protobuf_INCLUDE_DIRS might be tricky.  Are the paths in Protobuf_INCLUDE_DIRS at least correct?

**Comment by fruffy** [comment]
Could you try this patch and see whether it helps?

```diff
diff --git a/backends/dpdk/CMakeLists.txt b/backends/dpdk/CMakeLists.txt
index ffe4d26d9..fe3ffc33e 100644
--- a/backends/dpdk/CMakeLists.txt
+++ b/backends/dpdk/CMakeLists.txt
@@ -41,7 +41,7 @@ add_dependencies(dpdk_runtime_dir controlplane)
 
 add_library(dpdk_runtime STATIC ${DPDK_P4RUNTIME_INFO_GEN_SRCS})
 target_include_directories(dpdk_runtime
-  SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIR}
+  SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIRS}
 )
 
 # Silence various warnings as the root issue is out of our control, example https://github.com/protocolbuffers/protobuf/issues/7140
diff --git a/backends/p4tools/common/CMakeLists.txt b/backends/p4tools/common/CMakeLists.txt
index 275819e7f..8b91309a3 100644
--- a/backends/p4tools/common/CMakeLists.txt
+++ b/backends/p4tools/common/CMakeLists.txt
@@ -65,7 +65,7 @@ add_p4tools_library(p4tools-control-plane ${P4C_TOOLS_CONTROL_PLANE_SOURCES})
 
 target_include_directories(
   p4tools-control-plane
-  SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIR}
+  SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIRS}
 )
 
 add_dependencies(p4tools-control-plane controlplane)
diff --git a/backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt b/backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
index 005f960a6..8438e6e28 100644
--- a/backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
+++ b/backends/p4tools/modules/testgen/targets/bmv2/CMakeLists.txt
@@ -58,6 +58,6 @@ set(
 
 set(
   TESTGEN_INCLUDES ${TESTGEN_INCLUDES}
-  SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIR}
+  SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIRS}
   PARENT_SCOPE
 )
diff --git a/backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake b/backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
index f6e071e53..0e5c95c47 100644
--- a/backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
+++ b/backends/p4tools/modules/testgen/targets/bmv2/test/TestTemplate.cmake
@@ -46,7 +46,7 @@ function(validate_protobuf testfile testfolder)
   file(APPEND ${testfile} "for item in \${txtpbfiles[@]}\n")
   file(APPEND ${testfile} "do\n")
   file(APPEND ${testfile} "\techo \"Found \${item}\"\n")
-  file(APPEND ${testfile} "\t${PROTOC_BINARY} -I${Protobuf_INCLUDE_DIR} -I${CMAKE_CURRENT_LIST_DIR}/../proto -I${P4RUNTIME_STD_DIR} -I${P4C_SOURCE_DIR}/control-plane --encode=p4testgen.TestCase p4testgen.proto < \${item} > /dev/null\n")
+  file(APPEND ${testfile} "\t${PROTOC_BINARY} ${PROTOBUF_PROTOC_INCLUDES} -I${CMAKE_CURRENT_LIST_DIR}/../proto -I${P4RUNTIME_STD_DIR} -I${P4C_SOURCE_DIR}/control-plane --encode=p4testgen.TestCase p4testgen.proto < \${item} > /dev/null\n")
   file(APPEND ${testfile} "done\n")
 endfunction(validate_protobuf)
 
@@ -60,7 +60,7 @@ function(validate_protobuf_ir testfile testfolder)
   file(APPEND ${testfile} "for item in \${txtpbfiles[@]}\n")
   file(APPEND ${testfile} "do\n")
   file(APPEND ${testfile} "\techo \"Found \${item}\"\n")
-  file(APPEND ${testfile} "\t${PROTOC_BINARY} -I${Protobuf_INCLUDE_DIR} -I${CMAKE_CURRENT_LIST_DIR}/../proto -I${P4RUNTIME_STD_DIR} -I${P4C_SOURCE_DIR} -I${P4C_SOURCE_DIR}/control-plane --encode=p4testgen_ir.TestCase p4testgen_ir.proto < \${item} > /dev/null\n")
+  file(APPEND ${testfile} "\t${PROTOC_BINARY} ${PROTOBUF_PROTOC_INCLUDES} -I${CMAKE_CURRENT_LIST_DIR}/../proto -I${P4RUNTIME_STD_DIR} -I${P4C_SOURCE_DIR} -I${P4C_SOURCE_DIR}/control-plane --encode=p4testgen_ir.TestCase p4testgen_ir.proto < \${item} > /dev/null\n")
   file(APPEND ${testfile} "done\n")
 endfunction(validate_protobuf_ir)
 
diff --git a/cmake/Protobuf.cmake b/cmake/Protobuf.cmake
index f1feeb00e..5f3d8a23a 100644
--- a/cmake/Protobuf.cmake
+++ b/cmake/Protobuf.cmake
@@ -15,10 +15,9 @@ macro(p4c_obtain_protobuf)
     if(NOT Protobuf_FOUND)
       find_package(Protobuf REQUIRED)
     endif()
-    # Protobuf sets the protoc binary to a generator expression, which are problematic.
-    # They are problematic because they are only evaluated at build time.
-    # However, we may have scripts that depend on the actual build time during the configure phase.
-    # Hard code a custom binary instead.
+    # Protobuf sets the protoc binary to a generator expression, which are problematic. They are
+    # problematic because they are only evaluated at build time. However, we may have scripts that
+    # depend on the actual build time during the configure phase. Hard code a custom binary instead.
     find_program(PROTOC_BINARY protoc)
 
     if(ENABLE_PROTOBUF_STATIC)
@@ -71,12 +70,13 @@ macro(p4c_obtain_protobuf)
     set(Protobuf_LIBRARY "protobuf::libprotobuf")
     set(Protobuf_PROTOC_LIBRARY "protobuf::libprotoc")
     set(Protobuf_PROTOC_EXECUTABLE $<TARGET_FILE:protoc>)
-    # Protobuf sets the protoc binary to a generator expression, which are problematic.
-    # They are problematic because they are only evaluated at build time.
-    # However, we may have scripts that depend on the actual build time during the configure phase.
-    # Hard code a custom binary which we can use in addition to the generator expression.
+    # Protobuf sets the protoc binary to a generator expression, which are problematic. They are
+    # problematic because they are only evaluated at build time. However, we may have scripts that
+    # depend on the actual build time during the configure phase. Hard code a custom binary which we
+    # can use in addition to the generator expression.
+    # TODO: Maybe we can improve these scripts somehow?
     set(PROTOC_BINARY ${protobuf_BINARY_DIR}/protoc)
-    set(Protobuf_INCLUDE_DIR "${protobuf_SOURCE_DIR}/src/")
+    list(APPEND Protobuf_INCLUDE_DIRS "${protobuf_SOURCE_DIR}/src/")
 
     # Reset temporary variable modifications.
     set(CMAKE_UNITY_BUILD ${CMAKE_UNITY_BUILD_PREV})
@@ -84,6 +84,13 @@ macro(p4c_obtain_protobuf)
     set(CMAKE_POSITION_INDEPENDENT_CODE ${CMAKE_POSITION_INDEPENDENT_CODE_PREV})
   endif()
 
+  # Protobuf does not seem to set Protobuf_INCLUDE_DIR correctly, but we need this variable for
+  # generating code with protoc. Instead, we rely on Protobuf_INCLUDE_DIRS and generate a custom
+  # utility variable for includes.
+  set(PROTOBUF_PROTOC_INCLUDES)
+  foreach(dir ${Protobuf_INCLUDE_DIRS})
+    list(APPEND PROTOBUF_PROTOC_INCLUDES "-I${dir}")
+  endforeach()
 
   message("Done with setting up Protobuf for P4C.")
 endmacro(p4c_obtain_protobuf)
diff --git a/control-plane/CMakeLists.txt b/control-plane/CMakeLists.txt
index 1e59f9a56..24ced3ef3 100644
--- a/control-plane/CMakeLists.txt
+++ b/control-plane/CMakeLists.txt
@@ -50,9 +50,10 @@ set (P4RUNTIME_GEN_PYTHON "control-plane")
 #   control-plane/p4/config/p4info.pb.cc
 add_custom_target (mkP4configdir
   ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/p4/config)
+
 add_custom_command(OUTPUT ${P4RUNTIME_GEN_SRCS} ${P4RUNTIME_GEN_HDRS}
   COMMAND ${Protobuf_PROTOC_EXECUTABLE}
-          -I${P4RUNTIME_STD_DIR} -I${CMAKE_CURRENT_SOURCE_DIR} -I${Protobuf_INCLUDE_DIR}
+          -I${P4RUNTIME_STD_DIR} -I${CMAKE_CURRENT_SOURCE_DIR} ${PROTOBUF_PROTOC_INCLUDES}
           --cpp_out ${CMAKE_CURRENT_BINARY_DIR}
           --python_out ${CMAKE_CURRENT_BINARY_DIR}
           --experimental_allow_proto3_optional
@@ -94,7 +95,7 @@ set (CONTROLPLANE_HDRS
 
 add_library(controlplane-gen OBJECT ${P4RUNTIME_GEN_SRCS})
 target_include_directories(controlplane-gen
-  SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIR}
+  SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIRS}
 )
 target_link_libraries (controlplane-gen PUBLIC ${Protobuf_LIBRARY})
 # Needed for the correct import of google/status.pb.cc
```

**Comment by jkhsjdhjs** [comment]
@fruffy The patch does not apply on the latest main, `backends/p4tools/common/CMakeLists.txt` doesn't has a line containing
```
SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIR}
```

**Comment by fruffy** [comment]
> @fruffy The patch does not apply on the latest main, `backends/p4tools/common/CMakeLists.txt` doesn't has a line containing
> 
> ```
> SYSTEM BEFORE PUBLIC ${Protobuf_INCLUDE_DIR}
> ```

Fixed.

**Comment by jkhsjdhjs** [comment]
Yep, this works! I removed the `\ No newline at end of file` change and the change that only added a newline, as I assume these to be accidental, and added the other changes to this PR.

**Review by fruffy — APPROVED** [review]
Looks good to me. @vlstill anything to add?

**Review by vlstill — APPROVED** [review]
I don't see any problems.

**Pull request merged**
