### PR TITLE
Fix clang formatting

### PR DESCRIPTION
**Pull request by ChrisDodd**
Someone checked in a broken .clang-format that broke all the formatting on pointer/reference declarations.  This fixes that.

### CODE REVIEW

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by fruffy** [comment]
bf-p4c-compiler's `.clang-format` also has `PointerAlignment: Left`.

**Review by rst0git — APPROVED** [review]

**Comment by mbudiu-vmw** [comment]
We have to merge this quickly, or it will always generate conflicts.
@ChrisDodd can you please rebase and merge?

**Comment by ChrisDodd** [comment]
Anyone know what version of clang-format is being run on CI?  It doesn't seem to agree with the 10.0.0-4ubuntu1 I have installed locally.

**Comment by fruffy** [comment]
The version is fixed at 15.0.6
https://github.com/p4lang/p4c/blob/main/requirements.txt#L8

**Comment by davidbolvansky** [comment]
> bf-p4c-compiler's `.clang-format` also has `PointerAlignment: Left`.

What about this?

you should also update https://github.com/p4lang/p4c/blob/main/.git-blame-ignore-revs

**Pull request merged**
