### PR TITLE
Allow 1-bit int values

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
I don't think that the v1errors folder was being used. It was in the wrong place anyway.

### CODE REVIEW

**Comment by ChrisDodd** [comment]
We discussed adding bit<1> in the language design group (https://github.com/p4lang/p4-spec/issues/668), was a decision ever made?

**Comment by mbudiu-vmw** [comment]
We will on Monday. Testing that it works.

**Comment by mbudiu-vmw** [comment]
This is a small patch to allow `int<1>`.

**Comment by mbudiu-vmw** [comment]
I think that the LDWG has accepted this change, so we should probably merge this PR.
This is a one-line change, can we get a review?

**Comment by mbudiu-vmw** [comment]
I have pushed a change to the InvalidParserError test, it turns out that merging that PR and the mark_to_drop PR causes the build to fail. If this test passes it should fix the build when merged.

**Comment by hesingh** [comment]
When I resolved my PSA11 PR conflict, indeed Travis failed most tests (3-4) due to mark_to_drop.

**Pull request merged**
