### PR TITLE
Make stricter PSA tests that verify packet_path and instance fields i…

### PR DESCRIPTION
**Pull request by jafingerhut**
…n egress

### CODE REVIEW

**Comment by jafingerhut** [comment]
These tests fail without the changes proposed in this bmv2 PR, or something similarly effective: https://github.com/p4lang/behavioral-model/pull/937

The tests were written to be more comprehensive in their checking that PSA intrinsic metadata fields are assigned the correct values.

**Comment by jafingerhut** [comment]
@fruffy Would you have any time to look at an equivalence violation found for one of the test programs modified by this PR?  I am not yet knowledgable enough of the program's output to determine what kind of problem it found.

**Comment by fruffy** [comment]
I think it is related to this issue #2470. I have not implemented a fix because the resolution was unclear. Will update something tomorrow.

**Comment by jafingerhut** [comment]
@fruffy Thanks for taking a look.  I changed the test program so that the control always assigned a value to the 'out' parameter 'ret', which eliminates a warning from p4c that it might be uninitialized, in hopes that it will also avoid this error from the equivalence checker.  If you want to keep a copy of the version of the test program that caused the error report, let me know.  It is the one after the 3rd of the commits on this PR.

**Pull request merged**
