### PR TITLE
Small TC fixes

### PR DESCRIPTION
**Pull request by vbnogueira**
Whilst writing the automated test tools for the tc backend, I ended up finding some compilation bugs when compiling some generated C files from the testdata samples directory
This PR fixes those issues, describes them in more detail in the commit messages and updates `pna.h`

### CODE REVIEW

**Comment by vbnogueira** [comment]
@komaljai please take a look when you have some time

**Review by komaljai — APPROVED** [review]

**Comment by vbnogueira** [comment]
@fruffy question: Do we need to wait for the tofino fix to merge this PR, or can we merge as is?

**Comment by fruffy** [comment]
You can merge as is. The Tofino back end fixes will take a while.

**Comment by vbnogueira** [comment]
> You can merge as is. The Tofino back end fixes will take a while.

Sorry, but can you merge it?
I would merge myself, but I don't have permission to do so

**Pull request merged**
