### PR TITLE
psa: fix header json generation

### PR DESCRIPTION
**Pull request by hanw**

### CODE REVIEW

**Comment by hanw** [comment]
@jafingerhut the helloworld program is now failing with a new error.
```
Compiler Bug: psa-example-hello-world.p4(93): hdr.ipv4.dstAddr[1:0];: Unhandled case
                (PortId_t) ((PortIdUint_t) hdr.ipv4.dstAddr[1:0]));
                                           ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jafingerhut** [comment]
I am going ahead and merging this in, since the changes are specific to the PSA back end.  I suppose we can be _slightly_ relaxed about PSA-specific changes until we get something that passes at least a few more tests.

**Comment by hesingh** [comment]
Where can one get the ```psa-example-hello-world.p4``` file from?  I don't see this P4 program in the p4 repo.

**Comment by hanw** [comment]
it's in p4-spec repo.

**Comment by hesingh** [comment]
Ah, my google search also said p4-spec, but, I was scratching my head, why the spec would have it.  Seeing your reply, now I see psa has several examples - thanks!

I will look into this program's p4c failure due to new psa.p4 since I have the final fix completed to fix the four psa p4c tests.

**Comment by hanw** [comment]
I am working on a PR to fix the helloworld example. Can you work on the other 4 psa tests?

**Comment by hesingh** [comment]
ok - sounds good.

I have fixed all 4 psa tests and testing 'make check'.  I plan to checkin code today and also try to issue a PR later in the day.

**Comment by hesingh** [comment]
Incidentally, please use my changes sent out for PR today to test helloworld.  When I did, I don't see any failures.   I just see these warnings from 

```ResolveReferences::checkShadowing(const IR::INamespace* ns)```

```
./tmp9KXwG9/psa-example-hello-world-midend.p4(55): [--Wwarn=shadow] warning: .send_to_port shadows send_to_port
    @name(".send_to_port") action send_to_port() {
                                  ^^^^^^^^^^^^
/home/hemant/int/p4c/build/backends/p4test/p4include/psa.p4(391)
action send_to_port(inout psa_ingress_output_metadata_t meta,
       ^^^^^^^^^^^^
./tmp9KXwG9/psa-example-hello-world-midend.p4(60): [--Wwarn=shadow] warning: .ingress_drop shadows ingress_drop
    @name(".ingress_drop") action ingress_drop() {
                                  ^^^^^^^^^^^^
/home/hemant/int/p4c/build/backends/p4test/p4include/psa.p4(422)
action ingress_drop(inout psa_ingress_output_metadata_t meta)
       ^^^^^^^^^^^^
```

**Comment by hesingh** [comment]
Another psa failure from the spec PSA examples.  To fix this one, we'd have to add an enhancement to p4c.
```
hemant@ubuntu:~/int/p4c/build$ ./p4test --std p4-16 ../testdata/p4_16_samples/psa-example-register1.p4 --p4runtime-files tmp.p4info.txt
../testdata/p4_16_samples/psa-example-register1.p4(114): [--Werror=legacy] error: port_pkt_ip_bytes_in.read: functions or methods returning structures are not supported on this target
                tmp = port_pkt_ip_bytes_in.read(istd.ingress_port);
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hemant@ubuntu:~/int/p4c/build$ 
```

**Comment by hesingh** [comment]
@hanw I see your checkin to p4c for the psa_switch backend.

https://github.com/p4lang/p4c/pull/1729

With Andy's psa.p4 changes, the 4 tests fail with p4test.  Should we apply the same eliminate newtype to the p4test backend for the 4 tests to pass and then no changes to p4c/control-plane are needed?  The rest of my PR from today is needed to deal with newtype in the frontend code because the elimination is happening in the midend code.

**Comment by hesingh** [comment]
Oops, not thinking right.  The #1729 code eliminates newtype (PortId_t) in the midend.  P4runtime API generation happens before that.  Thus, my PR's p4c/control-plane changes are needed.

**Pull request merged**
