### PR TITLE
Add STF test exercising new ParserInvalidArgument parser error

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
Follow-up PR to finish work started with these recently merged changes:

https://github.com/p4lang/p4c/pull/1855
https://github.com/p4lang/behavioral-model/pull/757

**Comment by mbudiu-vmw** [comment]
I guess we needed #1862 before this succeeds?
Can you trigger this build again?

**Comment by jafingerhut** [comment]
I know I can trigger the build & test with another commit, and will do that if that is the easiest way.

I wanted to ask whether there was some button I can push in the Github web interface that will trigger such a build & test, without another commit?

**Comment by jafingerhut** [comment]
Never mind on my previous question.  I gave Travis some permission to access my Github account, and then found a button there to trigger a re-build without a new commit.

**Comment by mbudiu-vmw** [comment]
Some people with high enough privileges see a Travis-related button in the UI, but I am not one of them.

**Comment by cc10512** [comment]
@mbudiu-vmw the Travis CI for p4lang is public, so anyone should see the button in the browser interface and be able to see the Travis job. You may need to login into Travis with your github credentials to actually see the job.

**Pull request merged**
