### PR TITLE
Fix for issue #655

### PR DESCRIPTION
**Pull request by hanw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
The compiler crashes on 5 examples. So the patch is obviously not ready for review.
Also, please add a test case that actually runs a checksum computation. I think that the following would work as an STF file for the example filed with issue #655: 

```
packet 0 0000 0000
expect 0 0001 0001
packet 0 0001 0001
expect 0 0002 0002
```

If this example works you can also address issue #255.

**Comment by hanw** [comment]
yes, I was dragged to a meeting before I can finish adding the test case, doing it now.

**Comment by mbudiu-vmw** [comment]
This commit does not include the reference outputs from the new test case, so we cannot be sure that the test case has succeeded.

**Comment by hanw** [comment]
Still debugging, just switched to the VM with bmv2 installed. I will let you know when it's complete.

**Comment by hanw** [comment]
@mbudiu-vmw The checksum value computed by bmv2 seems odd to me, it is `0xfffe` instead of `0x0001` for an input of `0x0001`.

**Comment by hanw** [comment]
but other than that, I have added the test case for p4test and bmv2.

**Comment by mbudiu-vmw** [comment]
Probably my test is wrong: https://en.wikipedia.org/wiki/IPv4_header_checksum
It looks like you have to flip the bits.
Please update the stf file.

**Comment by hanw** [comment]
I have flipped the bits in the committed stf file.

**Comment by jafingerhut** [comment]
I would strongly recommend at least a few test cases that would detect the difference between doing a 1's complement sum vs. not doing a 1's complement sum, i.e. a case where adding two 16-bit numbers has a carry out into the 17th bit position.

**Comment by jafingerhut** [comment]
Also at least 1 case where the received packet is dropped because of a bad checksum.

**Pull request merged**
