### PR TITLE
Handle struct expression in ebfp backend

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

Fixes errors that appear in p4c-xdp tests.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
@osinstom please review this. Without this change P4 code for ebpf which uses struct expressions enters an infinite loop in the CodeGen visitor. This causes some xdp tests to fail.

**Review by fruffy — APPROVED** [review]

**Comment by rst0git** [comment]
@mbudiu-vmw Would it be possible to add tests in this repository as well?

**Review by osinstom — APPROVED** [review]
LGTM. Out of curiosity, what are the p4c-xdp tests that are failing?

**Comment by rst0git** [comment]
> LGTM. Out of curiosity, what are the p4c-xdp tests that are failing?

https://github.com/vmware/p4c-xdp/runs/5816847076

**Comment by mbudiu-vmw** [comment]
> @mbudiu-vmw Would it be possible to add tests in this repository as well?

That is a legitimate request; I had asked @osintom to test the code in the xdp repository too for his commits, but I guess he is not doing that. Haven't done it for this test, yet.

**Comment by osinstom** [comment]
> That is a legitimate request; I had asked @osintom to test the code in the xdp repository too for his commits, but I guess he is not doing that. Haven't done it for this test, yet.

@mbudiu-vmw Running tests for every change with some external plugins is counterproductive.. I suggest moving p4c-xdp to this repository, so we can keep all eBPF-related targets. Otherwise, it's a kind of a nightmare to _manually_ verify every change with p4c-xdp, and doesn't seem to me as a reliable way. I know that p4c-xdp has been created to show how to create p4c extensions, but it's obvious that things can break if something is sitting outside of the repo and we don't have integrations tests (how would we?). How do you verify if modifications to P4C frontend doesn't break p4c-xdp?

**Comment by mbudiu-vmw** [comment]
It's supposed to be very easy, just check out the repo and add a symlink in extensions.

**Comment by mbudiu-vmw** [comment]
Then the p4c make check will run the tests.

**Pull request merged**
