### PR TITLE
Do not toggle BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP in CMakelists.txt

### LINKED ISSUE #4147: Build errors with Boost 1.83
Hey,

since upgrading to Boost 1.83 I can't build the p4c graphs backend anymore due to the following error:
```
In file included from /usr/include/boost/multi_index/hashed_index.hpp:32,
                 from /usr/include/boost/graph/named_graph.hpp:18,
                 from /usr/include/boost/graph/adjacency_list.hpp:36,
                 from /home/jkhsjdhjs/aur/p4lang-p4c/src/p4c-1.2.4.3/backends/graphs/graphs.h:33,
                 from /home/jkhsjdhjs/aur/p4lang-p4c/src/p4c-1.2.4.3/backends/graphs/graphs.cpp:17,
                 from /home/jkhsjdhjs/aur/p4lang-p4c/src/p4c-1.2.4.3/build/backends/graphs/CMakeFiles/p4cgraphs.dir/Unity/unity_0_cxx.cxx:4:
/usr/include/boost/multi_index/detail/bucket_array.hpp: In function ‘void boost::serialization::load_construct_data(Archive&, boost::multi_index::detail::bucket_array<Allocator>*, unsigned int)’:
/usr/include/boost/multi_index/detail/bucket_array.hpp:239:19: error: there are no arguments to ‘bad_archive_exception’ that depend on a template parameter, so a declaration of ‘bad_archive_exception’ must be available [-fpermissive]
  239 |   throw_exception(bad_archive_exception());
      |                   ^~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/multi_index/detail/bucket_array.hpp:239:19: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from /usr/include/boost/multi_index/hashed_index.hpp:35:
/usr/include/boost/multi_index/detail/index_node_base.hpp: In function ‘void boost::serialization::load_construct_data(Archive&, boost::multi_index::detail::index_node_base<Value, Allocator>*, unsigned int)’:
/usr/include/boost/multi_index/detail/index_node_base.hpp:120:19: error: there are no arguments to ‘bad_archive_exception’ that depend on a template parameter, so a declaration of ‘bad_archive_exception’ must be available [-fpermissive]
  120 |   throw_exception(bad_archive_exception());
      |                   ^~~~~~~~~~~~~~~~~~~~~
```

When building without the graphs backend (`-DENABLE_P4C_GRAPHS=OFF`) it works fine, just like before. I've previously built the p4c graphs backend with Boost 1.81, which also worked fine.
Since I'm not sure whether this is a Boost bug or an incompatibility of p4c with Boost 1.83, I hope that you can give me a few pointers here. Thanks in advance!

### PR DESCRIPTION
**Pull request by fruffy**
Fixes #4147.

### CODE REVIEW

**Comment by jafingerhut** [comment]
I could approve this, but would prefer if someone closer to the C++ implementation could do so.  @chrisdodd would you have any time to take a look?  The changes are short, but not sure if thinking about the possible consequences of the change are.

**Comment by fruffy** [comment]
> I could approve this, but would prefer if someone closer to the C++ implementation could do so. @ChrisDodd would you have any time to take a look? The changes are short, but not sure if thinking about the possible consequences of the change are.

I do not know who is qualified to review these types of PRs at this point.

**Comment by jafingerhut** [comment]
@vlstill Do you have some expertise in the files affected here such that you might be able to give this a thoughtful review?

**Review by vlstill — APPROVED** [review]
Seems like these were all workarounds for some pretty old GCC bugs. Since the comment mentions GCC 4.8 and since this compiles and passes test with GCC 9.4 (which is almost the oldest supported) I guess it is safe to delete the workarounds now. As for the boost macro, that should be safe too, there should be no real conflict between the `get` versions.

It would be nice to have at least basic unit test for `get` though.

**Review by vlstill — APPROVED** [review]

**Pull request merged**
