### PR TITLE
Fix handling of keys without name annotation in graphs

### PR DESCRIPTION
**Pull request by vlstill**
Currently if a key without a `@name` annotation is generated by midend the graph backend fails on SIGSEGV. Furthermore, if multiple annotations were to appear, the graph output would be wrong. This fixes both cases, using the `expression->toString()` as fallback to `@name` annotation.

### CODE REVIEW

**Comment by vlstill** [comment]
... that is the result of the test before the changes, now it passes of course.

**Comment by MichalKekely** [comment]
Added 1 more fix to the same files - using "const bool &" in the Graph_visitor class was pointless and caused problems when creating objects

**Comment by mbudiu-vmw** [comment]
The test is never invoked in the CI scripts, would you consider adding that?
(same for the previous test you added.)

**Comment by mbudiu-vmw** [comment]
I can help explain how that's done in other backends.

**Comment by MichalKekely** [comment]
> The test is never invoked in the CI scripts, would you consider adding that? (same for the previous test you added.)

Would renaming it to "*-bmv2" suffice? (I guess then it should be picked up by CMakeLists for bmv2)

**Comment by mbudiu-vmw** [comment]
Today the tests are only run by p4test. Renaming it as -bmv2 would also compile with p4c-bm2-ss.
But what you want is to compile with p4-graphs. 
How a test is run is described in the makefile by a "driver". Usually the driver calls a python script.
There is currently no python script that runs p4-graphs.
Perhaps the simplest example I can give you is from a different project I am working on:
https://github.com/vmware/nerpa/blob/ofp4/ofp4/CMakeLists.txt
These are the relevant lines in the makefile:
```

# Program used to run tests
set(OF_DRIVER ${P4C_SOURCE_DIR}/extensions/ofp4/run-of-test.py)

# Tests to run
set (OF_TEST_SUITES "${CMAKE_CURRENT_SOURCE_DIR}/tests/*.p4")
p4c_add_tests("of" ${OF_DRIVER} "${OF_TEST_SUITES}" "${OF_XFAIL_TESTS}")
```
In your case you would replace "extensions/ofp4/run-of-test.py" with another script that you write, which would just invoke p4c-graphs on the input file and return the status of that command.

**Comment by vlstill** [comment]
I'll try to enable that, how do you suggest we match the graph tests, maybe just glob for `*graph*.p4` in `testdata/p4_16_samples/` & ` testdata/p4_14_samples/`?

**Comment by mbudiu-vmw** [comment]
that could be a good way to do it

**Comment by vlstill** [comment]
@mbudiu-vmw, I have added a very minimalist test driver for graph (it just runs p4c-graph with whatever arguments are passed to the driver) and activated it on the test added here & in #3312. I have checked that these tests pass & that the one introduced here fails if I revert 0d38b42eece1c32428876326ac915803236da79a.

**Comment by mbudiu-vmw** [comment]
I assume you have run `make check-graph`.

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by vlstill** [comment]
I did run ` ctest -V -R graph` but I have just checked `make check-graph` runs the same tests and works the same.

**Comment by vlstill** [comment]
@mbudiu-vmw, I am kind of clueless of what happened in the CI. Do you have any idea what could have caused the failure on `dpdk/testdata/p4_16_samples/pna-example-tcp-connection-tracking.p4` which was in no way changed and neither is it picked by the new graph target... Is there any other source the test could have came from?

**Comment by mbudiu-vmw** [comment]
I think we have the same failure in the CI without this PR.
Can you please fix this by running the respective test with the -f flag and submit the modified files?
This is probably because we merged some PRs that weren't rebased on main.

**Comment by vlstill** [comment]
OK, I have rebased & regenerated the p4.spec file

**Pull request merged**
