### PR TITLE
Three minor changes

### PR DESCRIPTION
**Pull request by ChrisDodd**
These relate to #367, in that they are minor cleanups that help with it, plus a test case that is problematic.

The ability to disable the SideEffectOrdering pass is a bit of a hack -- it is problematic in that it introduces too many unneeded copies that are too hard to get rid of, and isn't really necessary for most targets.  It should probably be a midend pass rather than a frontend pass in the first place.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
This pass does many important things, including making sure that the evaluation order is the one specified by the language. It takes care of many corner cases. Many subsequent passes assume that these corner cases do not happen; for example, arguments to calls never alias after this pass, so the inliner can be much simpler.

The SideEffectOrdering pass is the only pass which was specific to P4 v1. The PR #367 makes this pass independent on the source language.

Previously we could skip this pass for P4 v1 because we knew these corner cases cannot be expressed in P4-14. In general it should not be disabled for P4-16 programs - that's why it is in the front-end.

**Comment by mbudiu-vmw** [comment]
Please note that #367 causes the side-effect ordering to introduce many fewer copies. In fact, it will never introduce copies for P4-14 programs.

**Comment by ChrisDodd** [comment]
#367 introduces more copies for P4_14 programs, which is the problem.  Particularly it introduces extra copies for parser lookahead.

**Comment by mbudiu-vmw** [comment]
In general the copies are necessary to correctly generate code for bmv2. The language supports expressions which are too complicated for bmv2 to handle directly in select expressions, e.g.:
`select(a.b, p.lookahead<H>().x)`

In general, the back-end should be prepared to handle lookahead that reads into temporaries.
I think that the right approach is to teach the copy propagation pass about lookahead.

There are also some subtle issues related to exceptions and how much you readahead.

**Pull request merged**
