### PR TITLE
Fixes for issues #364 #376 and #377

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
I didn't mean to change anything there, but the rebase asked me to accept some changes.
What do I have to revert?

**Comment by cc10512** [comment]
```
git checkout master
git submodule update --init
git checkout <your_branch>
git rebase master
```

**Comment by mbudiu-vmw** [comment]
These git submodules are making the situation even more complicated.
We tried to avoid them.

**Comment by mbudiu-vmw** [comment]
I cannot checkout master, because I have another pending PR in master.

**Comment by mbudiu-vmw** [comment]
I cannot rebase on master; my master has been used for submitting another PR.
I was handling the master of my fork as a branch, but I see that it's not really working.

**Comment by sethfowler** [comment]
If you have `p4lang/p4c` as a remote in your repo, you can rebase against it; it doesn't matter if you local version of `master` is different. For example, if the remote is called `p4lang` (and assuming your current branch is `mbudiu-vmw:bugfixes`), you could do:

```
git fetch p4lang
git rebase -i p4lang/master
```

**Comment by ChrisDodd** [comment]
In yout case, it would be

get fetch upstream/master
git rebase -i upstream/master
...delete all the spurious merge/rebase commits from the list, leaving only
the real commits you want to keep
git push -f

You'll probably want to do the same on your local/forked master to bring it
back into sync with upstream at some point

**Comment by sethfowler** [comment]
To move the stuff on your `master` branch into its own branch, you can do:

```
git checkout master                          # Switch to your local master branch.
git checkout -b my_new_branch      # Create a new 'my_new_branch' branch
                                                           # which points at the same comment.
git checkout master                         # Switch back to your local master branch.
git reset --hard upstream/master   # Make your local master branch point to the same commit
                                                           # as the 'upstream' remote's master branch. Based on what
                                                           # Chris said, it sounds like that's the name you've used for this
                                                           # repo; if not, substitute the real remote name. Note that if you
                                                           # have any uncommitted changes, this will delete them!
git push -f origin master                  # Now your local master branch is correctly, so push the
                                                           # change to your Github fork. (I assume the remote for
                                                           # your fork is called 'origin', which is the default.)
```

Now your changes are on the `my_new_branch` branch and your master branch is back in sync with upstream.

**Comment by mbudiu-vmw** [comment]
Actually I notice that Chris has merged my PR, so I can now use my master branch in the right way.

**Comment by sethfowler** [comment]
Make sure that your master branch and the master branch from this repo point to the same commit. If not, you should fix it now before it causes you any more trouble.

**Comment by mbudiu-vmw** [comment]
You should add instructions to the README about properly handling the submodules, in the section about git here: https://github.com/p4lang/p4c/blob/master/docs/README.md

**Comment by mbudiu-vmw** [comment]
I hope that this version will work out.

**Comment by mbudiu-vmw** [comment]
The git website seems out of sync; I got a comment from @ChrisDodd by email, but it does not appear in this thread. I will submit a fix for cpplint after running the tests again.

**Pull request merged**
