### PR TITLE
 Deprecate .txt, support in favour of .txtpb. 

### LINKED ISSUE #4066: Support `.textproto` extension for output files in Protobuf Text Format
The official file extension for Protobuf Text Format files is `.textproto`: https://protobuf.dev/reference/protobuf/textformat-spec/#text-format-files

But IIUC, currently p4c  requires `.txt` instead in a bunch of places, e.g. to generate P4infos or table entry files.

Today:
```
    p4test --arch v1model \
        --p4runtime-files p4info.txt \
        --p4runtime-entries-files entries.txt \
        table-entries-ternary-bmv2.p4
```

Proposed:
```
    p4test --arch v1model \
        --p4runtime-files p4info.textproto \
        --p4runtime-entries-files entries.textproto \
        table-entries-ternary-bmv2.p4
```

The proposal is to start supporting `.textproto` and, optionally, to slowly phase out support for `.txt`, e.g. by initially giving a warning and eventually failing with an error.

@jafingerhut for visibility, as this came up in my review of https://github.com/p4lang/p4runtime/pull/432.

### PR DESCRIPTION
**Pull request by fruffy**
Ran into this so might as well fix it. 

Fixes #4066. 

First commit has the actual changes, second commit updates the reference files, third commit updates the DPDK and PSA back ends, too.

### CODE REVIEW

**Comment by fruffy** [comment]
> Is it intentional to delete all *.p4 file in the directory testdata/p4_16_bmv_errors, and a few other directories?

Considering the tests pass, yes. It looks like these are stale error files which have never been cleaned up.

**Comment by jafingerhut** [comment]
> > Is it intentional to delete all *.p4 file in the directory testdata/p4_16_bmv_errors, and a few other directories?
> 
> Considering the tests pass, yes. It looks like these are stale error files which have never been cleaned up.

The reason I ask is that some files with suffix `.p4` are source files for unit tests, so deleting those files would eliminate those unit tests, and not cause any test failures.

There are other files with suffix `.p4` that are expected output files to be checked against actual output files during tests, and deleting those (without also deleting the corresponding source `.p4` files) _would_ case test failures.

I am not sure which category the ones in directory `testdata/p4_16_bmv_errors` fall under.

**Comment by smolkaj** [comment]
This is a really nice quality of life improvement, thanks for the change!

**Comment by fruffy** [comment]
> > > Is it intentional to delete all *.p4 file in the directory testdata/p4_16_bmv_errors, and a few other directories?
> > 
> > 
> > Considering the tests pass, yes. It looks like these are stale error files which have never been cleaned up.
> 
> The reason I ask is that some files with suffix `.p4` are source files for unit tests, so deleting those files would eliminate those unit tests, and not cause any test failures.
> 
> There are other files with suffix `.p4` that are expected output files to be checked against actual output files during tests, and deleting those (without also deleting the corresponding source `.p4` files) _would_ case test failures.
> 
> I am not sure which category the ones in directory `testdata/p4_16_bmv_errors` fall under.

Oh I see what you mean. Long day, will fix this.

**Review by jafingerhut — APPROVED** [review]
After commit 3 on this PR I see many changes files in `testdata` subdirectories with `_outputs` in their names, and only in those directories, which makes me much more confident that no test cases have been changed or removed.  Looks good to me.  Given the number of places you found that `.txt` needed updating to `.txtpb`, I wouldn't be surprised if there might be another one in there lurking somewhere, but if so, it probably isn't being tested in CI.

**Pull request merged**
