### PR TITLE
Add psa specific metadata to bmv2 psa_switch backend

### PR DESCRIPTION
**Pull request by alexwong**
Changelog:
Add psa specific metadata to the psa_switch backend in accordance with https://github.com/jafingerhut/p4-guide/blob/master/psa-examples/README-psa-implementation.md.

Test:
All tests passed in travis on fork

### CODE REVIEW

**Comment by jafingerhut** [comment]
I do not have any comments on the C++ code changes themselves, as I am not terribly familiar with the code there.

I have run p4c-bm2-psa with these changes on psa-example-drop-all.p4, and inspected the BMv2 JSON file produced, and it does not have what looks like the correct contents for the 7 PSA header types and headers.  Nice.

It does not yet compile psa-unicast-or-drop.p4 without error, but I expect that this change represents progress, and it is OK if later changes get that one compiling correctly.

**Comment by alexwong** [comment]
> I have run p4c-bm2-psa with these changes on psa-example-drop-all.p4, and inspected the BMv2 JSON file produced, and it does not have what looks like the correct contents for the 7 PSA header types and headers. Nice.

Just want to make sure that this was a typo and it does print the 7 PSA header types and headers. I just compiled above and it looks to do so on my local build.

> It does not yet compile psa-unicast-or-drop.p4 without error, but I expect that this change represents progress, and it is OK if later changes get that one compiling correctly.

Ah, I just tried to compile this as well and it looks like there is a compile error. Because my next goals involve getting some of the things in this program compiling correctly (mainly assign and other statements referencing the new header), I agree that later commits will probably address this.

**Comment by jafingerhut** [comment]
That "not" in my first paragraph was definitely a typo.  Sorry for the confusion.

**Comment by jafingerhut** [comment]
Given Calin's approval, and since this only affects PSA back end of compiler, I am merging this in.

**Pull request merged**
