### PR TITLE
Initial support for arbitrary externs on bmv2

### PR DESCRIPTION
**Pull request by engjefersonsantiago**
Dear all,

I have implemented the initial support to extern instances in the bmv2 backend compiler. I have tested with P4-16 and P4-14. It is functional with P4-16, but I've seen an issue with P4-14, where the instantiation parameters are not being taken.

Regards,
Jeferson

### CODE REVIEW

**Comment by hanw** [comment]
Thanks, I have an upcoming patch that already implemented this feature as part of a larger refactoring. Would you mind holding on to this till I merged the refactor in? Then you can modify the refactored backend instead.

**Comment by engjefersonsantiago** [comment]
Not problem. I'll wait then.

Regards,
Jeferson

**Comment by mbudiu-vmw** [comment]
We should define an annotation (`@userextern`), which indicates that an extern is provided by the user.
Then the warning becomes an error if the annotation is missing.

**Comment by hanw** [comment]
@engjefersonsantiago It is going to be difficult for you rebase this pull request, given the most recent refactor. I suggest you re-apply your changes to the refactor bmv2 backend code.  Sorry for the trouble.

**Comment by engjefersonsantiago** [comment]
@hanw, maybe it will be a bit easier for you to check if your implementation fully contains my patch. Your changes have more than 6k LOC, mine is just 50 LOC.

**Comment by hanw** [comment]
Sure I will do that. Thanks.

**Comment by hanw** [comment]
Please submit a separate pull request for issue #604, I will close this one for now.

**Pull request closed without merging**
