### PR TITLE
check side effects in strength reduction; fixes #2221

### LINKED ISSUE #2221: StrengthReduction ignores side-effects in function calls
`StrengthReduction` (or `PassRepeated` in the latest version) transforms the following program:

```p4
bit<16> function_with_side_effect(inout bit<16> eth_type) {
    eth_type = 16w0x806;
    return 16w2;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        bit<16> dummy_var;
        dummy_var = 16w0 & function_with_side_effect(h.eth_hdr.eth_type);
        dummy_var = 16w0 * function_with_side_effect(h.eth_hdr.eth_type);
        dummy_var = 16w0 >> function_with_side_effect(h.eth_hdr.eth_type);
    }
}
```
into 
```p4 
bit<16> function_with_side_effect(inout bit<16> eth_type) {
    eth_type = 16w0x806;
    return 16w2;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        bit<16> dummy_var;
        dummy_var = 16w0;
        dummy_var = 16w0;
        dummy_var = 16w0;
    }
}
```
which ignores the side effects in the method-call expression.

[zero_op_with_side_effects.p4.txt](https://github.com/p4lang/p4c/files/4276248/zero_op_with_side_effects.p4.txt)
[zero_op_with_side_effects.stf.txt](https://github.com/p4lang/p4c/files/4361525/zero_op_with_side_effects.stf.txt)

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by fruffy** [comment]
There is also || and && that is missing I think.
I guess I could go all the way and check all expressions with this.

**Comment by fruffy** [comment]
[2221.p4.txt](https://github.com/p4lang/p4c/files/4361806/2221.p4.txt)
[2221.stf.txt](https://github.com/p4lang/p4c/files/4361807/2221.stf.txt)

Alright these tests should cover enough for now

**Comment by mbudiu-vmw** [comment]
`||` and `&&` have short-circuit evaluation by definition.
You should probably submit additional tests as a PR rather than as attachments to an issue.

**Comment by fruffy** [comment]
Ah right. I forgot about short-circuiting. My bad.

**Pull request merged**
