### PR TITLE
Make {#} a single token

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>
As discussed during the January 2023 LDWG meeting.
https://github.com/p4lang/p4-spec/pull/1184 will have to be updated.
This PR also refactors the IR to make it easier to add invalid header unions in a future PR.

### CODE REVIEW

**Review by jafingerhut — APPROVED** [review]
LGTM

**Comment by jafingerhut** [comment]
Note that my approval is for the grammar and lexer parts, not the rest of the C++ implementation, which I am not qualified to review at this time.

Question: Is it overkill to add a test case with white space in the middle to verify that it gives an error, e.g. "h1 = { # };" ?

**Comment by mbudiu-vmw** [comment]
Added a negative test.

**Comment by jafingerhut** [comment]
Thanks for the negative test case.  My approval still stands.

**Pull request merged**
