### PR TITLE
fixes for issue 1350

### PR DESCRIPTION
**Pull request by hanw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
We have never merged PR #1289. Maybe we should. @hanw : can you take a look at it?

**Comment by isaac-ped** [comment]
I seem to be getting the same error as before. If I define an extern function in the p4 file, which is not explicitly defined as an extern in the backed, it still fails:
```
error: Unknown extern function extern_fn
extern void extern_fn(inout bit<16> hdr);
            ^^^^^^^^^
```
Is this what was supposed to be changed?

**Comment by hanw** [comment]
Can you attach your program please?

**Comment by hanw** [comment]
This PR does not handle extern function, extern function is handled in #1289, which has not been merged.

**Comment by isaac-ped** [comment]
Ah - sorry. Did not realize what this was targeting. Running similar code with an extern object/method instead results in the same issue, if that is what this fix was for:

```
test.p4(48): error: Unknown extern method update from type ExternObj
    void update(inout bit<16> t);
         ^^^^^^
test.p4(46)
extern ExternObj {
       ^^^^^^^^^
```

With code containing:
```
extern ExternObj {
    ExternObj();
    void update(inout bit<16> t);
}

**Comment by hanw** [comment]
@isaac-ped try again?

**Comment by isaac-ped** [comment]
Working perfectly now!

**Pull request merged**
