### PR TITLE
Make the tree cloner also clone Member(TypeNameExpression) to ensure the result is a DAG

### PR DESCRIPTION
**Pull request by mihaibudiu**

### CODE REVIEW

**Comment by mihaibudiu** [comment]
Fixes #4500

**Review by kfcripps — COMMENTED** [review]
Now, `ClonePathExpressions` does not clone only `PathExpression`s. Should we change its name (and update the comment above the class definition) to reflect this?

**Comment by mihaibudiu** [comment]
I will let other people do the desired cleanups.

**Comment by kfcripps** [comment]
Done. @fruffy I don't want to approve my own changes so please approve if the second commit looks good to you. The first commit LGTM. Thank you @mihaibudiu for fixing this.

**Comment by fruffy** [comment]
ArrayIndices may also be relevant here.

**Review by fruffy — APPROVED** [review]

**Pull request merged**
