### PR TITLE
Validate headers type for v1model

### LINKED ISSUE #1672: bmv2 backend fails header generation sometimes
Please use the p4c in the URL below which is being used as a repo for PR to add boolean to P4 header.

https://github.com/hesingh/p4c-1

Use the test in testdata/p4_16_sample/header-bool-bmv2.p4.  Run the test as shown below and see the error where the arrow is "<===".  The error is from P4Objects.cpp in the behavioral model which fails to find the hdr or h in the output json. 

```
hemant@ubuntu:~/p4c-1/build$ bmv2/testdata/p4_16_samples/header-bool-bmv2.p4.test -b -v
Writing temporary files into  ./tmp9tR5ek
Executing  ./p4c-bm2-ss -o bmv2/testdata/p4_16_samples/header-bool-bmv2.json /home/hemant/p4c-1/testdata/p4_16_samples/header-bool-bmv2.p4
Exit code  0
Check for  /home/hemant/p4c-1/testdata/p4_16_samples/header-bool-bmv2.stf
Running model
Running /home/hemant/behavioral-model/targets/simple_switch/simple_switch --log-file switch.log --log-flush --use-files 0 --thrift-port 9124 --device-id 34 ../bmv2/testdata/p4_16_samples/header-bool-bmv2.json
Calling target program-options parser
Invalid reference to object of type 'header' with name 'h' <===
Running /home/hemant/behavioral-model/targets/simple_switch/simple_switch_CLI --thrift-port 9124
STF Command: 
Could not connect to thrift client on port 9124
Make sure the switch is running and that you have the right port
Exception  [Errno 3] No such process
hemant@ubuntu:~/p4c-1/build$ 

```

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #1672

### CODE REVIEW

**Comment by hesingh** [comment]
Any reason, we don't catch the issue in frontend code?

Also, I'd like to see normative text in the P4-16 spec where the v1model.p4 restrictions are specified.   I don't see the P4-16 spec saying only headers, stacks or header_unions are allowed with Parser.

**Comment by antoninbas** [comment]
> Any reason, we don't catch the issue in frontend code?
> 
> Also, I'd like to see normative text in the P4-16 spec where the v1model.p4 restrictions are specified. I don't see the P4-16 spec saying only headers, stacks or header_unions are allowed with Parser.

If it's architecture-specific, there isn't really a way to catch it in the frontend. I also don't see why the v1model.p4 architecture should be documented in the P4_16 spec. The lack of documentation for v1model.p4 has indeed been a major pain point, but I don't think it belongs in the language spec. @jafingerhut has written some documentation for simple_switch, which is also applicable to v1model: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

**Comment by hesingh** [comment]
ok, got it - thanks.

**Comment by jafingerhut** [comment]
Here is a PR proposing documenting the restriction that the P4_16 type parameter `H` in v1model.p4 must only contain header, header stacks, and header_union members.  https://github.com/p4lang/behavioral-model/pull/701

Certainly more can be written documenting the details of the v1model architecture than that, but I'm going about it piece-by-piece as I learn about those restrictions myself.

**Comment by hesingh** [comment]
@jafingerhut Thanks!

**Pull request merged**
