### PR TITLE
Fixes for Graph generation for switch(t.apply().action_run)

### PR DESCRIPTION
**Pull request by MichalKekely**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
How about a test.

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by MichalKekely** [comment]
> How about a test.

Done, test added

**Comment by mbudiu-vmw** [comment]
Running ./p4c-graphs with this test would fail before this fix?

**Comment by MichalKekely** [comment]
> Running ./p4c-graphs with this test would fail before this fix?

Yes

**Pull request merged**
