### PR TITLE
Fix clang_format mismatch.

### PR DESCRIPTION
**Pull request by fruffy**
Also fix pip package versions using a requirements.txt file.

### CODE REVIEW

**Comment by fruffy** [comment]
@mbudiu-vmw There are unrelated PRs failing because this check is missing. I also fixed all Python dependencies. Could you give this a review?

**Comment by mbudiu-vmw** [comment]
What should we do about #3810?

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by fruffy** [comment]
Thanks! Regarding #3810 the clang-format file is not broken, it's just a different pointer alignment. I am indifferent about the style as long as it is consistent.

**Comment by mbudiu-vmw** [comment]
We always used the other pointer style.

**Pull request merged**
