### PR TITLE
Eliminate typedefs when resolving constructor type declaration

### LINKED ISSUE #3952: Typedef constructor doesn't work
See the example below. Correct me if I'm wrong, but I think this should work. A fix is on the way.

```p4
#define V1MODEL_VERSION 20200408

#include <core.p4>
#include <v1model.p4>

// Main test code

typedef bit<10> my_counter_index_t;
typedef counter<my_counter_index_t> my_counter_t;

control Test() {
    // This compiles:
    counter<my_counter_index_t>(1024, CounterType.packets_and_bytes) counter_set_1;

    // But this doesn't:
    my_counter_t(1024, CounterType.packets_and_bytes) counter_set_2;

    apply {
        counter_set_1.count(42);
        counter_set_2.count(42);
    }
}

// Boilerplate code

struct header_t {}
struct metadata_t {}

parser MyParser(
    packet_in pkt,
    out header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t std_meta
) {
    state start {
        transition accept;
    }
}

control MyVerifyChecksum(
    inout header_t hdr,
    inout metadata_t meta
) {
    apply {}
}

control MyIngress(
    inout header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t std_meta
) {
    apply {
        Test.apply();
    }
}

control MyEgress(
    inout header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t std_meta
) {
    apply {}
}

control MyComputeChecksum(
    inout header_t hdr,
    inout metadata_t meta
) {
    apply {}
}

control MyDeparser(
    packet_out pkt,
    in header_t hdr
) {
    apply {
        pkt.emit(hdr);
    }
}

V1Switch(
    MyParser(),
    MyVerifyChecksum(),
    MyIngress(),
    MyEgress(),
    MyComputeChecksum(),
    MyDeparser()
) main;
```

### PR DESCRIPTION
**Pull request by qobilidop**
This fixes #3952.

### CODE REVIEW

**Comment by qobilidop** [comment]
I need some guidance on adding test code. Should I add a sample code to testdata and/or add some unit tests somewhere?

**Comment by mbudiu-vmw** [comment]
To add a new test just copy the file to the directory testdata/p4_16_samples, then run `cmake` (with the appropriate arguments), and then run the newly generated test to generate the outputs: `./p4/testdata/p4_16_samples/yourtest.p4.test -f`.
The add to this commit all the new files in testdata.

**Comment by mbudiu-vmw** [comment]
If you feel extra zealous you can also add this procedure to the README. It should be there. Thank you.

**Comment by qobilidop** [comment]
I'll update README in another PR, just to keep this one focused on fixing the issue.

**Review by mbudiu-vmw — APPROVED** [review]

**Pull request merged**
