### PR TITLE
Fix circular dep in includes

### PR DESCRIPTION
**Pull request by antoninbas**

### CODE REVIEW

**Comment by antoninbas** [comment]
@teverman FYI

**Comment by antoninbas** [comment]
@teverman I updated my commit to add a fwd declaration for Backend and move the constructor to the cpp file. What I'm worried about is that I don't seem to be catching these errors when I run my "non-unified" build

**Comment by sethfowler** [comment]
Not sure why you wouldn't...

**Comment by antoninbas** [comment]
can I get an approve for this?

**Pull request merged**
