### PR TITLE
Bringing header stacks in conformance with latest spec.

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
git is again confused about which commits are in this PR; I will have to reset again.
I wish I could figure out that this will happen before I submit the PR.

### CODE REVIEW

**Comment by sethfowler** [comment]
FYI, the PR contains all the commits that your version of the branch has that the version in this repo doesn't. To keep the PR clean, you have to work on each PR in a separate branch.

**Comment by mbudiu-vmw** [comment]
Yes, I was working under the optimistic assumption that all these commits will be merged, since they are all fairly small and bugfixes. If it is necessary I can submit separate PRs too.

However, the first 5 commits listed in the P$ have already been merged even in your repo, so that seems to be an issue with git on my side understanding this fact.

**Comment by sethfowler** [comment]
They're "different" commits from git's point of view because the SHA is different, which is a consequence of the fact that you're merging upstream/master into your branch. If you rebase your branch onto upstream/master, rather than merging, you'll avoid that problem.

**Comment by ChrisDodd** [comment]
merged as 76d35a5

**Comment by jnfoster** [comment]
Thanks Mihai!

**Comment by mbudiu-vmw** [comment]
What is the recommended git command to do that?

I have tried various versions of rebase with no success so far.

**Pull request closed without merging**
