### PR TITLE
Add P4_14 test program for header stack operations

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Normally we expect a check-in to also include the reference outputs generated when running make check.

**Comment by ChrisDodd** [comment]
Looks like a more thorough test than the existing one (instruct5.p4), so maybe that one should be deprecated.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Sorry, I know I have done this before, and you have patiently explained to others how to do it before, but can you remind me what command I can run to create these files and leave them on disk after the command is complete?  If it as straightforward as "cd build ; make check" and look in the testdata/p4_14_samples_output/ directory for the appropriately named files, then no need to respond, as I will find it soon.

**Comment by mbudiu-vmw** [comment]
Yes, after a `make check` you will find that you have some new files in `testdata/p4_*_outputs`, just add these files to the repository using `git add --all ../testdata`.

**Comment by jafingerhut** [comment]
I added the desired reference output files for the new test.

In this run, there are 4 failing tests that seem to have nothing to do with my additions, since I did not change the compiler code.  Not sure if there are intermittent failures on the Travis machines used to do testing for some known reasons?

**Comment by antoninbas** [comment]
@jafingerhut See #1250

**Comment by mbudiu-vmw** [comment]
Shouldn't this build have passed after we merged the uninitialized variable fix?

**Comment by cc10512** [comment]
Did you rebase?

**Comment by jafingerhut** [comment]
I have not rebased after the fix was made to p4c.  I will try that, and hopefully the tests will re-run and pass.

**Pull request merged**
