### PR TITLE
Fix off-by-one bug in ebpf backend mask computation

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Fixes #2791

**Comment by hesingh** [comment]
Does it make sense to add a tuple P4 test with don't care element in tuple?

**Comment by mbudiu-vmw** [comment]
Sure, please create one.

**Comment by hesingh** [comment]
> Sure, please create one.

Please add this parser state to your existing test.  I haven't compiled this code. thanks.
```p4
state ip {
        p.extract(headers.ipv4);
	transition select(headers.ipv4.protocol, diffserv) {
	(_, _) : accept;
        default : reject;
    }
```

**Comment by mbudiu-vmw** [comment]
This is a correct observation, the pass that eliminates multi-argument selects fails with partial "default" labels.

**Comment by mbudiu-vmw** [comment]
We should file a new issue for this case.

**Comment by hesingh** [comment]
> We should file a new issue for this case.

https://github.com/p4lang/p4c/issues/2816

**Comment by hesingh** [comment]
Just curious where is the tuple eliminated?

**Comment by mbudiu-vmw** [comment]
The pass is called SingleArgumentSelect, but it is not general enough unfortunately.

**Comment by mbudiu-vmw** [comment]
Maybe we should modify it to produce a value and a mask always

**Comment by hesingh** [comment]
> Maybe we should modify it to produce a value and a mask always

Makes sense.

**Comment by hesingh** [comment]
I tested the Gergely (without his  don't care tuple) code and it works - thanks.

**Comment by mbudiu-vmw** [comment]
This is a 1-line change really, should be very easy to review.

**Review by hanw — APPROVED** [review]

**Pull request merged**
