### PR TITLE
Fix for issue #1079

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Bug report and solution contributed by @ygottlieb-vencorelabs-com

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
It turns out that parser_dc_full.stf will actually work for this case.
I know because the first attempt to fix this bug made that test case crash.

**Comment by cc10512** [comment]
But obviously was not correctly covering this case, no? Otherwise how come it was passing before you fixed the bug?

**Comment by mbudiu-vmw** [comment]
Before fixing this bug we were generating no condition for the checksum verify/update, so it was always unconditional. Note that BMv2 may still skip the verify/update if the field list contains fields of an invalid header (the actual semantics in bmv2 when some fields are invalid and some are not is not clear).

**Comment by antoninbas** [comment]
@mbudiu-vmw if the target field is invalid, there will be no verify / update
if a field list contains fields of an invalid header, these fields will be skipped when computing the checksum and will therefore not contribute to the checksum
if all fields are invalid, the checksum will be 0

**Comment by debatgithub** [comment]
When a register section is defined in a p4 file and compiled with p4_16,
the resulting json doesn't have any reference to it.
Has the registers/meters/counters support totally disappeared from p4_16?
Or is there a back door to re-enable it?

**Comment by mbudiu-vmw** [comment]
Can you provide a test example?
We have several tests in testdata/*/*.p4 which use registers.

**Pull request merged**
