### PR TITLE
Add PINS examples to test suite.

### PR DESCRIPTION
**Pull request by fruffy**
These are some of the examples taken from https://github.com/sonic-net/sonic-pins/tree/main/sai_p4/instantiations/google. They are complex switch models written for v1model.p4. They can serve as good test examples for BMv2 and the simple-switch back end.

### CODE REVIEW

**Comment by jfingerh** [comment]
No expected output files?

**Comment by fruffy** [comment]
> No expected output files?

Done. Anything else I should add?

**Review by jafingerhut — APPROVED** [review]
LGTM.  Even though my specialty is reviewing test programs and expected outputs, I only gave these a fairly quick overview.  The test program would take me over an hour to review in detail, if I was trying to look for p4c bugs.  I do believe that this is a useful addition to the test suite, given how few P4 programs of this size we have in the test suite, and it is useful to add new ones, especially if they are under active maintenance (in their own home repos, at least).

**Review by rst0git — APPROVED** [review]
LGTM

**Comment by fruffy** [comment]
@pkotikal This is also a small PR. We are just adding the PINS programs to our open-source test suite.

**Review by pkotikal — APPROVED** [review]

**Comment by fruffy** [comment]
Thanks!

**Pull request merged**
