### PR TITLE
Add canonical base types to typemap; fixes #1806

### LINKED ISSUE #1806: Table Key as Slice Expression fails P4Runtime Serialization due to minWidthBits
If the following line of code is changed, one can reproduce the bit slices issue of gtestp4c failing.

https://github.com/p4lang/p4c/blob/master/control-plane/p4RuntimeSerializer.cpp#L666

Change the above line to use `typeMap->minWidthBits(matchFieldType, matchFieldType->getNode());`

gtestp4c is run by invoking `test/ptestp4c` from the p4c/build path. 

In the log, this is the first failure.

```
unknown file: Failure
C++ exception with description "In file: /tmp/p4c/frontends/p4/ typeMap.cpp:84
[31mCompiler Bug[0m: Could not find type for <Type_Bits>(959116) bit<10>
" thrown in the test body.
[  FAILED  ] P4Runtime.P4_16_MatchFields (553 ms)
```

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
I don't know why this didn't cause any problems so far.

### CODE REVIEW

**Comment by hesingh** [comment]
Code changes LGTM - thanks.

**Comment by hesingh** [comment]
> I don't know why this didn't cause any problems so far.

I think because no one tested a table key as a bit Slice.

**Comment by mbudiu-vmw** [comment]
there are tests with table keys that are slices.; for example pvs-struct.p4.

**Comment by mbudiu-vmw** [comment]
this has nothing to do with slices; it is about type_bits not having a pointer in the typemap that points to a canonical representation of itself. this can happen for other operators as well, like concatenation.

**Comment by hesingh** [comment]
> pvs-struct.p4

The single table key in pvs-struct.p4 is not a Slice.  

`key = { meta.data[0].da : exact;}`

**Comment by hesingh** [comment]
> this has nothing to do with slices; it is about type_bits not having a pointer in the typemap that points to a canonical representation of itself. this can happen for other operators as well, like concatenation.

Sorry, I don't understand.  If a table key is type_bits, it does have a Type_Type and Type_Type->type is type_bits.  This is why getTypeType passes with such a table key.  It's the Slice that failed.

**Comment by hesingh** [comment]
Next round of Travis failed due to use of `error` in two tests:

```
The following tests FAILED:
	655 - p4/testdata/p4_16_samples/issue1062-1-bmv2.p4 (Failed)
	702 - p4/testdata/p4_16_samples/issue1304.p4 (Failed)
```

My PR (https://github.com/p4lang/p4c/pull/1792) does not when I have incorporated the typeChecker.cpp changes of this PR into mine.  

We could move the two tests to p4_16_errors.

**Comment by jafingerhut** [comment]
If they are failing due to having table search keys that are type `error`, then another possibility is to mark them XFAIL, pending future compiler and P4Runtime changes that enable table search keys of those type to work.

**Comment by hesingh** [comment]
> If they are failing due to having table search keys that are type `error`, then another possibility is to mark them XFAIL, pending future compiler and P4Runtime changes that enable table search keys of those type to work.

It's not a table key.  metadata is using an `error`

**Comment by hesingh** [comment]
Sorry, my bad.  The metadata `error` is used as a table key.  I saw the `error` first in the metadata and reported that.

**Comment by hesingh** [comment]
I am familiar with the p4c compiler.  Latest round of diffs look good.  However, my code review vote does not count.  Another person would have to approve.   Thanks.

**Comment by hesingh** [comment]
@antoninbas: Please review the p4runtime code changes of this PR.  thanks.

**Pull request merged**
