### PR TITLE
Added changes for default hit actions for tc backend

### PR DESCRIPTION
**Pull request by Sosutha**
* Updated tc_may_override hint to be used with default_hit actions

* Added testcases for tc_may_override hint with default_hit action

### CODE REVIEW

**Review by komaljai — APPROVED** [review]

**Comment by Sosutha** [comment]
@fruffy Could you approve this PR, PR is reviewed and approved from P4TC contributor. Need approval from a reviewer with merge access to merge the PR

**Review by psivanup — APPROVED** [review]
Looks fine to me

**Comment by fruffy** [comment]
> @fruffy Could you approve this PR, PR is reviewed and approved from P4TC contributor. Need approval from a reviewer with merge access to merge the PR

I have invited komaljai to have write access to approve PRs.

**Review by komaljai — APPROVED** [review]

**Comment by jafingerhut** [comment]
@Sosutha Out of curiosity, is there any public documentation, perhaps planned to be included in https://github.com/p4lang/p4c/blob/main/backends/tc/README.md, or linked to from that README, that explains the meanings and restrictions on use of these p4tc-specific annotations?

+ `@tc_type`
+ `@tc_may_override`
+ `@default_hit`
+ `@default_hit_const`
+ `@tc_acl`
+ `@nummask`

I may have missed some, but from some grep'ing through the test programs in testdata/p4tc_samples, those are the ones that I did not recognize as part of the language spec, nor in any public documentation I have come across so far.

**Comment by Sosutha** [comment]
> @Sosutha Out of curiosity, is there any public documentation, perhaps planned to be included in https://github.com/p4lang/p4c/blob/main/backends/tc/README.md, or linked to from that README, that explains the meanings and restrictions on use of these p4tc-specific annotations?
> 
> * `@tc_type`
> * `@tc_may_override`
> * `@default_hit`
> * `@default_hit_const`
> * `@tc_acl`
> * `@nummask`
> 
> I may have missed some, but from some grep'ing through the test programs in testdata/p4tc_samples, those are the ones that I did not recognize as part of the language spec, nor in any public documentation I have come across so far.

Right now, we do not have any public documentation. But we have plan to add one soon

**Pull request merged**
