### PR TITLE
typedef with generic types requires type arguments

### LINKED ISSUE #3170: Error message for checking of types inside header does not say what the specialization is location is
Take:
```
header yy
{
  bit tt;
}
struct y
{
  yy[2] tt;
}
header t<tt>
{
  tt y;
}

typedef t ty;
typedef ty<y> tty;
```
Right now the compiler outputs:
```
t2.p4(11): [--Werror=type-error] error: Field 'y' of 'header t' cannot have type 'struct y'
  tt y;
     ^
t2.p4(5)
struct y
       ^
```
But it does not reference the last typedef line for the subsitution that had happened so it is not obvious where the problem is located.
I suspect this is an issue with most places of subsitutions too include functions.

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

Fixes #3170

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Fixes #3172 
... by just forbidding the example.

**Comment by apinski-cavium** [comment]
Is this even invalid because the specification is not clear here.

**Comment by apinski-cavium** [comment]
Actually I think it should be invalid, though the specifications should be clear too.

**Comment by jnfoster** [comment]
I agree this was a compiler bug. Can you point out where the spec is unclear? In the example program that illustrated the bug, I'd argue a generic without its type arguments isn't really a type.

**Comment by mbudiu-vmw** [comment]
That generic is something like a function that takes some type arguments and returns a type. Not really a type, indeed.
I think that both behaviors are reasonable (the previous one, and the current one), but since no one asked for this feature I think it's safe to not allow it.

**Comment by mbudiu-vmw** [comment]
So, can anyone approve this PR?

**Review by jnfoster — APPROVED** [review]

**Comment by jnfoster** [comment]
My pleasure.

**Pull request merged**
