### PR TITLE
Add test of v1model update_checksum implementation

### PR DESCRIPTION
**Pull request by jafingerhut**
It does not test the verify_checksum implementation.

### CODE REVIEW

**Comment by jafingerhut** [comment]
The new P4 program only compiles with the new v1model checksum APIs added via this commit: https://github.com/p4lang/p4c/commit/f09a95dcda68ca18a1528be6a63a16f2b8074d46

but later reverted on 2017-Aug-28.

**Comment by mbudiu-vmw** [comment]
There should already be a few tests with stf files that exercise the checksums in bmv2.
But more tests are always better.

**Comment by jafingerhut** [comment]
@mbudiu-vmw I found only one P4_16 test program in the p4c/testdata/p4_16_samples program where there is checksum calculation code, _and_ there is an .stf file to specify input packets, and expected output packets that check for the correct checksum being computed.  That is issue655-bmv2.p4 and issue655-bmv2.stf.  It only calculates checksums for a single 16-bit field.

The test program and .stf file proposed in this PR calculate the IPv4 header checksum over an entire 20-byte IPv4 header, plus a test packet that has 24-bit IPv4 header with options, parsed into a varbit field with a non-0 length.  Thus this test should be adding a little bit of functional coverage not already covered by other tests.

**Comment by jafingerhut** [comment]
@cc10512 I have tried making the changes you suggested -- thanks for file name and line number pointers to guide me.  We'll see what the Travis build thinks of these changes in a bit.

**Pull request merged**
