### PR TITLE
DPDK: add support for h.setValid and h.setInvalid

### PR DESCRIPTION
**Pull request by hanw**
pretty straightforward translation.
`h.setValid() -> validate h`
`h.setInvalid() -> invalidate h`

### CODE REVIEW

**Comment by hesingh** [comment]
What about adding support for isValid()?

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by hesingh** [comment]
Later, please also think about adding support for isHit() and isActionRun() - thanks.

**Comment by hanw** [comment]
> 
> 
> What about adding support for isValid()?

isValid() is already supported.

**Comment by hanw** [comment]
> 
> 
> Later, please also think about adding support for isHit() and isActionRun() - thanks.

Will do.

**Pull request merged**
