### PR TITLE
Disallow Type_Control as a tuple argument

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Fixes #3750

**Review by jafingerhut — APPROVED** [review]
LGTM.  As usual I am reviewing the test programs and expected outputs.

**Comment by apinski-cavium** [comment]
Thanks for the fix. I also get the same compiler bug with:
```
extern ct
{
  void f();
}
void f(tuple<ct> t)
{
  t[0].f();
}
```
As Type_Extern is not a Type_ArchBlock nor a IContainer.

**Review by rst0git — APPROVED** [review]
LGTM

**Pull request merged**
