### PR TITLE
Update first paragraph of README to no longer say alpha-quality

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
The new sentences in this proposed README change for p4c is based upon Calin's comment here: https://github.com/p4lang/p4c/issues/2080#issuecomment-552155749

I believe it would be good to require that Calin approve this PR before it is merged in, to ensure that I haven't overstated anything here.  Calin, I'm happy to modify this PR if you have any suggested changes to it.

**Comment by cc10512** [comment]
Thanks Andy!

**Comment by jnfoster** [comment]
+1!

**Comment by jafingerhut** [comment]
I see approvals from a good set of folks, so going ahead and merging this in.

**Pull request merged**
