### PR TITLE
Load support for ir enum map when --fromJSON is used (#1784)

### PR DESCRIPTION
**Pull request by vidakjelena**
*Modifed convertEnums to save user defined enums in program
instead of removing them.

*Added pass fillEnumMap, which is called in reduced midEnd branch,
that fills enumMap

Signed-off-by: Jelena Vidakovic <jelena.vidakovic@rt-rk.com>

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
This seems to have failed because the switch.p4 test took more than 10 minutes and Travis terminated the job.

**Comment by mbudiu-vmw** [comment]
If you can rebase and rerun I hope this will succeed and then I plan to merge this.

**Comment by vidakjelena** [comment]
Hello,
I updated PR. According to Travis results on previous version of my PR, I found out that on OSX it behaves different, I test it, and on my Mac machine that I used for testing and it doesn't fail. Just in case, I supported for Linux, for now.  In meantime I will figure out what the problem with this result is for OSX and update if I manage.

**Comment by mbudiu-vmw** [comment]
The behavioral model simulator changes frequently.

**Pull request merged**
