### PR TITLE
crash.cpp: Register names fixed for building under Cygwin.

### PR DESCRIPTION
**Pull request by DoctorNoobingstoneIPresume**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Can you give a reference for how this feature works in cygwin?

**Comment by DoctorNoobingstoneIPresume** [comment]
> Can you give a reference for how this feature works in cygwin?

In the Cygwin installation:

File `/usr/include/cygwin/signal.h`:

```
...
#ifdef __x86_64__
...
struct __attribute__ ((aligned (16))) __mcontext
{
...
  __uint64_t rax;
  __uint64_t rcx;
  __uint64_t rdx;
  __uint64_t rbx;
  __uint64_t rsp;
  __uint64_t rbp;
  __uint64_t rsi;
  __uint64_t rdi;
  __uint64_t r8;
  __uint64_t r9;
  __uint64_t r10;
  __uint64_t r11;
  __uint64_t r12;
  __uint64_t r13;
  __uint64_t r14;
  __uint64_t r15;
...
};

#else /* !x86_64 */

struct __mcontext
{
...
  __uint32_t edi;
  __uint32_t esi;
  __uint32_t ebx;
  __uint32_t edx;
  __uint32_t ecx;
  __uint32_t eax;
  __uint32_t ebp;
...
  __uint32_t esp;
...
};

#endif /* !x86_64 */
...
```

File `/usr/include/sys/ucontext.h`:

```
...
typedef struct __mcontext mcontext_t;

typedef __attribute__ ((aligned (16))) struct __ucontext {
	mcontext_t	uc_mcontext;
	struct __ucontext *uc_link;
	sigset_t	uc_sigmask;
	stack_t	uc_stack;
	unsigned long int	uc_flags;
} ucontext_t;
...
```

In `p4c` project:

File `lib/crash.cpp`:

```
static void dumpregs(mcontext_t *mctxt) {
...
    LOG1(" eax=" << hex(mctxt->mc_eax, 8, '0') <<
...
```

This is correct for Linux, but for Cygwin we should replace `mc_eax` with `eax` etc. as per `mcontext_t` (i.e. `__mcontext`) definition above.

**Comment by mbudiu-vmw** [comment]
This also fails the check with cpplint.

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by DoctorNoobingstoneIPresume** [comment]
> This also fails the check with cpplint.

Thank you for checking. I hope that now I have fixed it to pass the current version of `cpplint.py`.

**Pull request merged**
