### PR TITLE
Rename all params in FindParameters pass

### PR DESCRIPTION
**Pull request by amreshk**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Let's see if these tests pass.

**Comment by amreshk** [comment]
Seeing fails on name mismatch due to the pass now renaming all the action params,

```
-    @name(".setb1") action setb1_2(bit<8> val, bit<9> port) {
-        hdr.data.b1 = val;
-        standard_metadata.egress_spec = port;
+    @name(".setb1") action setb1_2(bit<8> val_1, bit<9> port_1) {
+        hdr.data.b1 = val_1;
+        standard_metadata.egress_spec = port_1;
```

**Comment by fruffy** [comment]
Should the original name be preserved with an annotation? Are there any control plane programs relying on the name? Also this is missing the example program.

**Comment by jfingerh** [comment]
action parameter names are represented in P4Info files that P4Runtime API controller software has full access to all of its contents, including the parameter names, as a (partial) description of the P4 program.

For example, this action in this p4c test program: https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples_outputs/action-two-params.p4#L46
```
    action actTbl(bit<24> id, bit<32> ip) {
    }
```
is represented by this part of the P4Info file generated by p4c.  Note the "id" and "ip" names, which are intended to match the original action parameter names.  (I do not recall whether P4_16 supports @name annotations on action parameters, but if so, then those annotated names should override the one in the P4 source code.): https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples_outputs/action-two-params.p4.p4info.txt#L33
```
actions {
  preamble {
    id: 23137650
    name: "MyIngress.actTbl"
    alias: "actTbl"
  }
  params {
    id: 1
    name: "id"
    bitwidth: 24
  }
  params {
    id: 2
    name: "ip"
    bitwidth: 32
  }
}
```

**Comment by jfingerh** [comment]
@fruffy My previous comment does not definitively answer your question: "Are there any control plane programs relying on the name?", but it is extremely easy for a P4Runtime API controller to examine the P4Info file and examine names there, and to rely on particular names existing there, and/or to use names to help distinguish the semantics of which action parameters mean what.

**Comment by jfingerh** [comment]
I should also add that the P4Info file is today generated not at the end of the last midend compiler pass.  If I recall correctly, it is generated from the IR of the input P4 program at the end of the last front end pass, before the first mid end pass.  Generating a correct expected P4Info file thus puts several constraints on what a front end pass is allowed to do.

**Comment by fruffy** [comment]
Thanks, I was wondering about that. The runtime [relies](https://github.com/p4lang/p4c/blob/master/control-plane/p4RuntimeSerializer.cpp#L962) on [externalName](https://github.com/p4lang/p4c/blob/1b5722bbe2fc94db19c28f74069aa4982788c83b/ir/declaration.h#L36) to get a parameter name, but that uses annotations. I am surprised it works after the FrontEnd transformation. Annotations can also be used with parameters, but it is a little ugly.

**Comment by mbudiu-vmw** [comment]
The `@name` annotations are for P4 source code and programmers.
The compiler also maintains internally the original name of each identifier to use in error reporting and in code generation.
If you look at the ID class you will notice that it has two strings inside: the current and original name.
The rules for disambiguation of identifiers are really dependent on the context. For example, in P4 identifiers in the same scope have to be disambiguated, but in the P4Runtime API the names of local variables are irrelevant, but action parameter names matter.

**Comment by mbudiu-vmw** [comment]
The reference outputs are expected to change.
However, the p4info files should probably not change. If they do this is a problem.

**Comment by amreshk** [comment]
Added the testcase from issue #2710 

The p4info has the original param name `value`,

```
  actions {
    preamble {
      id: 20299687
      name: "MyIC.wrapper.wrapped.set"
      alias: "set"
    }
    params {
      id: 1
      name: "value"
      bitwidth: 8
   }
 }

```

**Comment by mbudiu-vmw** [comment]
It looks like this does not work. The code generated for BMV2 will have the new action argument names in some instances, and the control plane will report an error when using the original names.

**Comment by mbudiu-vmw** [comment]
The right solution is for the compiler to use a `@name` annotation on action arguments and for the back-ends and the control plane to honor that. But I don't know if they do.

**Comment by mbudiu-vmw** [comment]
I think I have a working solution, I will post it in a separate PR. It is based on this PR, with a few small changes for bmv2.

**Comment by mbudiu-vmw** [comment]
Included in #2715

**Comment by mbudiu-vmw** [comment]
I assume it's ok to close this.

**Comment by amreshk** [comment]
yes, thank you.

**Pull request closed without merging**
