### PR TITLE
Disable 'unused' warning for some psa.p4 externs

### LINKED ISSUE #3145: Unused types in extern definitions
Since commit https://github.com/p4lang/p4c/commit/8eebedea818a2c788e0675d052a170be904a8e7f, the compiler shows warnings such as:

```
/usr/local/share/p4c/p4include/bmv2/psa.p4(546): [--Wwarn=unused] warning: 'W' is unused
extern Counter<W, S> {
               ^
/usr/local/share/p4c/p4include/bmv2/psa.p4(575): [--Wwarn=unused] warning: 'W' is unused
extern DirectCounter<W> {
                     ^
```
As far as I understand, in the definition for the extern `DirectCounter` in PSA, `W` is used to set the width of values used by the control plane API.

Would it make sense to add an annotation that can be used to specify parameters used the control plane API to suppress this warning?

For example, something like:

```P4
@ControlPlaneAPI(W)
extern DirectCounter<W> {
  DirectCounter(PSA_CounterType_t type);
  void count();

  /*
  @ControlPlaneAPI
  {
    W    read<W>      (in TableEntry key);
    W    sync_read<W> (in TableEntry key);
    void set          (in TableEntry key, in W seed);
    void reset        (in TableEntry key);
    void start        (in TableEntry key);
    void stop         (in TableEntry key);
  }
  */
}
```

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

Fixes #3145

### CODE REVIEW

**Comment by rst0git** [comment]
@mbudiu-vmw Thank you for fixing this!

Should we update both `dpdk/psa.p4` and `bmv2/psa.p4`?

**Review by rst0git — APPROVED** [review]
LGTM

**Comment by mbudiu-vmw** [comment]
There are some unused arguments in pna.p4.
@jafingerhut I see this:
```
control MainControlT<PM, MH, MM>(
    //in    PM pre_user_meta,
    inout MH main_hdr,
    inout MM main_user_meta,
    in    pna_main_input_metadata_t  istd,
    inout pna_main_output_metadata_t ostd);
```
which is why PM is unused. Can we just delete PM from the type parameters?

**Comment by mbudiu-vmw** [comment]
I really don't understand why these runs failed. I downloaded myself this version and rerun the command that was reported to fail and it worked fine: ` ./dpdk/testdata/p4_16_samples/pna-dpdk-parser-state-err.p4.test`

**Comment by mbudiu-vmw** [comment]
@rst0git could you please try just the test above in this branch to see what happens?
I am very puzzled why it failed.

**Comment by rst0git** [comment]
@mbudiu-vmw When I run the test locally it passes. I'm not able to replicate the error.

From the CI logs it looks like `pna-dpdk-parser-state-err.p4-error` has not been updated, but I can see the change in the pull request.
```
1873/2232 Test  #108: dpdk/testdata/p4_16_samples/pna-dpdk-parser-state-err.p4 .......................................***Failed    1.69 sec
--- /__w/p4c/p4c/testdata/p4_16_samples_outputs/pna-dpdk-parser-state-err.p4-error	2022-03-24 18:17:49.647840883 +0000
+++ ./tmpv25t3jqe/pna-dpdk-parser-state-err.p4-error	2022-03-24 19:00:34.055518498 +0000
@@ -1,12 +0,0 @@
-pna.p4(373): [--Wwarn=unused] warning: 'W' is unused
-extern Counter<W, S> {
-               ^
-pna.p4(380): [--Wwarn=unused] warning: 'W' is unused
-extern DirectCounter<W> {
-                     ^
-pna.p4(673): [--Wwarn=unused] warning: 'PM' is unused
-parser MainParserT<PM, MH, MM>(
-                   ^^
-pna.p4(680): [--Wwarn=unused] warning: 'PM' is unused
-control MainControlT<PM, MH, MM>(
-                     ^^
./p4c-dpdk --dump ./tmpv25t3jqe -o ./tmpv25t3jqe/pna-dpdk-parser-state-err.p4.spec --arch pna --bf-rt-schema ./tmpv25t3jqe/pna-dpdk-parser-state-err.p4.bfrt.json /__w/p4c/p4c/testdata/p4_16_samples/pna-dpdk-parser-state-err.p4
```


Would it be possible to move the changes for PNA in a separate PR?

**Review by rst0git — APPROVED** [review]

**Pull request merged**
