### PR TITLE
Run Gauntlet validation, sanitizers, and Ubuntu 18 build/test as nightly actions.

### PR DESCRIPTION
**Pull request by fruffy**
Save some CI resources on PRs.

### CODE REVIEW

**Review by jafingerhut — APPROVED** [review]
LGTM.  I guess the resource you are most concerned with reducing here is the time spent waiting while the diffs in a PR are tested?

**Comment by fruffy** [comment]
@jnfoster The PR is blocked because `validate` is a required run. Can you disable it? In general, we should update the required CI runs.

**Comment by jafingerhut** [comment]
@jnfoster Do you know who the set of people is that has authorization to make the required steps for this to pass CI checks?

If it does not include @fruffy, I would be in favor of adding him to that set.  Also anyone else you think would make sense to add to that set.

**Comment by fruffy** [comment]
> After discussing with the (informal) p4c maintainers, I've bumped up @fruffy's privileges on this repository. He should be able to modify CI configuration settings now.

Thank you!

**Pull request merged**
