### PR TITLE
Remove 6 unneeded fields from v1model standard_metadata

### PR DESCRIPTION
**Pull request by jafingerhut**
drop and recirculate_port were never used by BMv2 simple_switch, least
not in any git commit logs I can find, and they have been marked so in
the v1model.p4 include file for several months now.

clone_spec, lf_field_list, resubmit_flag, and recirculate_flag have
been documented for a while now as internal implementation details of
BMv2 simple_switch, and should never be modified by a P4 program's
code.  There is also no functional reason to read them in a P4
program.  As of a recent change to BMv2 simple_switch code, these
fields need not be present in standard_metadata any longer in order
for simple_switch to work correctly.

### CODE REVIEW

**Comment by jafingerhut** [comment]
There is 0 urgency to merge this.  I simply wanted to create the PR while I was thinking of it.  It would fix https://github.com/p4lang/p4c/issues/1845

The changes to behavioral-model that make it no longer necessary to include the 4 fields in standard_metadata were only committed recently (2019-Apr-25 here https://github.com/p4lang/behavioral-model/commit/7cd8d683517739c51ecf807d1919f4f118e349db ).  It would make sense to me if folks wanted to let the dust settle a little while longer on such a change before merging this one (if it is ever desired to merge this one).

Only one test file was removed: clone-bmv2.p4, because it used the clone_spec field in a way that seemed somehow essential to the test.  Preserving the value of the clone_spec field explicitly seems to me exactly what the documentation of simple_switch recommended against: writing the value of the clone_spec field in the user's P4 program.

**Comment by jafingerhut** [comment]
I agree that v1model.p4 changes have that ripple effect, but at least right now the only expected output files that need updating if line numbers within v1model.p4 changes can have their expected output files updated with these commands in a p4c/build directory:
```
./p4/testdata/p4_16_samples/issue841.p4.test -f
./err/testdata/p4_16_errors/issue1541.p4.test -f
./err/testdata/p4_16_errors/issue513.p4.test -f
```
Most p4c PRs do not touch v1model.p4, and pretty much independent of ones that do touch it.

**Comment by mbudiu-vmw** [comment]
@jafingerhut : you will need to rebase this branch.
I hope that the other fixes to v1model which I just merged will pass tests...

**Comment by jafingerhut** [comment]
@mbudiu-vmw Rebase complete, with tests passing.  Only a few minor updates to expected outputs were necessary to get them to pass again, some to the v1model.p4 line numbers, some to compiler-generated intermediate names of things.

**Pull request merged**
