### PR TITLE
Add STF tests of P4_16 header stack operation behavior

### PR DESCRIPTION
**Pull request by jafingerhut**
I have tested this with the version of p4lang/behavioral-model after this commit: https://github.com/p4lang/behavioral-model/commit/5d3e2f2bbeb4434941236712847dce0f62c9b398

and the tests only produce the expected results, which I believe are correct according to the P4_16 language spec, if you build simple_switch after running configure for behavioral-model with this option:
```
./configure --enable-WP4-16-stacks
```

### CODE REVIEW

**Comment by antoninbas** [comment]
One more reason to wait for 1.11: the bmv2 docker image which is used for running the Travis CI tests doesn't use `--enable-WP4-16-stacks` (since it is not the default yet).

**Comment by jafingerhut** [comment]
It seems reasonable to me to wait until behavioral-model release 1.11.0, when these tests should pass with the default build options for behavioral-model, before merging this new test in.

**Comment by antoninbas** [comment]
Maybe this test should be merged and tagged as XFAIL? Then we will just need to remove it from the XFAIL list when bmv2 1.11 is released.

**Comment by jafingerhut** [comment]
Tried adding this new test to XFAIL list, but Travis testing still runs it.  Maybe I didn't mark the test XFAIL correctly?  If I did it correctly, then something weird is going on to cause Travis to run the test anyway.

**Comment by mbudiu-vmw** [comment]
The test should be run, but it should not cause a failure.

**Comment by mbudiu-vmw** [comment]
There are two tests run for each p4 file: one with p4test and one with bmv2.
You have added the xfail to the wrong makefile.
You have to use the backends/bmv2 makefile.

**Comment by jafingerhut** [comment]
@mbudiu-vmw "The test should be run, but it should not cause a failure."

If you meant "I've looked at the new test, and it should pass with the latest versions of p4c and behavioral-model code", then I disagree.  Some of packet-in/packet-out behavior relies upon changes to behavioral-model in how P4_16 push and pop primitives are implemented, that are not planned to be the default behavior until behavioral-model 1.11 is released in the future.

If you meant "We should not merge in changes that cause 'make check' to fail", then we are in agreement, hence marking the new test XFAIL.

**Comment by jafingerhut** [comment]
@mbudiu-vmw I modified the test P4_16 program so that it no longer works around already-fixed issue #1127.

**Comment by jafingerhut** [comment]
If the new behavioral-model 11.1 will avoid all of the failures, what benefit is there in splitting up the test cases?

It might be possible to write a different P4_16 test program that exhibits the issue #1128, with or without the changes coming in behavioral-model release 11.1, i.e. a program that has a parser calling a sub-parser, passing a header stack as an inout parameter.

**Comment by jafingerhut** [comment]
I have created an STF test case in a PR that I believe demonstrates issue #1128, and its behavior will not be affected by releasing behavioral-model 1.11: https://github.com/p4lang/p4c/pull/1132

**Comment by mbudiu-vmw** [comment]
If we merge this the build will (hopefully) fail when the bmv2 simulator is updated.
What should be do?

**Comment by jafingerhut** [comment]
I am perfectly happy to wait to merge this after behavioral-model 1.11 is released, and change this PR at that time to remove the new test from XFAIL, since it should then pass.

**Comment by mbudiu-vmw** [comment]
Yes, and your example from https://github.com/p4lang/p4c/pull/1132 will not generate legal JSON anymore with my recent PR: https://github.com/p4lang/p4c/pull/1133. We have to wait for support from bmv2.

**Comment by mbudiu-vmw** [comment]
We should merge this after #1144.

**Comment by antoninbas** [comment]
bmv2 1.11.0 has been released and `--enable-WP4-16-stacks` is now the default.
It will take some time for the new bmv2 docker image to build, but after that the Travis regression for this PR should be restarted - and hopefully it will pass.

**Comment by antoninbas** [comment]
Looks like the new docker image has been built and uploaded to docker hub. I'm restarting the Travis job now.

**Comment by antoninbas** [comment]
@jafingerhut @mbudiu-vmw the test is passing, can we merge?

**Comment by mbudiu-vmw** [comment]
This is great!
Thank you.

**Comment by jafingerhut** [comment]
@antoninbas Good to see that these tests are passing, as expected, and yes they are good to merge.

**Pull request merged**
