### PR TITLE
Apply clang-format to ir and lib files.

### PR DESCRIPTION
**Pull request by fruffy**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Many of my PRs now fail because I forgot to reformat the code.
This is a big waste of CI resources.
I really think you should not be allowed to push of the code is not formatted.

**Comment by fruffy** [comment]
clang-format is part of the [git hook](https://github.com/p4lang/p4c/blob/main/tools/hooks/pre-commit#L73) script, but it is optional and has to be installed manually. I do not think there is a straightforward way to make this automatically part of P4C's commit flow.

**Comment by fruffy** [comment]
The issue is largely the same as the ref files, but for linting you will get feedback early now.

We could make it so that linting has to pass first before tests are run, but sometimes you do not care about linting.

**Comment by rst0git** [comment]
> clang-format is part of the git hook script, but it is optional and has to be installed manually. I do not think there is a straightforward way to make this automatically part of P4C's commit flow.

It should be possible to run clang-format in our CI. Here is an example of how it is used in another open-source project:
https://github.com/checkpoint-restore/criu/blob/criu-dev/.github/workflows/lint.yml

**Review by mbudiu-vmw — APPROVED** [review]

**Pull request merged**
