### PR TITLE
Construct bitvec from integer types larger than uintptr_t

### PR DESCRIPTION
**Pull request by ChrisDodd**
This uses some template/enable_if magic to only do the overload if there exists a type larger than uintptr_t -- if uintptr_t and uintmax_t are the same, then a simple overload would fail, and just defining for uintmax_t would have trouble with shifts being out of range.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
This looks fine, but I really don't have a deep understanding of the bitvec code so I can't tell for sure. Moreover, I believe that none of the tests we have in the public repo exercise this code. Maybe you want to write some unit tests?

**Comment by ChrisDodd** [comment]
This code will be excercised if you build with -m32 (or on a 32-bit machine), but on a normal 64 bit machine (with 64 bit intmax_t), these additions are a noop.

**Comment by mbudiu-vmw** [comment]
The question is "which compiler pass uses bitvecs"?

**Comment by ChrisDodd** [comment]
Hmm -- looks like the frontend doesn't use bitvecs anywhere -- they're only used in private backends.  But they are generally useful.

**Pull request merged**
