### PR TITLE
BMv2: fix hashing non-tuple causing segfault

### PR DESCRIPTION
**Pull request by Trigary**
Currently, attempting to hash (via the v1model hash extern) a field that is not a tuple will result in a segmentation fault. This PR fixes that issue: the correct, intended error message is displayed instead.

Snippet used for testing:
```p4
bit<8> output;
hash(output, HashAlgorithm.crc16, (bit<8>) 0, (bit<8>) 42, (bit<8>) 255);
```

Current output:
```
$ p4c-bm2-ss mytest.p4 -o mytest.json
Segmentation fault
```

Output with this PR's modifications:
```
$ p4c-bm2-ss mytest.p4 -o mytest.json
mytest.p4(123): [--Werror=legacy] error: 8w42: expected a struct
hash(output, HashAlgorithm.crc16, (bit<8>) 0, (bit<8>) 42, (bit<8>) 255);
                                                       ^^
error: Are you using an up-to-date v1model.p4?
```

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Can you please also supply a test case? A file named -bmv2.p4 ought to work.

**Comment by Trigary** [comment]
I have added a test file, but I'm afraid it's far from ideal:
 - Test cases in the `p4_16_bmv_errors` folder pass even if a segmentation fault happens during the compilation.
 - I was unable to get this test case to work in the `p4_16_errors` / `p4_16_errors_outputs` folders. I believe the reason is that those test cases are executed with the `p4test` backend, but the error generation logic I'm trying to test is in the `bmv2` backend.

**Comment by mbudiu-vmw** [comment]
The file should not be in "errors", since it is supposed to compile fine.
After adding the new test file type 'cmake ..' (or whatever cmake command you used to compile), then run the new test generating the reference outputs:
`./p4/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4.test -f`

Then commit all the new files generated (git add ../testdata).

**Comment by Trigary** [comment]
Is the file supposed to compile fine? This PR fixes a segmentation fault by not passing a `nullptr` to the `::error(...)` method (in the `modelError` invocation of `helpers.cpp`), meaning that `::error` is called. When compiling the file the `p4c-bm2-ss` process' return value is non-zero and an error message (shown at the bottom of my original PR "comment") is also displayed. Or am I misunderstanding something?

Nevertheless, I have tried doing what you suggested:
 - Move `testdata/p4_16_bmv_errors/hashing-non-tuple-bmv2.p4` to `testdata/p4_16_samples`
 - Ran `./p4/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4.test -f`
 - Then tested the results via `ctest --output-on-failure -R 'hashing-non-tuple-bmv2'`

The result is that the 1 out of the 2 tests failed: (`hashing-non-tuple-bmv2.p4-stderr` gets generated, but it's empty)
```
user@TRIG-LT:~/ProgrammingLinux/p4c/build$ ./p4/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4.test -f
./p4test --pp ./tmp1zhvmmwp/hashing-non-tuple-bmv2.p4 --dump ./tmp1zhvmmwp --top4 FrontEndDump,FrontEndLast,MidEndLast --testJson --maxErrorCount 100 --arch v1model --p4runtime-files ./tmp1zhvmmwp/hashing-non-tuple-bmv2.p4.p4info.txt --p4runtime-entries-files ./tmp1zhvmmwp/hashing-non-tuple-bmv2.p4.entries.txt /home/user/ProgrammingLinux/p4c/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4
./p4test -I. --pp ./tmp1zhvmmwp/hashing-non-tuple-bmv2.p4-x --std p4-16 ./tmp1zhvmmwp/hashing-non-tuple-bmv2.p4 --maxErrorCount 100
./p4test -I. --pp ./tmp1zhvmmwp/hashing-non-tuple-bmv2-midend.p4-x --std p4-16 ./tmp1zhvmmwp/hashing-non-tuple-bmv2-midend.p4 --maxErrorCount 100
user@TRIG-LT:~/ProgrammingLinux/p4c/build$ ctest --output-on-failure -R 'hashing-non-tuple-bmv2'
Test project /home/user/ProgrammingLinux/p4c/build
    Start  506: bmv2/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4
1/2 Test  #506: bmv2/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4 ...***Failed    0.79 sec
Error compiling
/home/user/ProgrammingLinux/p4c/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4(18): [--Werror=legacy] error: 8w42: expected a struct
        hash(output, HashAlgorithm.crc16, (bit<8>) 0, (bit<8>) 42, (bit<8>) 255);
                                                               ^^
error: Are you using an up-to-date v1model.p4?

*** Test failed

    Start 1124: p4/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4
2/2 Test #1124: p4/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4 .....   Passed    0.98 sec

50% tests passed, 1 tests failed out of 2

Label Time Summary:
bmv2    =   0.79 sec*proc (1 test)
p4      =   0.98 sec*proc (1 test)

Total Test time (real) =   1.85 sec

The following tests FAILED:
        506 - bmv2/testdata/p4_16_samples/hashing-non-tuple-bmv2.p4 (Failed)
Errors while running CTest
```

**Comment by mbudiu-vmw** [comment]
Then you need to add the failing test in bmv2/CMakeLists.txt in the XFAIL_TESTS section with an explanation of why it needs to fail.

**Comment by Trigary** [comment]
Thank you for your help, I believe I have fixed the test case.

**Review by mbudiu-vmw — APPROVED** [review]

**Pull request merged**
