### PR TITLE
Update PSA include files to match recent changes in version from PSA spec

### PR DESCRIPTION
**Pull request by jafingerhut**
These are only removing obsolete comments.

### CODE REVIEW

**Comment by jafingerhut** [comment]
@usha1830 FYI.  Only removing comments, but just so you know in case it affects anything you are working on.

**Comment by jafingerhut** [comment]
@hanw would you mind giving a quick look over this and approve?  It is only comment additions and removals, this time.

**Comment by jfingerh** [comment]
@hanw These changes only (a) remove old control plane API comments from psa.p4 include files, which were never really used by anyone anyway, I am pretty sure, and confused several people by their presence, and (b) adds comments for assert and assume extern functions.  Would be great if you could take a quick scan and approve this, if it meets with your approval, so I can merge it.  Thanks.

**Review by usha1830 — APPROVED** [review]
Looks good to me

**Comment by jafingerhut** [comment]
@mbudiu-vmw Sorry for the bother.  Usha Gupta has reviewed this, and it is only changes in comments.  She does not have write access, so it appears her approval is not sufficient for me to merge this.  If you do not mind approving it, that would be appreciated.

**Review by mbudiu-vmw — APPROVED** [review]

**Pull request merged**
