### PR TITLE
Update README.md instructions for running doxygen

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
@AdarshRawat1 These changes make sense to me regarding my confusions about running doxygen.  Let me know if you see anything in these changes that is different than what you would recommend.

In particular, if we want to recommend using `cmake` with `-DENABLE_DOCS=ON`, it would be good to make those instructions work.  Right now all of my attempts to use those steps have resulted in an error message, as mentioned in this issue: https://github.com/p4lang/p4c/issues/4805

**Review by fruffy — APPROVED** [review]
Conditional approval pending @AdarshRawat1 's review.

**Comment by jafingerhut** [comment]
@fruffy I am guessing the one failing test has nothing to do with changes to the README.md.  I am leaving it there for now, in case you want to examine it and see if its root cause looks familiar to you.  I do not know why it occurred.

**Comment by fruffy** [comment]
Looks like a racecondition to me. Not quite clear why the Python lex/yacc code is sharing state here.

**Comment by jafingerhut** [comment]
@AdarshRawat1 Could you please take a look at these changes and give any comments, or suggestions for further changes, that you think of?

**Review by AdarshRawat1 — APPROVED** [review]

**Pull request merged**
