### PR TITLE
Mask strength-reduction

### LINKED ISSUE #2606: Strength-reduce masks with all 1s
`a &&& 0xFFFF` is the same as `a` when `a` has 16 bits.

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #2606

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
@fruffy : your validator claims that these programs are not equivalent. Is this a false positive?
How are you modelling the semantics of &&&? Are you using the definition from https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-cubes?

**Comment by fruffy** [comment]
This was a silly bug in my code, more specifically in table masks. It is fixed now. These are the parts that are not well tested with fuzzing.

**Review by fruffy — APPROVED** [review]
Unsure if that lets you merge those requests but I can approve some of the small, inconsequential ones, which look good to me.

**Comment by mbudiu-vmw** [comment]
No, unfortunately I think you have to have some more important role to allow me to merge my requests.
I actually don't know how you get to be in that pool or "commiters".

**Comment by jnfoster** [comment]
I think we can add @fruffy to the list of key committers based on his strong track record of past and ongoing contributions to p4c.

**Comment by fruffy** [comment]
Thanks for the invitation!

**Comment by jnfoster** [comment]
Thanks for your contributions!!

**Comment by mbudiu-vmw** [comment]
@fruffy : can you approve this again, please? It does not work retroactively.

**Comment by mbudiu-vmw** [comment]
sorry, I am wrong, it did.

**Pull request merged**
