### PR TITLE
IR/json support for bitvec fields

### PR DESCRIPTION
**Pull request by ChrisDodd**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
No unit tests?

**Comment by ChrisDodd** [comment]
Unfortunately, we don't use bitvec anywhere in the IR in p4c currently.

**Comment by mbudiu-vmw** [comment]
You can still write some unit tests using gtest for example.

**Comment by ChrisDodd** [comment]
Added a trivial gtest for the bitve i/o

**Pull request merged**
