### PR TITLE
Replace $$() with ${} in CMakeList.txt

### PR DESCRIPTION
**Pull request by boblytton**
As per suggestion by Calin

### CODE REVIEW

**Comment by boblytton** [comment]
With the fix, it looks like cpplint is now running over the P4C_UBPF_SOURCES and finding problems.
Hi @mbudiu-vmw, would you be the right person to look at them?

1009/1491 Test   #1: cpplint .......................................................................***Failed   42.70 sec
/p4c/backends/ubpf/midend.cpp:52:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
/p4c/backends/ubpf/midend.cpp:89:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/midend.cpp:134:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/target.cpp:105:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/target.cpp:125:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/target.cpp:131:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/target.cpp:131:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
/p4c/backends/ubpf/ubpfBackend.cpp:90:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfControl.cpp:58:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfControl.cpp:62:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfControl.cpp:150:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfControl.cpp:312:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfControl.cpp:331:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfControl.cpp:451:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfControl.cpp:463:  Redundant blank line at the end of a code block should be deleted.  [whitespace/blank_line] [3]
/p4c/backends/ubpf/ubpfControl.cpp:529:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfControl.cpp:627:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfControl.cpp:627:  At least two spaces is best between code and comments  [whitespace/comments] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:23:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
/p4c/backends/ubpf/ubpfDeparser.cpp:31:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:33:  public: should be indented +1 space inside class OutHeaderSize  [whitespace/indent] [3]
/p4c/backends/ubpf/ubpfDeparser.cpp:114:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:138:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:177:  At least two spaces is best between code and comments  [whitespace/comments] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:179:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
/p4c/backends/ubpf/ubpfDeparser.cpp:185:  At least two spaces is best between code and comments  [whitespace/comments] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:204:  At least two spaces is best between code and comments  [whitespace/comments] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:207:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
/p4c/backends/ubpf/ubpfDeparser.cpp:212:  At least two spaces is best between code and comments  [whitespace/comments] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:221:  Redundant blank line at the end of a code block should be deleted.  [whitespace/blank_line] [3]
/p4c/backends/ubpf/ubpfDeparser.cpp:278:  Redundant blank line at the end of a code block should be deleted.  [whitespace/blank_line] [3]
/p4c/backends/ubpf/ubpfDeparser.cpp:282:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:346:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfDeparser.cpp:356:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfModel.cpp:24:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
/p4c/backends/ubpf/ubpfParser.cpp:26:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
/p4c/backends/ubpf/ubpfParser.cpp:27:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
/p4c/backends/ubpf/ubpfParser.cpp:36:  public: should be indented +1 space inside class UBPFStateTranslationVisitor  [whitespace/indent] [3]
/p4c/backends/ubpf/ubpfParser.cpp:38:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfParser.cpp:49:  Anonymous namespace should be terminated with "// namespace"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfParser.cpp:367:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfParser.cpp:367:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
/p4c/backends/ubpf/ubpfProgram.cpp:31:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfProgram.cpp:168:  Should have a space between // and comment  [whitespace/comments] [4]
/p4c/backends/ubpf/ubpfProgram.cpp:253:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfProgram.cpp:253:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
/p4c/backends/ubpf/ubpfRegister.cpp:27:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfRegister.cpp:83:  Using C-style cast.  Use reinterpret_cast<UbpfTarget *>(...) instead  [readability/casting] [4]
/p4c/backends/ubpf/ubpfRegister.cpp:95:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfRegister.cpp:101:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfRegister.cpp:125:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfRegister.cpp:154:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfTable.cpp:27:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
/p4c/backends/ubpf/ubpfTable.cpp:29:  Do not indent within a namespace  [runtime/indentation_namespace] [4]
/p4c/backends/ubpf/ubpfTable.cpp:30:  protected: should be indented +1 space inside class UbpfActionTranslationVisitor  [whitespace/indent] [3]
/p4c/backends/ubpf/ubpfTable.cpp:35:  public: should be indented +1 space inside class UbpfActionTranslationVisitor  [whitespace/indent] [3]
/p4c/backends/ubpf/ubpfTable.cpp:116:  Anonymous namespace should be terminated with "// namespace"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfTable.cpp:171:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfTable.cpp:189:  At least two spaces is best between code and comments  [whitespace/comments] [2]
/p4c/backends/ubpf/ubpfTable.cpp:411:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
/p4c/backends/ubpf/ubpfType.cpp:25:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
/p4c/backends/ubpf/ubpfType.cpp:68:  Redundant blank line at the end of a code block should be deleted.  [whitespace/blank_line] [3]
/p4c/backends/ubpf/ubpfType.cpp:109:  Redundant blank line at the end of a code block should be deleted.  [whitespace/blank_line] [3]
/p4c/backends/ubpf/ubpfType.cpp:177:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfType.cpp:178:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
/p4c/backends/ubpf/ubpfType.cpp:234:  Namespace should be terminated with "// namespace UBPF"  [readability/namespace] [5]
Total errors found: 66

**Comment by mbudiu-vmw** [comment]
Please open an issue and assign it to @osinstom

**Comment by boblytton** [comment]
Added issue:
Fixing add_cpplint_files() statement causes lint errors #2270

**Comment by boblytton** [comment]
Closing and reopening via a different branch (rather than a fork)
see #2281

**Pull request closed without merging**
