### PR TITLE
Allow empty entries lists for tables

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Fixes #2905

**Comment by jfingerh** [comment]
It would be nice to have a test case that generates a P4Info file and a P4 entries file, and verifies the entries file contains no entries for such a table.  It probably works, but may as well exercise it with an automated test.  I can create such a test case in a separate PR after this one is merged, if you prefer.

**Review by jfingerh — APPROVED** [review]
LGTM

**Comment by mbudiu-vmw** [comment]
If you have a handy program with an empty table we can attach it to this PR.

**Comment by jfingerh** [comment]
I can create one tonight if that is soon enough to include it in this PR.

**Comment by jafingerhut** [comment]
Attached is a zip file that if you unzip it in the root directory of your p4c repo copy, while checked out on your branch, will add one test program to p4_16_samples and its expected outputs in p4_16_samples_outputs.  The test is the same as the one called table-entries-exact-bmv2.p4 except that its `const entries` list is empty.  The output file `table-entries-exact-0entries-bmv2.p4.entries.txt` is empty, as it should be.

**Comment by mbudiu-vmw** [comment]
@jfingerh added the test you supplied. Please approve if we can merge this.

**Review by jafingerhut — APPROVED** [review]
LGTM

**Pull request merged**
