### PR TITLE
DPDK Backend: Register extern support for bfrt.json

### PR DESCRIPTION
**Pull request by usha1830**
This PR adds support for register extern in bfrt.json.
A new table is emitted for the register instance. This is as expected by the p4-dpdk-target.

```
    {
      "name" : "ip.MyIC.reg",
      "id" : 369588800,
      "table_type" : "Register",
      "size" : 1024,
      "annotations" : [],
      "depends_on" : [],
      "key" : [
        {
          "id" : 65557,
          "name" : "$REGISTER_INDEX",
          "repeated" : false,
          "annotations" : [],
          "mandatory" : true,
          "match_type" : "Exact",
          "type" : {
            "type" : "uint32"
          }
        }
      ],
      "data" : [
        {
          "mandatory" : false,
          "read_only" : false,
          "singleton" : {
            "id" : 65557,
            "name" : "$REGISTER_INDEX",
            "repeated" : false,
            "annotations" : [],
            "type" : {
              "type" : "bytes",
              "width" : 16
            }
          }
        }
      ],
      "supported_operations" : ["Sync"],
      "attributes" : []
    }

```

### CODE REVIEW

**Review by mbudiu-vmw — COMMENTED** [review]
I am not really qualified to review the bfruntime changes, so I cannot approve this.
There are lots of whitespace changes, ideally these should be a separate PR, but there's no point making one one. Is this from clang-format?

**Comment by usha1830** [comment]
> I am not really qualified to review the bfruntime changes, so I cannot approve this. There are lots of whitespace changes, ideally these should be a separate PR, but there's no point making one one. Is this from clang-format?

Yes the whitespace changes are coming from clang-format

**Comment by usha1830** [comment]
Adding @swaroopsarma working on the https://github.com/p4lang/p4-dpdk-target which is consuming the output bfrt.json

**Comment by fruffy** [comment]
There are some changes to testgen, which is why some users are required as reviewers. Can you revert those changes? They seem benign.

**Comment by usha1830** [comment]
> There are some changes to testgen, which is why some users are required as reviewers. Can you revert those changes? They seem benign.

I reverted the changes in testgen directory

**Comment by usha1830** [comment]
Closing this PR as there are unrelated formatting changes after multiple runs of different versions of clang-format. Created a new [PR](https://github.com/p4lang/p4c/pull/3723) for the same with just the relevant changes.

**Pull request closed without merging**
