### PR TITLE
Use libbacktrace for stack dumps if available

### PR DESCRIPTION
**Pull request by ChrisDodd**
- Memory allocation tracing hooks to track where memory is being allocated and print summary with stack trace of each allocation site.  Used when logging in ComputeWriteSet to understand how/why it is using so much memory.

### CODE REVIEW

**Comment by ChrisDodd** [comment]
Turns out with PIE executables (which Ubuntu 20.04 uses by default), addr2line is completely broken and can't produce a useful backtrace.  The libbacktrace library from Github is a good alternative -- produces nice dumps and even deals with inlined calls, and is more efficient to boot.  We don't really want a dependency on it, but using it automatically when it is installed is a good compromise.

**Review by mihaibudiu — APPROVED** [review]

**Comment by jafingerhut** [comment]
Has anyone analyzed the reasons for the CI test failures?

**Comment by fruffy** [comment]
> Has anyone analyzed the reasons for the CI test failures?

Likely a missing include, which is why the unity builds pass. The sanitizer failure looks like a `clang` compilation issue.

**Comment by fruffy** [comment]
Test failures are because I added `GIT_SHALLOW` to the p4runtime submodule pull. This will cause issues when trying to checkout an older commit. #4096 will fix this.

**Comment by jafingerhut** [comment]
@chrisdodd Looks like 3 of the CI builds are still failing even after https://github.com/p4lang/p4c/pull/4092 was merged in last week., 2 of them related to Bazel builds.  Is this something that someone at Google might be able to help with?

**Comment by fruffy** [comment]
> @ChrisDodd Looks like 3 of the CI builds are still failing even after #4092 was merged in last week., 2 of them related to Bazel builds. Is this something that someone at Google might be able to help with?

I believe the failure is a Clang problem, since the clang build also fails. Bazel uses Clang by default iirc.

**Pull request merged**
