### PR TITLE
Implement sizeInBits

### LINKED ISSUE #1717: Develop sizeof solution until module system is available in p4c
It is better to file this new issue so that implementation discussions can take place here.  This way, the spec changes don't get cluttered with implementation details.

See spec-changes that are discussing the problem.

https://github.com/p4lang/p4-spec/issues/660
https://github.com/p4lang/p4-spec/pull/712

Right now, the implementation is focused on supporting ```type.size()```.  After a LDWG discussion, we may change the implementation.

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #1717.

### CODE REVIEW

**Comment by hesingh** [comment]
It would be good to add a nested struct to the test program and use the struct inside a header.  Test the nested struct for width_bits and also the header.  Looking at the code, the test will pass.  Still it's good to add the test.  

thanks for the quick fix.

**Comment by hesingh** [comment]
It would be also good to add sizeInBytes() to the code to save many developers from doing the math in their p4 code to get the sizeInBytes.

**Comment by hesingh** [comment]
Please also add a varbits field to a header and test.  Varbits width_bits() should be zero and compile-time.

**Comment by hanw** [comment]
Is there any useful program we could write with varbit size being zero? It would be nice if we could have a real use case for this design decision. Otherwise, I rather left it out as unspecified, and come back to it when we have a use case.

**Comment by hesingh** [comment]
This is header in a P4 program

```
header bitvec_hdr {
    row_t row;
    varbit<32> v;
}
```
During compile-time, the width_bits() of such a header will count sizeof `v` as zero.  

One has to test p4c code changes with any field allowed in a header.

**Comment by hanw** [comment]
A better example would be use sizeof varbit in a program that parse IPv4 options. I understand what the current proposal is, but I am not convinced if the proposal makes sense in practice.

**Comment by jafingerhut** [comment]
The reason I proposed that the sizeInBits/Bytes() of a header that contains varbit fields, to count the varbit fields as 0, is exactly because of a use case like defining an IPv4 header with varbit options at the end.

The most common use case I know of for wanting to do sizeInBits/Bytes is tunnel encap/decap length modification calculations.

Getting back sizeInBytes(ipv4_with_possible_options) = 20 bytes is useful in such a program (the length of an IPv4 header without the options).  If you need to include the options length in your calculation, then that can be done by explicitly storing the length of the varbits in a user-defined metadata field.

I would argue that getting back sizeInBytes(ipv4_with_possible_options) = 60 bytes is not very useful in such a program (the maximum length of an IPv4 header with longest possible options).

**Comment by hesingh** [comment]
sizeInBits has the same issue for accounting for possible ipv4 options.  I would support both sizeInBits and sizeInBytes.  Also, my preference is sizeBits and sizeBytes with no "In" - two words are better than three to type.

**Comment by hesingh** [comment]
> Is there any useful program we could write with varbit size being zero? It would be nice if we could have a real use case for this design decision. Otherwise, I rather left it out as unspecified, and come back to it when we have a use case.

Whatever long-winded or useful P4 program you write, p4c still returns zero bits for Varbits at compile-time.  So what's the use of a useful program?  This PR is dealing with compile-time Varbits only.

**Comment by hesingh** [comment]
I pulled a new p4lang/p4c workspace, patched code changes from this PR, and tested sizeof-bmv2.p4.  The test fails.  The P4 program is included below.

```
hemant@ubuntu:~/int/ttt/p4c/build$ ./p4test --std p4-16 ../testdata/p4_16_samples/sizeof-bmv2.p4
In file: /home/hemant/int/ttt/p4c/frontends/p4/typeChecking/typeChecker.cpp:144
Compiler Bug: At this point in the compilation typechecking should not infer new types anymore, but it did.

hemant@ubuntu:~/int/ttt/p4c/build$ 
```

```
#include <core.p4>

typedef bit<48>  EthernetAddress;

header Ethernet_h {
    EthernetAddress dstAddr;
    EthernetAddress srcAddr;
    bit<16>         etherType;
}

header ipv4_t {
    bit<4>  version;
    bit<4>  ihl;
    bit<6>  dscp;
    bit<2>  ecn;
    bit<16> totalLen;
    bit<16> identification;
    bit<1>  flag_rsvd;
    bit<1>  flag_noFrag;
    bit<1>  flag_more;
    bit<13> fragOffset;
    bit<8>  ttl;
    bit<8>  protocol;
    bit<16> hdrChecksum;
    bit<32> srcAddr;
    bit<32> dstAddr;
    bit<8>  sizeInBits;    
}

struct Parsed_packet {
    Ethernet_h    ethernet;
    ipv4_t        ipv4;
}

struct mystruct1 {}

parser parserI(packet_in pkt,
               out Parsed_packet hdr) {
    state start {
        bit<8> my_local = 1;
        pkt.extract(hdr.ethernet);
        hdr.ipv4.totalLen = (hdr.ethernet.sizeInBits() + hdr.ethernet.sizeInBits());
        transition select(hdr.ethernet.etherType) {
            16w0x0800: parse_ipv4;
            default: accept;
        }
    }
    state parse_ipv4 {
        bit<16> my_local = 2;
        pkt.extract(hdr.ipv4);
        transition select(hdr.ipv4.version, hdr.ipv4.protocol) {
            (4w0x4, 8w0x06): accept;
            (4w0x4, 8w0x17): accept;
            default: accept;
        }
    }
}
```

**Comment by mbudiu-vmw** [comment]
In this PR is it illegal to call sizeInBits on a header with varbits.
That's probably a bit harsh. If we follow @jafingerhut's suggestion we should also probably add a maxSizeInBits.

**Comment by hesingh** [comment]
> In this PR is it illegal to call sizeInBits on a header with varbits.
> That's probably a bit harsh. If we follow @jafingerhut's suggestion we should also probably add a maxSizeInBits.

Seem ok to do so.  

What about my note about also supporting sizeInBytes?  This way few lines of code in p4c saves P4 programmers to convert bits to bytes in all programs.

**Comment by mbudiu-vmw** [comment]
Since this is not a standard feature it is more imporant to understand how it would work than to implement if fully. If the LDWG decides we need sizeInBytes we can add it as well.

**Comment by jafingerhut** [comment]
I have no objection to adding maxSizeInBits/Bytes as a separate operation that counts varbit fields as their maximum size, rather than 0.  Off hand, it does not seem to me as useful in as many cases as the one that counts varbit as 0, but if it saves more time in discussing the options of what to do, vs. the time to implement it, then I am 100% for it :-)

**Comment by hesingh** [comment]
Agree with Andy that the other work can be a subsequent PR if the LDWG decides to do so.  thanks.

**Comment by hesingh** [comment]
I see p4c code changes to compute width_bits() for `SerEnum`, Varbits, and header stack, but no unit tests exist in the P4 program for these types.  Please add the tests.

**Comment by mbudiu-vmw** [comment]
I have added the methods minSizeInBits and minSizeInBytes to stacks as well.

**Comment by antoninbas** [comment]
@mbudiu-vmw is this PR delayed because of LDWG discussions or are you simply waiting for someone to review?
I'm asking because it would be great if `TypeMap::minWidthBits` could be used for #1736

**Comment by mbudiu-vmw** [comment]
The PR is ready for review. I don't think we need to wait for LDWG. First, it was converging to this solution, and second, we can still make changes if we don't advertise this feature in the spec.

**Comment by hesingh** [comment]
With the checked in code, if a base type in `Type_Bits` is passed to minSizeInBits(), the function causes a compiler bug.  minSizeInBits() invokes this line of code.

https://github.com/p4lang/p4c/blob/master/frontends/p4/typeMap.cpp#L307

getTypeType() calls getType() which reaches this line of code to cause the compiler bug.

https://github.com/p4lang/p4c/blob/master/frontends/p4/typeMap.cpp#L84

I have fixed the issue in my PSA 1.1 PR .  The changed code is ready for review in my PR.  See

https://github.com/p4lang/p4c/pull/1736/commits/38dd644eb813ce8b80a58af975b9f4e7726f607d#diff-85933acf29d903849fbfdece52c797ccR307

**Pull request merged**
