### PR TITLE
Update some stale DPDK error reference files.

### PR DESCRIPTION
**Pull request by fruffy**
Also make sure that the dpdk test runner throws an error when the reference file is stale.

Looks like there was some regression in the error messages, but I do not know how to fix these. 

This is yak shaving needed for #4683.

### CODE REVIEW

**Comment by jafingerhut** [comment]
@usha1830 @Sosutha Could one of you review this?

**Comment by jafingerhut** [comment]
@fruffy I am not sure of the history of these test programs, but I did notice that several of the ones updated here instantiate an extern called ipsec_accelerator, which is defined in p4c/include/dpdk/pna.p4, but not in p4c/include/pna.p4.

Perhaps a better change would be to update those test programs mentioning ipsec_accelerator to replace `#include <pna.p4>` with `#include <dpdk/pna.p4>` ?

**Comment by fruffy** [comment]
> @fruffy I am not sure of the history of these test programs, but I did notice that several of the ones updated here instantiate an extern called ipsec_accelerator, which is defined in p4c/include/dpdk/pna.p4, but not in p4c/include/pna.p4.
> 
> Perhaps a better change would be to update those test programs mentioning ipsec_accelerator to replace `#include <pna.p4>` with `#include <dpdk/pna.p4>` ?

Thanks for the tip, updated the include headers for some of the files and it looks like that was a reason for the regression.

**Review by jafingerhut — APPROVED** [review]
LGTM

**Pull request merged**
