### PR TITLE
Fix for issue #807

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by cc10512** [comment]
Are we also updating the spec to reflect this change as discussed in https://github.com/p4lang/p4-spec/issues/361?

**Comment by jafingerhut** [comment]
@cc10512 I have two issues open for p4lang/p4-spec that you might be thinking about.  Let me know if there are any other possible P4_16 spec changes you think ought to have issues created for them:

Propose documenting that methods cannot return references to stateful objects: https://github.com/p4lang/p4-spec/issues/367

Document clearly that controls and parsers cannot be passed as run-time parameters to controls/parameters: https://github.com/p4lang/p4-spec/issues/364

**Comment by jnfoster** [comment]
The bug report was for the following error message:
```
In file: p4c/midend/inlining.cpp:404
Compiler Bug: cycle.p4(18): C2 c2_0/c2 expected an instance declaration
    C2 c2 = e.get2();
```
This pull request does not modify `inlining.cpp`. That's fine, of course. But for the purposes of deepening our collective understanding of the compiler, it would be great to add a brief note describing what invariant `inlining.cpp` was incorrectly assuming and why it is now true.

**Comment by jnfoster** [comment]
It appears this fix addresses the symptom but not the root cause. See  https://github.com/p4lang/p4c/issues/807#issuecomment-319593487 for an example program that triggers the same bug but ever return a control...

**Comment by mbudiu-vmw** [comment]
The root cause is that controls were not designed to be passed around as first-class values.
We just have to tighten the type checker to prevent that kind of usage.
This fixes this reported issue, there will be other fixes for other similar issues.

**Pull request merged**
