### PR TITLE
Fix for issues #696 and #1097

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by jafingerhut** [comment]
I am guessing that if someone provided tests using STF to check whether simple_switch is doing the expected thing for registers accessed from both ingress and egress, you wouldn't mind?

**Comment by mbudiu-vmw** [comment]
We never have enough tests.
However, the semantics of a register accessed from both input and output is not clear; in particular, the interleaving of packets in the two pipelines is not specified. So I am not sure what tests one should write.

**Comment by jafingerhut** [comment]
It is pretty easy to write an STF test that for each packet, only accesses a single element of the register array, but in both ingress and egress.  It is safe to assume that for the same packet, ingress must complete before egress begins.

For different packets, agreed that the order may not be consistent, but the test can be written to avoid that issue.  Let me try to make something simple here.

**Comment by jafingerhut** [comment]
[issue1097.zip](https://github.com/p4lang/p4c/files/1564279/issue1097.zip)

I have attached a ZIP file with a P4 program and corresponding STF file that fail with the latest master version of p4c-bm2-ss, but succeed with the changes Mihai has in this pull request, because the changes in this PR do correctly include a definition for a globally defined register in the "register_arrays" section of the bmv2 JSON file, and simple_switch is processing the packets as I would expect it should.

Mihai, feel free to add these two files to your pull request if you wish.

**Pull request merged**
