### PR TITLE
Temporarily disable test which hangs

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
This addresses temporarily #1900

**Comment by mbudiu-vmw** [comment]
I just submitted a version which uses system.

**Comment by mbudiu-vmw** [comment]
I believe that this test failed because we need to merge #1899.
All this churn in the behavioral model makes it hard to synchronize. Is there a better solution - perhaps based on versioning the compiler and simulator to keep them in sync - or at least fail quickly?

**Comment by jafingerhut** [comment]
I think the main reason we have recently had several test failures in p4c because of changes in behavioral-model is due to the ongoing PSA implementation work, _plus_ the fact that several XFAIL tests were checked into p4c that were waiting on updates to behavioral-model to work.

If we instead work in this order:

+ update behavioral-model for a new feature
+ only then check in the PSA test programs that rely on the new behavioral-model feature, not as XFAIL, but as a normally working test

then this breakage should not happen as often as it has for the last week or two.

There are not many XFAIL tests for PSA left, but if we instead of making them XFAIL could leave them in the testdata directory, but somehow mark them as DONT_RUN_YET (I think there is at least one *_EXCLUDE symbol in the CMakeList.txt files somewhere for this?), then p4c test results would change less often for this reason.

**Comment by jafingerhut** [comment]
I have restarted the Travis job for this PR, which will likely pass this time (or at least should not fail because of the behavioral-model commit earlier today).

**Pull request merged**
